# Data collection

In [ ]:
!pip install gdown
import zipfile
import gdown

# Google Drive share link
url = "https://drive.google.com/file/d/1ciNCHgCjMjSTnx5PX4nhemy2e5216oDR/view?usp=drive_link"

# Download ZIP
zip_file = "dataset.zip"

print("Downloading...")
gdown.download(url, zip_file, quiet=False)

# Extract into the current directory
print("Extracting...")
with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall(".")

print("Done!")

import os

os.remove(zip_file)
print("ZIP file removed.")

## Temperature Data Historical

In [1]:
import requests
from bs4 import BeautifulSoup
import os

base_url = "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/historical/"

response = requests.get(base_url)
soup = BeautifulSoup(response.text, "html.parser")

links = [a.get("href") for a in soup.find_all("a") if a.get("href").endswith((".zip",".pdf",".txt"))]
os.makedirs("Document_Corpus", exist_ok=True)
os.makedirs("Document_Corpus/dwd_temp", exist_ok=True)
os.makedirs("Document_Corpus/dwd_temp/historical_zip", exist_ok=True)
for link in links:
    file_url = base_url + link
    file_path = os.path.join("Document_Corpus/dwd_temp/historical_zip", link)
    
    print("Downloading:", link)
    r = requests.get(file_url)
    with open(file_path, "wb") as f:
        f.write(r.content)

Downloading: TU_Stundenwerte_Beschreibung_Stationen.txt
Downloading: stundenwerte_TU_00003_19500401_20110331_hist.zip
Downloading: stundenwerte_TU_00044_20070401_20241231_hist.zip
Downloading: stundenwerte_TU_00052_19760101_19880101_hist.zip
Downloading: stundenwerte_TU_00071_20091201_20191231_hist.zip
Downloading: stundenwerte_TU_00073_20070401_20241231_hist.zip
Downloading: stundenwerte_TU_00078_20041101_20241231_hist.zip
Downloading: stundenwerte_TU_00091_20040901_20241231_hist.zip
Downloading: stundenwerte_TU_00096_20190409_20241231_hist.zip
Downloading: stundenwerte_TU_00102_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_00125_19710104_20241231_hist.zip
Downloading: stundenwerte_TU_00131_20041101_20241231_hist.zip
Downloading: stundenwerte_TU_00142_19820101_20241231_hist.zip
Downloading: stundenwerte_TU_00150_20050701_20241231_hist.zip
Downloading: stundenwerte_TU_00151_20050301_20241231_hist.zip
Downloading: stundenwerte_TU_00154_20050301_20241231_hist.zip
Downloading: stundenwerte_TU_00161_20110901_20241231_hist.zip
Downloading: stundenwerte_TU_00164_19560101_20241231_hist.zip
Downloading: stundenwerte_TU_00167_20040901_20241231_hist.zip
Downloading: stundenwerte_TU_00175_19550101_19751231_hist.zip
Downloading: stundenwerte_TU_00181_19990928_20081103_hist.zip
Downloading: stundenwerte_TU_00183_19730101_20241231_hist.zip
Downloading: stundenwerte_TU_00191_20041104_20241231_hist.zip
Downloading: stundenwerte_TU_00198_19610101_20241231_hist.zip
Downloading: stundenwerte_TU_00217_20050101_20241231_hist.zip
Downloading: stundenwerte_TU_00222_19820101_20241231_hist.zip
Downloading: stundenwerte_TU_00232_19550101_20241231_hist.zip
Downloading: stundenwerte_TU_00257_20021101_20241231_hist.zip
Downloading: stundenwerte_TU_00259_20040701_20241231_hist.zip
Downloading: stundenwerte_TU_00282_19610101_20241231_hist.zip
Downloading: stundenwerte_TU_00284_19470101_19550101_hist.zip
Downloading: stundenwerte_TU_00294_20040701_20241231_hist.zip
Downloading: stundenwerte_TU_00298_19810101_20241231_hist.zip
Downloading: stundenwerte_TU_00303_19930819_20241231_hist.zip
Downloading: stundenwerte_TU_00314_20040501_20241231_hist.zip
Downloading: stundenwerte_TU_00320_20060701_20241231_hist.zip
Downloading: stundenwerte_TU_00326_20040701_20130708_hist.zip
Downloading: stundenwerte_TU_00330_20040801_20241231_hist.zip
Downloading: stundenwerte_TU_00342_20101201_20241231_hist.zip
Downloading: stundenwerte_TU_00348_19891215_20110901_hist.zip
Downloading: stundenwerte_TU_00361_19480101_19760101_hist.zip
Downloading: stundenwerte_TU_00368_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_00377_20041001_20241231_hist.zip
Downloading: stundenwerte_TU_00379_20170901_20241231_hist.zip
Downloading: stundenwerte_TU_00390_20040701_20241231_hist.zip
Downloading: stundenwerte_TU_00399_19691201_20110801_hist.zip
Downloading: stundenwerte_TU_00400_19910101_20241231_hist.zip
Downloading: stundenwerte_TU_00403_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_00410_20040501_20200615_hist.zip
Downloading: stundenwerte_TU_00420_20070801_20241231_hist.zip
Downloading: stundenwerte_TU_00424_19610101_19810101_hist.zip
Downloading: stundenwerte_TU_00427_19730101_20241231_hist.zip
Downloading: stundenwerte_TU_00430_19860101_20210505_hist.zip
Downloading: stundenwerte_TU_00433_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_00445_20050701_20241231_hist.zip
Downloading: stundenwerte_TU_00450_20051101_20121204_hist.zip
Downloading: stundenwerte_TU_00460_19610101_20241231_hist.zip
Downloading: stundenwerte_TU_00474_19750601_19780601_hist.zip
Downloading: stundenwerte_TU_00535_20040601_20241231_hist.zip
Downloading: stundenwerte_TU_00553_19510101_19740901_hist.zip
Downloading: stundenwerte_TU_00554_19740901_20060228_hist.zip
Downloading: stundenwerte_TU_00555_20080101_20241231_hist.zip
Downloading: stundenwerte_TU_00591_19730101_20241231_hist.zip
Downloading: stundenwerte_TU_00596_19730101_20241231_hist.zip
Downloading: stundenwerte_TU_00598_19490101_19570101_hist.zip
Downloading: stundenwerte_TU_00599_19840101_19971201_hist.zip
Downloading: stundenwerte_TU_00603_20010403_20241231_hist.zip
Downloading: stundenwerte_TU_00617_20040601_20241231_hist.zip
Downloading: stundenwerte_TU_00656_19480101_20241231_hist.zip
Downloading: stundenwerte_TU_00662_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_00685_20020101_20061031_hist.zip
Downloading: stundenwerte_TU_00691_19490101_20241231_hist.zip
Downloading: stundenwerte_TU_00701_19490101_20241231_hist.zip
Downloading: stundenwerte_TU_00704_19910101_20241231_hist.zip
Downloading: stundenwerte_TU_00722_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_00755_20040601_20241231_hist.zip
Downloading: stundenwerte_TU_00757_20040601_20241231_hist.zip
Downloading: stundenwerte_TU_00760_20171201_20241231_hist.zip
Downloading: stundenwerte_TU_00766_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_00769_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_00817_20050201_20241231_hist.zip
Downloading: stundenwerte_TU_00840_19910101_20241231_hist.zip
Downloading: stundenwerte_TU_00850_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_00853_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_00856_19910101_20241231_hist.zip
Downloading: stundenwerte_TU_00860_20231001_20241231_hist.zip
Downloading: stundenwerte_TU_00863_20071001_20120403_hist.zip
Downloading: stundenwerte_TU_00867_19470101_20241231_hist.zip
Downloading: stundenwerte_TU_00876_19730101_19890101_hist.zip
Downloading: stundenwerte_TU_00879_20020101_20030611_hist.zip
Downloading: stundenwerte_TU_00880_19560101_20241231_hist.zip
Downloading: stundenwerte_TU_00891_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_00896_20040801_20241231_hist.zip
Downloading: stundenwerte_TU_00917_20040901_20241231_hist.zip
Downloading: stundenwerte_TU_00919_19580101_19720101_hist.zip
Downloading: stundenwerte_TU_00953_19550101_20241231_hist.zip
Downloading: stundenwerte_TU_00954_20000501_20241231_hist.zip
Downloading: stundenwerte_TU_00963_19940103_20241231_hist.zip
Downloading: stundenwerte_TU_00979_20040901_20230313_hist.zip
Downloading: stundenwerte_TU_00982_19760101_19780601_hist.zip
Downloading: stundenwerte_TU_00983_20061201_20241231_hist.zip
Downloading: stundenwerte_TU_00991_20050201_20241231_hist.zip
Downloading: stundenwerte_TU_01001_19810101_20241231_hist.zip
Downloading: stundenwerte_TU_01048_19730101_20241231_hist.zip
Downloading: stundenwerte_TU_01050_20060401_20241231_hist.zip
Downloading: stundenwerte_TU_01051_20070301_20230814_hist.zip
Downloading: stundenwerte_TU_01052_20040701_20241231_hist.zip
Downloading: stundenwerte_TU_01072_20040601_20241231_hist.zip
Downloading: stundenwerte_TU_01078_19760301_20241231_hist.zip
Downloading: stundenwerte_TU_01103_20061001_20241231_hist.zip
Downloading: stundenwerte_TU_01107_20041201_20241231_hist.zip
Downloading: stundenwerte_TU_01130_20020101_20050422_hist.zip
Downloading: stundenwerte_TU_01161_20050201_20241231_hist.zip
Downloading: stundenwerte_TU_01197_19480101_20241231_hist.zip
Downloading: stundenwerte_TU_01200_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_01207_20060301_20241231_hist.zip
Downloading: stundenwerte_TU_01214_20040801_20241231_hist.zip
Downloading: stundenwerte_TU_01219_19710101_19981102_hist.zip
Downloading: stundenwerte_TU_01221_19490101_19710101_hist.zip
Downloading: stundenwerte_TU_01224_20021201_20241231_hist.zip
Downloading: stundenwerte_TU_01228_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_01239_20040701_20080923_hist.zip
Downloading: stundenwerte_TU_01246_20150801_20241231_hist.zip
Downloading: stundenwerte_TU_01255_20021201_20241231_hist.zip
Downloading: stundenwerte_TU_01262_19920517_20241231_hist.zip
Downloading: stundenwerte_TU_01266_20040601_20241231_hist.zip
Downloading: stundenwerte_TU_01270_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_01279_19861101_20241231_hist.zip
Downloading: stundenwerte_TU_01297_20041001_20241231_hist.zip
Downloading: stundenwerte_TU_01300_20040601_20241231_hist.zip
Downloading: stundenwerte_TU_01303_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_01327_20040801_20241231_hist.zip
Downloading: stundenwerte_TU_01332_20050301_20241231_hist.zip
Downloading: stundenwerte_TU_01339_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_01341_20081201_20110929_hist.zip
Downloading: stundenwerte_TU_01346_19520101_20241231_hist.zip
Downloading: stundenwerte_TU_01357_20050301_20241231_hist.zip
Downloading: stundenwerte_TU_01358_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_01411_20070101_20241231_hist.zip
Downloading: stundenwerte_TU_01420_19810101_20241231_hist.zip
Downloading: stundenwerte_TU_01421_19620101_19840901_hist.zip
Downloading: stundenwerte_TU_01424_20080801_20241231_hist.zip
Downloading: stundenwerte_TU_01425_19480101_19620101_hist.zip
Downloading: stundenwerte_TU_01426_19610101_19850101_hist.zip
Downloading: stundenwerte_TU_01443_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_01451_20040601_20241231_hist.zip
Downloading: stundenwerte_TU_01468_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_01473_20060101_20190228_hist.zip
Downloading: stundenwerte_TU_01490_19650101_19770801_hist.zip
Downloading: stundenwerte_TU_01503_20121001_20241231_hist.zip
Downloading: stundenwerte_TU_01504_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_01515_20021104_20030814_hist.zip
Downloading: stundenwerte_TU_01526_20041101_20241231_hist.zip
Downloading: stundenwerte_TU_01544_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_01550_19480101_20241231_hist.zip
Downloading: stundenwerte_TU_01572_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_01580_19460101_20241231_hist.zip
Downloading: stundenwerte_TU_01583_19510101_19710101_hist.zip
Downloading: stundenwerte_TU_01584_20090601_20241031_hist.zip
Downloading: stundenwerte_TU_01587_19910101_20241231_hist.zip
Downloading: stundenwerte_TU_01590_20030701_20241231_hist.zip
Downloading: stundenwerte_TU_01602_20040701_20241231_hist.zip
Downloading: stundenwerte_TU_01605_19820101_20241231_hist.zip
Downloading: stundenwerte_TU_01612_19730101_20241231_hist.zip
Downloading: stundenwerte_TU_01639_19500101_20241231_hist.zip
Downloading: stundenwerte_TU_01645_20040501_20241231_hist.zip
Downloading: stundenwerte_TU_01666_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_01684_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_01691_19480101_20241231_hist.zip
Downloading: stundenwerte_TU_01694_19810101_20241231_hist.zip
Downloading: stundenwerte_TU_01721_20061001_20241231_hist.zip
Downloading: stundenwerte_TU_01735_20050301_20241231_hist.zip
Downloading: stundenwerte_TU_01736_20020124_20241231_hist.zip
Downloading: stundenwerte_TU_01757_19780101_20241231_hist.zip
Downloading: stundenwerte_TU_01758_19510101_19780101_hist.zip
Downloading: stundenwerte_TU_01759_20001025_20241231_hist.zip
Downloading: stundenwerte_TU_01766_19891001_20241231_hist.zip
Downloading: stundenwerte_TU_01792_20200814_20241231_hist.zip
Downloading: stundenwerte_TU_01803_19910101_20241231_hist.zip
Downloading: stundenwerte_TU_01832_19821101_20241231_hist.zip
Downloading: stundenwerte_TU_01833_19480101_19821101_hist.zip
Downloading: stundenwerte_TU_01834_19510101_19780701_hist.zip
Downloading: stundenwerte_TU_01863_20071201_20241231_hist.zip
Downloading: stundenwerte_TU_01869_19810101_20241231_hist.zip
Downloading: stundenwerte_TU_01886_20160901_20241231_hist.zip
Downloading: stundenwerte_TU_01957_19530101_20150323_hist.zip
Downloading: stundenwerte_TU_01960_19600101_19710101_hist.zip
Downloading: stundenwerte_TU_01964_20050501_20241231_hist.zip
Downloading: stundenwerte_TU_01975_19490101_20241231_hist.zip
Downloading: stundenwerte_TU_01981_20050301_20241231_hist.zip
Downloading: stundenwerte_TU_02014_19490101_20241231_hist.zip
Downloading: stundenwerte_TU_02023_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_02039_20061101_20241231_hist.zip
Downloading: stundenwerte_TU_02044_19810101_20241231_hist.zip
Downloading: stundenwerte_TU_02074_20040601_20241231_hist.zip
Downloading: stundenwerte_TU_02080_20040701_20120912_hist.zip
Downloading: stundenwerte_TU_02081_19480101_19550101_hist.zip
Downloading: stundenwerte_TU_02088_20040601_20050512_hist.zip
Downloading: stundenwerte_TU_02110_20030101_20241201_hist.zip
Downloading: stundenwerte_TU_02115_19520501_20241231_hist.zip
Downloading: stundenwerte_TU_02166_19820101_19910502_hist.zip
Downloading: stundenwerte_TU_02167_20050301_20120402_hist.zip
Downloading: stundenwerte_TU_02171_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_02174_20101101_20241231_hist.zip
Downloading: stundenwerte_TU_02201_20050801_20241231_hist.zip
Downloading: stundenwerte_TU_02211_20041001_20241231_hist.zip
Downloading: stundenwerte_TU_02252_20050701_20241231_hist.zip
Downloading: stundenwerte_TU_02261_19480101_20241231_hist.zip
Downloading: stundenwerte_TU_02290_19470101_20241231_hist.zip
Downloading: stundenwerte_TU_02303_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_02306_20050801_20241231_hist.zip
Downloading: stundenwerte_TU_02315_20021101_20241231_hist.zip
Downloading: stundenwerte_TU_02319_20050601_20241231_hist.zip
Downloading: stundenwerte_TU_02323_20060701_20241231_hist.zip
Downloading: stundenwerte_TU_02338_20020101_20051223_hist.zip
Downloading: stundenwerte_TU_02362_20040801_20241231_hist.zip
Downloading: stundenwerte_TU_02374_19490101_19740701_hist.zip
Downloading: stundenwerte_TU_02385_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_02410_19610102_20241231_hist.zip
Downloading: stundenwerte_TU_02429_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_02437_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_02444_19910801_20241231_hist.zip
Downloading: stundenwerte_TU_02456_20011017_20050826_hist.zip
Downloading: stundenwerte_TU_02480_20040901_20241231_hist.zip
Downloading: stundenwerte_TU_02483_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_02485_20110502_20241231_hist.zip
Downloading: stundenwerte_TU_02486_20050301_20241231_hist.zip
Downloading: stundenwerte_TU_02488_19820101_20021001_hist.zip
Downloading: stundenwerte_TU_02494_20020101_20131020_hist.zip
Downloading: stundenwerte_TU_02497_20040801_20241231_hist.zip
Downloading: stundenwerte_TU_02503_19510101_20030505_hist.zip
Downloading: stundenwerte_TU_02521_19820101_19940401_hist.zip
Downloading: stundenwerte_TU_02522_19480101_20081031_hist.zip
Downloading: stundenwerte_TU_02532_19480101_20131031_hist.zip
Downloading: stundenwerte_TU_02542_19750601_20160402_hist.zip
Downloading: stundenwerte_TU_02559_19550101_20241231_hist.zip
Downloading: stundenwerte_TU_02564_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_02565_19490101_19881015_hist.zip
Downloading: stundenwerte_TU_02575_20070523_20241231_hist.zip
Downloading: stundenwerte_TU_02578_20040701_20241231_hist.zip
Downloading: stundenwerte_TU_02597_19480101_20241231_hist.zip
Downloading: stundenwerte_TU_02600_20050301_20241231_hist.zip
Downloading: stundenwerte_TU_02601_19480101_20241231_hist.zip
Downloading: stundenwerte_TU_02618_20041001_20241231_hist.zip
Downloading: stundenwerte_TU_02627_20040701_20241231_hist.zip
Downloading: stundenwerte_TU_02629_20040701_20241231_hist.zip
Downloading: stundenwerte_TU_02638_19650701_20241231_hist.zip
Downloading: stundenwerte_TU_02641_20040901_20241231_hist.zip
Downloading: stundenwerte_TU_02656_19550101_19900101_hist.zip
Downloading: stundenwerte_TU_02667_19600101_20241231_hist.zip
Downloading: stundenwerte_TU_02680_20050601_20241231_hist.zip
Downloading: stundenwerte_TU_02691_19940401_19941101_hist.zip
Downloading: stundenwerte_TU_02700_20041201_20241231_hist.zip
Downloading: stundenwerte_TU_02704_20040501_20241231_hist.zip
Downloading: stundenwerte_TU_02708_20060701_20241231_hist.zip
Downloading: stundenwerte_TU_02712_19710101_20241231_hist.zip
Downloading: stundenwerte_TU_02738_19980101_19980201_hist.zip
Downloading: stundenwerte_TU_02750_20051101_20241231_hist.zip
Downloading: stundenwerte_TU_02761_19750601_19780601_hist.zip
Downloading: stundenwerte_TU_02773_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_02794_19890101_20241231_hist.zip
Downloading: stundenwerte_TU_02796_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_02812_19950101_20241231_hist.zip
Downloading: stundenwerte_TU_02814_19750601_20241231_hist.zip
Downloading: stundenwerte_TU_02829_19660101_20180710_hist.zip
Downloading: stundenwerte_TU_02856_20040701_20241231_hist.zip
Downloading: stundenwerte_TU_02878_20170801_20241231_hist.zip
Downloading: stundenwerte_TU_02886_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_02905_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_02907_19910101_20241231_hist.zip
Downloading: stundenwerte_TU_02920_19820101_19841101_hist.zip
Downloading: stundenwerte_TU_02925_19560101_20241231_hist.zip
Downloading: stundenwerte_TU_02928_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_02932_19720501_20241231_hist.zip
Downloading: stundenwerte_TU_02947_20061001_20241231_hist.zip
Downloading: stundenwerte_TU_02951_20040601_20241231_hist.zip
Downloading: stundenwerte_TU_02953_20070401_20241231_hist.zip
Downloading: stundenwerte_TU_02961_20020101_20241231_hist.zip
Downloading: stundenwerte_TU_02968_20081201_20240831_hist.zip
Downloading: stundenwerte_TU_02985_19910305_20241231_hist.zip
Downloading: stundenwerte_TU_03015_19510101_20241231_hist.zip
Downloading: stundenwerte_TU_03023_19510101_20161231_hist.zip
Downloading: stundenwerte_TU_03028_19710401_20241231_hist.zip
Downloading: stundenwerte_TU_03031_20040701_20241231_hist.zip
Downloading: stundenwerte_TU_03032_19490101_20241231_hist.zip
Downloading: stundenwerte_TU_03034_20070101_20241231_hist.zip
Downloading: stundenwerte_TU_03042_20080601_20241231_hist.zip
Downloading: stundenwerte_TU_03044_20070701_20180601_hist.zip
Downloading: stundenwerte_TU_03083_20050101_20241231_hist.zip
Downloading: stundenwerte_TU_03085_19510101_19850301_hist.zip
Downloading: stundenwerte_TU_03086_19850301_20241231_hist.zip
Downloading: stundenwerte_TU_03093_19541201_20241231_hist.zip
Downloading: stundenwerte_TU_03098_19940101_20241231_hist.zip
Downloading: stundenwerte_TU_03126_19550101_20241231_hist.zip
Downloading: stundenwerte_TU_03137_20080501_20241231_hist.zip
Downloading: stundenwerte_TU_03139_19831101_20050101_hist.zip
Downloading: stundenwerte_TU_03147_19850101_20241231_hist.zip
Downloading: stundenwerte_TU_03155_20040801_20241231_hist.zip
Downloading: stundenwerte_TU_03158_19890101_20241231_hist.zip
Downloading: stundenwerte_TU_03164_20060701_20241231_hist.zip
Downloading: stundenwerte_TU_03166_19820101_20241231_hist.zip
Downloading: stundenwerte_TU_03167_19621201_20241231_hist.zip
Downloading: stundenwerte_TU_03170_20020101_20121221_hist.zip
Downloading: stundenwerte_TU_03181_20210801_20241231_hist.zip
Downloading: stundenwerte_TU_03196_19810101_20241231_hist.zip
Downloading: stundenwerte_TU_03204_20080701_20241231_hist.zip
Downloading: stundenwerte_TU_03226_20060801_20241231_hist.zip
Downloading: stundenwerte_TU_03231_19790101_20241231_hist.zip
Downloading: stundenwerte_TU_03234_20050201_20241231_hist.zip
Downloading: stundenwerte_TU_03244_19750601_20241231_hist.zip
Downloading: stundenwerte_TU_03245_20020102_20021120_hist.zip
Downloading: stundenwerte_TU_03246_20020101_20070613_hist.zip
Downloading: stundenwerte_TU_03254_20020102_20241231_hist.zip
Downloading: stundenwerte_TU_03257_20040601_20241231_hist.zip
Downloading: stundenwerte_TU_03268_20021101_20241231_hist.zip
Downloading: stundenwerte_TU_03271_20041101_20241231_hist.zip
Downloading: stundenwerte_TU_03274_19921001_19941001_hist.zip
Downloading: stundenwerte_TU_03278_20090401_20241231_hist.zip
Downloading: stundenwerte_TU_03284_20050501_20241231_hist.zip
Downloading: stundenwerte_TU_03287_19871001_20241231_hist.zip
Downloading: stundenwerte_TU_03289_20041101_20241231_hist.zip
Downloading: stundenwerte_TU_03307_20080401_20241231_hist.zip

## Temperature Data Recent

In [2]:
import requests
from bs4 import BeautifulSoup
import os
import time

base_url = "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/air_temperature/recent/"

response = requests.get(base_url)
soup = BeautifulSoup(response.text, "html.parser")

links = [a.get("href") for a in soup.find_all("a") if a.get("href").endswith((".zip",".pdf",".txt"))]

os.makedirs("Document_Corpus/dwd_temp", exist_ok=True)
os.makedirs("Document_Corpus/dwd_temp/recent_zip", exist_ok=True)

for link in links:
    file_url = base_url + link
    file_path = os.path.join("Document_Corpus/dwd_temp/recent_zip", link)
    
    print("Downloading:", link)
    r = requests.get(file_url)
    
    with open(file_path, "wb") as f:
        f.write(r.content)
    
    print(f"Downloaded: {link}")
    print("Waiting 5 seconds before next download...\n")
    time.sleep(5)

Downloading: TU_Stundenwerte_Beschreibung_Stationen.txt
Downloaded: TU_Stundenwerte_Beschreibung_Stationen.txt
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00044_akt.zip
Downloaded: stundenwerte_TU_00044_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00073_akt.zip
Downloaded: stundenwerte_TU_00073_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00078_akt.zip
Downloaded: stundenwerte_TU_00078_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00091_akt.zip
Downloaded: stundenwerte_TU_00091_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00096_akt.zip
Downloaded: stundenwerte_TU_00096_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00102_akt.zip
Downloaded: stundenwerte_TU_00102_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00125_akt.zip
Downloaded: stundenwerte_TU_00125_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00131_akt.zip
Downloaded: stundenwerte_TU_00131_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00142_akt.zip
Downloaded: stundenwerte_TU_00142_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00150_akt.zip
Downloaded: stundenwerte_TU_00150_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00151_akt.zip
Downloaded: stundenwerte_TU_00151_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00154_akt.zip
Downloaded: stundenwerte_TU_00154_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00161_akt.zip
Downloaded: stundenwerte_TU_00161_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00164_akt.zip
Downloaded: stundenwerte_TU_00164_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00167_akt.zip
Downloaded: stundenwerte_TU_00167_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00183_akt.zip
Downloaded: stundenwerte_TU_00183_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00191_akt.zip
Downloaded: stundenwerte_TU_00191_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00198_akt.zip
Downloaded: stundenwerte_TU_00198_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00217_akt.zip
Downloaded: stundenwerte_TU_00217_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00222_akt.zip
Downloaded: stundenwerte_TU_00222_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00232_akt.zip
Downloaded: stundenwerte_TU_00232_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00257_akt.zip
Downloaded: stundenwerte_TU_00257_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00259_akt.zip
Downloaded: stundenwerte_TU_00259_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00282_akt.zip
Downloaded: stundenwerte_TU_00282_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00294_akt.zip
Downloaded: stundenwerte_TU_00294_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00298_akt.zip
Downloaded: stundenwerte_TU_00298_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00303_akt.zip
Downloaded: stundenwerte_TU_00303_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00314_akt.zip
Downloaded: stundenwerte_TU_00314_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00320_akt.zip
Downloaded: stundenwerte_TU_00320_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00330_akt.zip
Downloaded: stundenwerte_TU_00330_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00342_akt.zip
Downloaded: stundenwerte_TU_00342_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00368_akt.zip
Downloaded: stundenwerte_TU_00368_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00377_akt.zip
Downloaded: stundenwerte_TU_00377_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00379_akt.zip
Downloaded: stundenwerte_TU_00379_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00390_akt.zip
Downloaded: stundenwerte_TU_00390_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00400_akt.zip
Downloaded: stundenwerte_TU_00400_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00403_akt.zip
Downloaded: stundenwerte_TU_00403_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00420_akt.zip
Downloaded: stundenwerte_TU_00420_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00427_akt.zip
Downloaded: stundenwerte_TU_00427_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00433_akt.zip
Downloaded: stundenwerte_TU_00433_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00445_akt.zip
Downloaded: stundenwerte_TU_00445_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00460_akt.zip
Downloaded: stundenwerte_TU_00460_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00535_akt.zip
Downloaded: stundenwerte_TU_00535_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00555_akt.zip
Downloaded: stundenwerte_TU_00555_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00591_akt.zip
Downloaded: stundenwerte_TU_00591_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00596_akt.zip
Downloaded: stundenwerte_TU_00596_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00603_akt.zip
Downloaded: stundenwerte_TU_00603_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00617_akt.zip
Downloaded: stundenwerte_TU_00617_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00656_akt.zip
Downloaded: stundenwerte_TU_00656_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00662_akt.zip
Downloaded: stundenwerte_TU_00662_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00691_akt.zip
Downloaded: stundenwerte_TU_00691_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00701_akt.zip
Downloaded: stundenwerte_TU_00701_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00704_akt.zip
Downloaded: stundenwerte_TU_00704_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00722_akt.zip
Downloaded: stundenwerte_TU_00722_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00755_akt.zip
Downloaded: stundenwerte_TU_00755_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00757_akt.zip
Downloaded: stundenwerte_TU_00757_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00760_akt.zip
Downloaded: stundenwerte_TU_00760_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00766_akt.zip
Downloaded: stundenwerte_TU_00766_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00769_akt.zip
Downloaded: stundenwerte_TU_00769_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00817_akt.zip
Downloaded: stundenwerte_TU_00817_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00840_akt.zip
Downloaded: stundenwerte_TU_00840_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00850_akt.zip
Downloaded: stundenwerte_TU_00850_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00853_akt.zip
Downloaded: stundenwerte_TU_00853_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00856_akt.zip
Downloaded: stundenwerte_TU_00856_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00860_akt.zip
Downloaded: stundenwerte_TU_00860_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00867_akt.zip
Downloaded: stundenwerte_TU_00867_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00880_akt.zip
Downloaded: stundenwerte_TU_00880_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00891_akt.zip
Downloaded: stundenwerte_TU_00891_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00896_akt.zip
Downloaded: stundenwerte_TU_00896_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00917_akt.zip
Downloaded: stundenwerte_TU_00917_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00953_akt.zip
Downloaded: stundenwerte_TU_00953_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00954_akt.zip
Downloaded: stundenwerte_TU_00954_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00963_akt.zip
Downloaded: stundenwerte_TU_00963_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00983_akt.zip
Downloaded: stundenwerte_TU_00983_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_00991_akt.zip
Downloaded: stundenwerte_TU_00991_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01001_akt.zip
Downloaded: stundenwerte_TU_01001_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01048_akt.zip
Downloaded: stundenwerte_TU_01048_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01050_akt.zip
Downloaded: stundenwerte_TU_01050_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01051_akt.zip
Downloaded: stundenwerte_TU_01051_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01052_akt.zip
Downloaded: stundenwerte_TU_01052_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01072_akt.zip
Downloaded: stundenwerte_TU_01072_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01078_akt.zip
Downloaded: stundenwerte_TU_01078_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01103_akt.zip
Downloaded: stundenwerte_TU_01103_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01107_akt.zip
Downloaded: stundenwerte_TU_01107_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01161_akt.zip
Downloaded: stundenwerte_TU_01161_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01197_akt.zip
Downloaded: stundenwerte_TU_01197_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01200_akt.zip
Downloaded: stundenwerte_TU_01200_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01207_akt.zip
Downloaded: stundenwerte_TU_01207_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01214_akt.zip
Downloaded: stundenwerte_TU_01214_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01224_akt.zip
Downloaded: stundenwerte_TU_01224_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01228_akt.zip
Downloaded: stundenwerte_TU_01228_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01246_akt.zip
Downloaded: stundenwerte_TU_01246_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01255_akt.zip
Downloaded: stundenwerte_TU_01255_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01262_akt.zip
Downloaded: stundenwerte_TU_01262_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01266_akt.zip
Downloaded: stundenwerte_TU_01266_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01270_akt.zip
Downloaded: stundenwerte_TU_01270_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01279_akt.zip
Downloaded: stundenwerte_TU_01279_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01297_akt.zip
Downloaded: stundenwerte_TU_01297_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01300_akt.zip
Downloaded: stundenwerte_TU_01300_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01303_akt.zip
Downloaded: stundenwerte_TU_01303_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01327_akt.zip
Downloaded: stundenwerte_TU_01327_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01332_akt.zip
Downloaded: stundenwerte_TU_01332_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01339_akt.zip
Downloaded: stundenwerte_TU_01339_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01346_akt.zip
Downloaded: stundenwerte_TU_01346_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01357_akt.zip
Downloaded: stundenwerte_TU_01357_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01358_akt.zip
Downloaded: stundenwerte_TU_01358_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01411_akt.zip
Downloaded: stundenwerte_TU_01411_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01420_akt.zip
Downloaded: stundenwerte_TU_01420_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01424_akt.zip
Downloaded: stundenwerte_TU_01424_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01443_akt.zip
Downloaded: stundenwerte_TU_01443_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01451_akt.zip
Downloaded: stundenwerte_TU_01451_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01468_akt.zip
Downloaded: stundenwerte_TU_01468_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01503_akt.zip
Downloaded: stundenwerte_TU_01503_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01504_akt.zip
Downloaded: stundenwerte_TU_01504_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01526_akt.zip
Downloaded: stundenwerte_TU_01526_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01544_akt.zip
Downloaded: stundenwerte_TU_01544_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01550_akt.zip
Downloaded: stundenwerte_TU_01550_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01572_akt.zip
Downloaded: stundenwerte_TU_01572_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01580_akt.zip
Downloaded: stundenwerte_TU_01580_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01584_akt.zip
Downloaded: stundenwerte_TU_01584_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01587_akt.zip
Downloaded: stundenwerte_TU_01587_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01590_akt.zip
Downloaded: stundenwerte_TU_01590_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01602_akt.zip
Downloaded: stundenwerte_TU_01602_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01605_akt.zip
Downloaded: stundenwerte_TU_01605_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01612_akt.zip
Downloaded: stundenwerte_TU_01612_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01639_akt.zip
Downloaded: stundenwerte_TU_01639_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01645_akt.zip
Downloaded: stundenwerte_TU_01645_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01666_akt.zip
Downloaded: stundenwerte_TU_01666_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01684_akt.zip
Downloaded: stundenwerte_TU_01684_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01691_akt.zip
Downloaded: stundenwerte_TU_01691_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01694_akt.zip
Downloaded: stundenwerte_TU_01694_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01721_akt.zip
Downloaded: stundenwerte_TU_01721_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01735_akt.zip
Downloaded: stundenwerte_TU_01735_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01736_akt.zip
Downloaded: stundenwerte_TU_01736_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01757_akt.zip
Downloaded: stundenwerte_TU_01757_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01759_akt.zip
Downloaded: stundenwerte_TU_01759_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01766_akt.zip
Downloaded: stundenwerte_TU_01766_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01792_akt.zip
Downloaded: stundenwerte_TU_01792_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01803_akt.zip
Downloaded: stundenwerte_TU_01803_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01832_akt.zip
Downloaded: stundenwerte_TU_01832_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01863_akt.zip
Downloaded: stundenwerte_TU_01863_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01869_akt.zip
Downloaded: stundenwerte_TU_01869_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01886_akt.zip
Downloaded: stundenwerte_TU_01886_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01964_akt.zip
Downloaded: stundenwerte_TU_01964_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01975_akt.zip
Downloaded: stundenwerte_TU_01975_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_01981_akt.zip
Downloaded: stundenwerte_TU_01981_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_02014_akt.zip
Downloaded: stundenwerte_TU_02014_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_02023_akt.zip
Downloaded: stundenwerte_TU_02023_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_02039_akt.zip
Downloaded: stundenwerte_TU_02039_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_02044_akt.zip
Downloaded: stundenwerte_TU_02044_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_02074_akt.zip
Downloaded: stundenwerte_TU_02074_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_02110_akt.zip
Downloaded: stundenwerte_TU_02110_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_02115_akt.zip
Downloaded: stundenwerte_TU_02115_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_02171_akt.zip
Downloaded: stundenwerte_TU_02171_akt.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_TU_02174_akt.zip
Downloaded: stundenwerte_TU_02174_akt.zip
Waiting 5 seconds before next download...


# Solar Data Collection

In [3]:
import requests
from bs4 import BeautifulSoup
import os
import time

base_url = "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/solar/"

response = requests.get(base_url)
soup = BeautifulSoup(response.text, "html.parser")

links = [a.get("href") for a in soup.find_all("a") if a.get("href").endswith((".zip",".pdf",".txt"))]

os.makedirs("Document_Corpus/dwd_solar", exist_ok=True)
os.makedirs("Document_Corpus/dwd_solar/zip", exist_ok=True)
for link in links:
    file_url = base_url + link
    file_path = os.path.join("Document_Corpus/dwd_solar/zip", link)
    
    print("Downloading:", link)
    r = requests.get(file_url)
    
    with open(file_path, "wb") as f:
        f.write(r.content)
    
    print(f"Downloaded: {link}")
    print("Waiting 5 seconds before next download...\n")
    time.sleep(3)

Downloading: BESCHREIBUNG_obsgermany_climate_hourly_solar_de.pdf
Downloaded: BESCHREIBUNG_obsgermany_climate_hourly_solar_de.pdf
Waiting 5 seconds before next download...

Downloading: DESCRIPTION_obsgermany_climate_hourly_solar_en.pdf
Downloaded: DESCRIPTION_obsgermany_climate_hourly_solar_en.pdf
Waiting 5 seconds before next download...

Downloading: ST_Stundenwerte_Beschreibung_Stationen.txt
Downloaded: ST_Stundenwerte_Beschreibung_Stationen.txt
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_00183_row.zip
Downloaded: stundenwerte_ST_00183_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_00656_row.zip
Downloaded: stundenwerte_ST_00656_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_00662_row.zip
Downloaded: stundenwerte_ST_00662_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_00691_row.zip
Downloaded: stundenwerte_ST_00691_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_00853_row.zip
Downloaded: stundenwerte_ST_00853_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_00867_row.zip
Downloaded: stundenwerte_ST_00867_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_01048_row.zip
Downloaded: stundenwerte_ST_01048_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_01303_row.zip
Downloaded: stundenwerte_ST_01303_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_01346_row.zip
Downloaded: stundenwerte_ST_01346_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_01358_row.zip
Downloaded: stundenwerte_ST_01358_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_01443_row.zip
Downloaded: stundenwerte_ST_01443_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_01580_row.zip
Downloaded: stundenwerte_ST_01580_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_01594_row.zip
Downloaded: stundenwerte_ST_01594_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_01639_row.zip
Downloaded: stundenwerte_ST_01639_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_01684_row.zip
Downloaded: stundenwerte_ST_01684_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_01957_row.zip
Downloaded: stundenwerte_ST_01957_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_01975_row.zip
Downloaded: stundenwerte_ST_01975_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_02290_row.zip
Downloaded: stundenwerte_ST_02290_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_02483_row.zip
Downloaded: stundenwerte_ST_02483_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_02532_row.zip
Downloaded: stundenwerte_ST_02532_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_02712_row.zip
Downloaded: stundenwerte_ST_02712_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_02925_row.zip
Downloaded: stundenwerte_ST_02925_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_02928_row.zip
Downloaded: stundenwerte_ST_02928_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_02932_row.zip
Downloaded: stundenwerte_ST_02932_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_03015_row.zip
Downloaded: stundenwerte_ST_03015_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_03028_row.zip
Downloaded: stundenwerte_ST_03028_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_03032_row.zip
Downloaded: stundenwerte_ST_03032_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_03098_row.zip
Downloaded: stundenwerte_ST_03098_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_03478_row.zip
Downloaded: stundenwerte_ST_03478_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_03631_row.zip
Downloaded: stundenwerte_ST_03631_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_03668_row.zip
Downloaded: stundenwerte_ST_03668_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_03815_row.zip
Downloaded: stundenwerte_ST_03815_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_03987_row.zip
Downloaded: stundenwerte_ST_03987_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_04271_row.zip
Downloaded: stundenwerte_ST_04271_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_04336_row.zip
Downloaded: stundenwerte_ST_04336_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_04393_row.zip
Downloaded: stundenwerte_ST_04393_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_04466_row.zip
Downloaded: stundenwerte_ST_04466_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_04642_row.zip
Downloaded: stundenwerte_ST_04642_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_04928_row.zip
Downloaded: stundenwerte_ST_04928_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_05100_row.zip
Downloaded: stundenwerte_ST_05100_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_05142_row.zip
Downloaded: stundenwerte_ST_05142_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_05282_row.zip
Downloaded: stundenwerte_ST_05282_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_05404_row.zip
Downloaded: stundenwerte_ST_05404_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_05419_row.zip
Downloaded: stundenwerte_ST_05419_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_05440_row.zip
Downloaded: stundenwerte_ST_05440_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_05705_row.zip
Downloaded: stundenwerte_ST_05705_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_05779_row.zip
Downloaded: stundenwerte_ST_05779_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_05792_row.zip
Downloaded: stundenwerte_ST_05792_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_05856_row.zip
Downloaded: stundenwerte_ST_05856_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_05906_row.zip
Downloaded: stundenwerte_ST_05906_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_06197_row.zip
Downloaded: stundenwerte_ST_06197_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_07365_row.zip
Downloaded: stundenwerte_ST_07365_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_07370_row.zip
Downloaded: stundenwerte_ST_07370_row.zip
Waiting 5 seconds before next download...

Downloading: stundenwerte_ST_15000_row.zip
Downloaded: stundenwerte_ST_15000_row.zip
Waiting 5 seconds before next download...

# Wind Recent Data Collection

In [4]:
import requests
from bs4 import BeautifulSoup
import os
import time

base_url = "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind/recent/"

response = requests.get(base_url)
soup = BeautifulSoup(response.text, "html.parser")

links = [a.get("href") for a in soup.find_all("a") if a.get("href").endswith((".zip",".pdf",".txt"))]

os.makedirs("Document_Corpus/dwd_wind", exist_ok=True)
os.makedirs("Document_Corpus/dwd_wind/recent_zip", exist_ok=True)
for link in links:
    file_url = base_url + link
    file_path = os.path.join("Document_Corpus/dwd_wind/recent_zip", link)
    
    print("Downloading:", link)
    r = requests.get(file_url)
    
    with open(file_path, "wb") as f:
        f.write(r.content)
    
    print(f"Downloaded: {link}")
    print("Waiting 3 seconds before next download...\n")
    time.sleep(3)

Downloading: FF_Stundenwerte_Beschreibung_Stationen.txt
Downloaded: FF_Stundenwerte_Beschreibung_Stationen.txt
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00011_akt.zip
Downloaded: stundenwerte_FF_00011_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00090_akt.zip
Downloaded: stundenwerte_FF_00090_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00096_akt.zip
Downloaded: stundenwerte_FF_00096_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00102_akt.zip
Downloaded: stundenwerte_FF_00102_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00125_akt.zip
Downloaded: stundenwerte_FF_00125_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00161_akt.zip
Downloaded: stundenwerte_FF_00161_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00164_akt.zip
Downloaded: stundenwerte_FF_00164_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00183_akt.zip
Downloaded: stundenwerte_FF_00183_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00197_akt.zip
Downloaded: stundenwerte_FF_00197_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00198_akt.zip
Downloaded: stundenwerte_FF_00198_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00232_akt.zip
Downloaded: stundenwerte_FF_00232_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00282_akt.zip
Downloaded: stundenwerte_FF_00282_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00298_akt.zip
Downloaded: stundenwerte_FF_00298_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00303_akt.zip
Downloaded: stundenwerte_FF_00303_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00342_akt.zip
Downloaded: stundenwerte_FF_00342_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00368_akt.zip
Downloaded: stundenwerte_FF_00368_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00427_akt.zip
Downloaded: stundenwerte_FF_00427_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00433_akt.zip
Downloaded: stundenwerte_FF_00433_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00460_akt.zip
Downloaded: stundenwerte_FF_00460_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00591_akt.zip
Downloaded: stundenwerte_FF_00591_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00596_akt.zip
Downloaded: stundenwerte_FF_00596_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00603_akt.zip
Downloaded: stundenwerte_FF_00603_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00619_akt.zip
Downloaded: stundenwerte_FF_00619_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00642_akt.zip
Downloaded: stundenwerte_FF_00642_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00656_akt.zip
Downloaded: stundenwerte_FF_00656_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00662_akt.zip
Downloaded: stundenwerte_FF_00662_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00691_akt.zip
Downloaded: stundenwerte_FF_00691_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00701_akt.zip
Downloaded: stundenwerte_FF_00701_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00704_akt.zip
Downloaded: stundenwerte_FF_00704_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00722_akt.zip
Downloaded: stundenwerte_FF_00722_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00766_akt.zip
Downloaded: stundenwerte_FF_00766_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00788_akt.zip
Downloaded: stundenwerte_FF_00788_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00840_akt.zip
Downloaded: stundenwerte_FF_00840_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00853_akt.zip
Downloaded: stundenwerte_FF_00853_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00856_akt.zip
Downloaded: stundenwerte_FF_00856_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00867_akt.zip
Downloaded: stundenwerte_FF_00867_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00880_akt.zip
Downloaded: stundenwerte_FF_00880_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00891_akt.zip
Downloaded: stundenwerte_FF_00891_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00953_akt.zip
Downloaded: stundenwerte_FF_00953_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00954_akt.zip
Downloaded: stundenwerte_FF_00954_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00963_akt.zip
Downloaded: stundenwerte_FF_00963_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01001_akt.zip
Downloaded: stundenwerte_FF_01001_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01011_akt.zip
Downloaded: stundenwerte_FF_01011_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01013_akt.zip
Downloaded: stundenwerte_FF_01013_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01048_akt.zip
Downloaded: stundenwerte_FF_01048_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01078_akt.zip
Downloaded: stundenwerte_FF_01078_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01200_akt.zip
Downloaded: stundenwerte_FF_01200_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01228_akt.zip
Downloaded: stundenwerte_FF_01228_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01262_akt.zip
Downloaded: stundenwerte_FF_01262_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01270_akt.zip
Downloaded: stundenwerte_FF_01270_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01303_akt.zip
Downloaded: stundenwerte_FF_01303_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01339_akt.zip
Downloaded: stundenwerte_FF_01339_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01346_akt.zip
Downloaded: stundenwerte_FF_01346_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01357_akt.zip
Downloaded: stundenwerte_FF_01357_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01358_akt.zip
Downloaded: stundenwerte_FF_01358_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01379_akt.zip
Downloaded: stundenwerte_FF_01379_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01420_akt.zip
Downloaded: stundenwerte_FF_01420_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01443_akt.zip
Downloaded: stundenwerte_FF_01443_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01468_akt.zip
Downloaded: stundenwerte_FF_01468_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01490_akt.zip
Downloaded: stundenwerte_FF_01490_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01503_akt.zip
Downloaded: stundenwerte_FF_01503_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01544_akt.zip
Downloaded: stundenwerte_FF_01544_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01550_akt.zip
Downloaded: stundenwerte_FF_01550_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01580_akt.zip
Downloaded: stundenwerte_FF_01580_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01587_akt.zip
Downloaded: stundenwerte_FF_01587_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01605_akt.zip
Downloaded: stundenwerte_FF_01605_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01612_akt.zip
Downloaded: stundenwerte_FF_01612_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01639_akt.zip
Downloaded: stundenwerte_FF_01639_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01684_akt.zip
Downloaded: stundenwerte_FF_01684_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01691_akt.zip
Downloaded: stundenwerte_FF_01691_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01694_akt.zip
Downloaded: stundenwerte_FF_01694_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01757_akt.zip
Downloaded: stundenwerte_FF_01757_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01759_akt.zip
Downloaded: stundenwerte_FF_01759_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01766_akt.zip
Downloaded: stundenwerte_FF_01766_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01803_akt.zip
Downloaded: stundenwerte_FF_01803_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01832_akt.zip
Downloaded: stundenwerte_FF_01832_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01869_akt.zip
Downloaded: stundenwerte_FF_01869_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01886_akt.zip
Downloaded: stundenwerte_FF_01886_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01963_akt.zip
Downloaded: stundenwerte_FF_01963_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01975_akt.zip
Downloaded: stundenwerte_FF_01975_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01993_akt.zip
Downloaded: stundenwerte_FF_01993_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02014_akt.zip
Downloaded: stundenwerte_FF_02014_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02023_akt.zip
Downloaded: stundenwerte_FF_02023_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02044_akt.zip
Downloaded: stundenwerte_FF_02044_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02115_akt.zip
Downloaded: stundenwerte_FF_02115_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02171_akt.zip
Downloaded: stundenwerte_FF_02171_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02252_akt.zip
Downloaded: stundenwerte_FF_02252_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02261_akt.zip
Downloaded: stundenwerte_FF_02261_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02290_akt.zip
Downloaded: stundenwerte_FF_02290_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02303_akt.zip
Downloaded: stundenwerte_FF_02303_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02315_akt.zip
Downloaded: stundenwerte_FF_02315_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02349_akt.zip
Downloaded: stundenwerte_FF_02349_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02377_akt.zip
Downloaded: stundenwerte_FF_02377_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02385_akt.zip
Downloaded: stundenwerte_FF_02385_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02410_akt.zip
Downloaded: stundenwerte_FF_02410_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02429_akt.zip
Downloaded: stundenwerte_FF_02429_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02483_akt.zip
Downloaded: stundenwerte_FF_02483_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02485_akt.zip
Downloaded: stundenwerte_FF_02485_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02497_akt.zip
Downloaded: stundenwerte_FF_02497_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02559_akt.zip
Downloaded: stundenwerte_FF_02559_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02564_akt.zip
Downloaded: stundenwerte_FF_02564_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02573_akt.zip
Downloaded: stundenwerte_FF_02573_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02597_akt.zip
Downloaded: stundenwerte_FF_02597_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02601_akt.zip
Downloaded: stundenwerte_FF_02601_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02638_akt.zip
Downloaded: stundenwerte_FF_02638_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02667_akt.zip
Downloaded: stundenwerte_FF_02667_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02712_akt.zip
Downloaded: stundenwerte_FF_02712_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02773_akt.zip
Downloaded: stundenwerte_FF_02773_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02794_akt.zip
Downloaded: stundenwerte_FF_02794_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02812_akt.zip
Downloaded: stundenwerte_FF_02812_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02856_akt.zip
Downloaded: stundenwerte_FF_02856_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02878_akt.zip
Downloaded: stundenwerte_FF_02878_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02886_akt.zip
Downloaded: stundenwerte_FF_02886_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02897_akt.zip
Downloaded: stundenwerte_FF_02897_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02905_akt.zip
Downloaded: stundenwerte_FF_02905_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02907_akt.zip
Downloaded: stundenwerte_FF_02907_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02925_akt.zip
Downloaded: stundenwerte_FF_02925_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02928_akt.zip
Downloaded: stundenwerte_FF_02928_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02932_akt.zip
Downloaded: stundenwerte_FF_02932_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02961_akt.zip
Downloaded: stundenwerte_FF_02961_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_02985_akt.zip
Downloaded: stundenwerte_FF_02985_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03015_akt.zip
Downloaded: stundenwerte_FF_03015_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03028_akt.zip
Downloaded: stundenwerte_FF_03028_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03032_akt.zip
Downloaded: stundenwerte_FF_03032_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03086_akt.zip
Downloaded: stundenwerte_FF_03086_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03093_akt.zip
Downloaded: stundenwerte_FF_03093_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03098_akt.zip
Downloaded: stundenwerte_FF_03098_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03126_akt.zip
Downloaded: stundenwerte_FF_03126_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03158_akt.zip
Downloaded: stundenwerte_FF_03158_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03166_akt.zip
Downloaded: stundenwerte_FF_03166_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03167_akt.zip
Downloaded: stundenwerte_FF_03167_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03196_akt.zip
Downloaded: stundenwerte_FF_03196_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03231_akt.zip
Downloaded: stundenwerte_FF_03231_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03244_akt.zip
Downloaded: stundenwerte_FF_03244_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03254_akt.zip
Downloaded: stundenwerte_FF_03254_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03268_akt.zip
Downloaded: stundenwerte_FF_03268_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03287_akt.zip
Downloaded: stundenwerte_FF_03287_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03321_akt.zip
Downloaded: stundenwerte_FF_03321_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03362_akt.zip
Downloaded: stundenwerte_FF_03362_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03366_akt.zip
Downloaded: stundenwerte_FF_03366_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03376_akt.zip
Downloaded: stundenwerte_FF_03376_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03379_akt.zip
Downloaded: stundenwerte_FF_03379_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03402_akt.zip
Downloaded: stundenwerte_FF_03402_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03484_akt.zip
Downloaded: stundenwerte_FF_03484_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03513_akt.zip
Downloaded: stundenwerte_FF_03513_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03534_akt.zip
Downloaded: stundenwerte_FF_03534_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03623_akt.zip
Downloaded: stundenwerte_FF_03623_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03631_akt.zip
Downloaded: stundenwerte_FF_03631_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03639_akt.zip
Downloaded: stundenwerte_FF_03639_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03651_akt.zip
Downloaded: stundenwerte_FF_03651_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03660_akt.zip
Downloaded: stundenwerte_FF_03660_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03668_akt.zip
Downloaded: stundenwerte_FF_03668_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03730_akt.zip
Downloaded: stundenwerte_FF_03730_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03761_akt.zip
Downloaded: stundenwerte_FF_03761_akt.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_03811_akt.zip
Downloaded: stundenwerte_FF_03811_akt.zip
Waiting 3 seconds before next download...


# Wind Historical Data

In [5]:
import requests
from bs4 import BeautifulSoup
import os
import time

base_url = "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/wind/historical/"

response = requests.get(base_url)
soup = BeautifulSoup(response.text, "html.parser")

links = [a.get("href") for a in soup.find_all("a") if a.get("href").endswith((".zip",".pdf",".txt"))]

os.makedirs("Document_Corpus/dwd_wind", exist_ok=True)
os.makedirs("Document_Corpus/dwd_wind/historical_zip", exist_ok=True)
for link in links:
    file_url = base_url + link
    file_path = os.path.join("Document_Corpus/dwd_wind/historical_zip", link)
    
    print("Downloading:", link)
    r = requests.get(file_url)
    
    with open(file_path, "wb") as f:
        f.write(r.content)
    
    print(f"Downloaded: {link}")
    print("Waiting 3 seconds before next download...\n")
    time.sleep(3)

Downloading: FF_Stundenwerte_Beschreibung_Stationen.txt
Downloaded: FF_Stundenwerte_Beschreibung_Stationen.txt
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00003_19370101_20110331_hist.zip
Downloaded: stundenwerte_FF_00003_19370101_20110331_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00011_19800901_20241231_hist.zip
Downloaded: stundenwerte_FF_00011_19800901_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00044_19690101_19951130_hist.zip
Downloaded: stundenwerte_FF_00044_19690101_19951130_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00052_19690101_20011231_hist.zip
Downloaded: stundenwerte_FF_00052_19690101_20011231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00072_19780901_19950531_hist.zip
Downloaded: stundenwerte_FF_00072_19780901_19950531_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00090_19880219_20241231_hist.zip
Downloaded: stundenwerte_FF_00090_19880219_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00096_20190409_20241231_hist.zip
Downloaded: stundenwerte_FF_00096_20190409_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00102_20010404_20241231_hist.zip
Downloaded: stundenwerte_FF_00102_20010404_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00125_19740301_20241231_hist.zip
Downloaded: stundenwerte_FF_00125_19740301_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00126_19791101_20101130_hist.zip
Downloaded: stundenwerte_FF_00126_19791101_20101130_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00161_19801201_20241231_hist.zip
Downloaded: stundenwerte_FF_00161_19801201_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00164_19790101_20241231_hist.zip
Downloaded: stundenwerte_FF_00164_19790101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00175_19740201_19760430_hist.zip
Downloaded: stundenwerte_FF_00175_19740201_19760430_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00181_19991101_20081102_hist.zip
Downloaded: stundenwerte_FF_00181_19991101_20081102_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00183_19730101_20241231_hist.zip
Downloaded: stundenwerte_FF_00183_19730101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00193_19790901_19871231_hist.zip
Downloaded: stundenwerte_FF_00193_19790901_19871231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00197_19900801_20241231_hist.zip
Downloaded: stundenwerte_FF_00197_19900801_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00198_19610101_20241231_hist.zip
Downloaded: stundenwerte_FF_00198_19610101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00222_19820101_20080701_hist.zip
Downloaded: stundenwerte_FF_00222_19820101_20080701_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00232_19610101_20241231_hist.zip
Downloaded: stundenwerte_FF_00232_19610101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00259_19780501_19930731_hist.zip
Downloaded: stundenwerte_FF_00259_19780501_19930731_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00282_19710801_20241231_hist.zip
Downloaded: stundenwerte_FF_00282_19710801_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00298_19810101_20241231_hist.zip
Downloaded: stundenwerte_FF_00298_19810101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00303_19930906_20241231_hist.zip
Downloaded: stundenwerte_FF_00303_19930906_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00320_19790101_19970131_hist.zip
Downloaded: stundenwerte_FF_00320_19790101_19970131_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00330_19770301_20080531_hist.zip
Downloaded: stundenwerte_FF_00330_19770301_20080531_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00342_20101201_20241231_hist.zip
Downloaded: stundenwerte_FF_00342_20101201_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00348_19891214_20110901_hist.zip
Downloaded: stundenwerte_FF_00348_19891214_20110901_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00368_19730101_20241231_hist.zip
Downloaded: stundenwerte_FF_00368_19730101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00399_19750401_20150630_hist.zip
Downloaded: stundenwerte_FF_00399_19750401_20150630_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00400_19910101_20001025_hist.zip
Downloaded: stundenwerte_FF_00400_19910101_20001025_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00424_19750101_19801231_hist.zip
Downloaded: stundenwerte_FF_00424_19750101_19801231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00427_19730101_20241231_hist.zip
Downloaded: stundenwerte_FF_00427_19730101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00430_19870101_20210505_hist.zip
Downloaded: stundenwerte_FF_00430_19870101_20210505_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00433_19740101_20241231_hist.zip
Downloaded: stundenwerte_FF_00433_19740101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00460_19690101_20241231_hist.zip
Downloaded: stundenwerte_FF_00460_19690101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00553_19700601_19741231_hist.zip
Downloaded: stundenwerte_FF_00553_19700601_19741231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00554_19750101_20060228_hist.zip
Downloaded: stundenwerte_FF_00554_19750101_20060228_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00591_19730101_20241231_hist.zip
Downloaded: stundenwerte_FF_00591_19730101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00596_19730101_20241231_hist.zip
Downloaded: stundenwerte_FF_00596_19730101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00599_19750101_19990228_hist.zip
Downloaded: stundenwerte_FF_00599_19750101_19990228_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00603_19860801_20241231_hist.zip
Downloaded: stundenwerte_FF_00603_19860801_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00619_19870501_20241231_hist.zip
Downloaded: stundenwerte_FF_00619_19870501_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00642_19810101_20241231_hist.zip
Downloaded: stundenwerte_FF_00642_19810101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00656_19370101_20241231_hist.zip
Downloaded: stundenwerte_FF_00656_19370101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00662_19660101_20241231_hist.zip
Downloaded: stundenwerte_FF_00662_19660101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00691_19260101_20241231_hist.zip
Downloaded: stundenwerte_FF_00691_19260101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00701_19520101_20241231_hist.zip
Downloaded: stundenwerte_FF_00701_19520101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00704_19790401_20241231_hist.zip
Downloaded: stundenwerte_FF_00704_19790401_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00706_19690901_19920831_hist.zip
Downloaded: stundenwerte_FF_00706_19690901_19920831_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00722_19560101_20241231_hist.zip
Downloaded: stundenwerte_FF_00722_19560101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00766_19650101_20241231_hist.zip
Downloaded: stundenwerte_FF_00766_19650101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00769_19720101_20060930_hist.zip
Downloaded: stundenwerte_FF_00769_19720101_20060930_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00788_19650101_20241231_hist.zip
Downloaded: stundenwerte_FF_00788_19650101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00840_19900501_20241231_hist.zip
Downloaded: stundenwerte_FF_00840_19900501_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00850_19740801_20150630_hist.zip
Downloaded: stundenwerte_FF_00850_19740801_20150630_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00853_19610101_20241231_hist.zip
Downloaded: stundenwerte_FF_00853_19610101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00856_20030101_20241231_hist.zip
Downloaded: stundenwerte_FF_00856_20030101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00867_19720101_20241231_hist.zip
Downloaded: stundenwerte_FF_00867_19720101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00876_19730101_19881231_hist.zip
Downloaded: stundenwerte_FF_00876_19730101_19881231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00880_19830101_20241231_hist.zip
Downloaded: stundenwerte_FF_00880_19830101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00891_19690101_20241231_hist.zip
Downloaded: stundenwerte_FF_00891_19690101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00953_19690101_20241231_hist.zip
Downloaded: stundenwerte_FF_00953_19690101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00954_20010403_20241231_hist.zip
Downloaded: stundenwerte_FF_00954_20010403_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00963_19740101_20241231_hist.zip
Downloaded: stundenwerte_FF_00963_19740101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_00998_19500101_20090201_hist.zip
Downloaded: stundenwerte_FF_00998_19500101_20090201_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01001_19810101_20241231_hist.zip
Downloaded: stundenwerte_FF_01001_19810101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01010_19870401_20080923_hist.zip
Downloaded: stundenwerte_FF_01010_19870401_20080923_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01011_19901011_20241231_hist.zip
Downloaded: stundenwerte_FF_01011_19901011_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01013_19800401_20241231_hist.zip
Downloaded: stundenwerte_FF_01013_19800401_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01048_19730101_20241231_hist.zip
Downloaded: stundenwerte_FF_01048_19730101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01078_19520101_20241231_hist.zip
Downloaded: stundenwerte_FF_01078_19520101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01130_19720401_20040229_hist.zip
Downloaded: stundenwerte_FF_01130_19720401_20040229_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01200_20070101_20241231_hist.zip
Downloaded: stundenwerte_FF_01200_20070101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01219_19750101_19980310_hist.zip
Downloaded: stundenwerte_FF_01219_19750101_19980310_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01221_19500301_19741231_hist.zip
Downloaded: stundenwerte_FF_01221_19500301_19741231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01228_20010424_20241231_hist.zip
Downloaded: stundenwerte_FF_01228_20010424_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01261_19690101_19920731_hist.zip
Downloaded: stundenwerte_FF_01261_19690101_19920731_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01262_19920519_20241231_hist.zip
Downloaded: stundenwerte_FF_01262_19920519_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01270_19730101_20241231_hist.zip
Downloaded: stundenwerte_FF_01270_19730101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01297_19801201_19850718_hist.zip
Downloaded: stundenwerte_FF_01297_19801201_19850718_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01303_19630101_20241231_hist.zip
Downloaded: stundenwerte_FF_01303_19630101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01339_19710101_20241231_hist.zip
Downloaded: stundenwerte_FF_01339_19710101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01346_19550101_20241231_hist.zip
Downloaded: stundenwerte_FF_01346_19550101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01357_19931215_20241231_hist.zip
Downloaded: stundenwerte_FF_01357_19931215_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01358_19550101_20241231_hist.zip
Downloaded: stundenwerte_FF_01358_19550101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01359_19820101_19921126_hist.zip
Downloaded: stundenwerte_FF_01359_19820101_19921126_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01379_19821201_20241231_hist.zip
Downloaded: stundenwerte_FF_01379_19821201_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01415_19760601_19881231_hist.zip
Downloaded: stundenwerte_FF_01415_19760601_19881231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01416_19840401_19871231_hist.zip
Downloaded: stundenwerte_FF_01416_19840401_19871231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01420_19670101_20241231_hist.zip
Downloaded: stundenwerte_FF_01420_19670101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01422_19730801_19890430_hist.zip
Downloaded: stundenwerte_FF_01422_19730801_19890430_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01423_19720501_19871231_hist.zip
Downloaded: stundenwerte_FF_01423_19720501_19871231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01425_19510501_19621231_hist.zip
Downloaded: stundenwerte_FF_01425_19510501_19621231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01426_19640101_19841231_hist.zip
Downloaded: stundenwerte_FF_01426_19640101_19841231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01443_19550101_20241231_hist.zip
Downloaded: stundenwerte_FF_01443_19550101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01468_19701001_20241231_hist.zip
Downloaded: stundenwerte_FF_01468_19701001_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01490_19650101_20241231_hist.zip
Downloaded: stundenwerte_FF_01490_19650101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01503_20121001_20241231_hist.zip
Downloaded: stundenwerte_FF_01503_20121001_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01505_19750101_20071031_hist.zip
Downloaded: stundenwerte_FF_01505_19750101_20071031_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01515_19690101_19911231_hist.zip
Downloaded: stundenwerte_FF_01515_19690101_19911231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01526_19770301_19930729_hist.zip
Downloaded: stundenwerte_FF_01526_19770301_19930729_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01544_19590101_20241231_hist.zip
Downloaded: stundenwerte_FF_01544_19590101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01550_19690101_20241231_hist.zip
Downloaded: stundenwerte_FF_01550_19690101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01572_19821201_20041231_hist.zip
Downloaded: stundenwerte_FF_01572_19821201_20041231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01580_19510101_20241231_hist.zip
Downloaded: stundenwerte_FF_01580_19510101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01587_20031210_20241231_hist.zip
Downloaded: stundenwerte_FF_01587_20031210_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01605_19820101_20241231_hist.zip
Downloaded: stundenwerte_FF_01605_19820101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01612_19730101_20241231_hist.zip
Downloaded: stundenwerte_FF_01612_19730101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01639_19390101_20241231_hist.zip
Downloaded: stundenwerte_FF_01639_19390101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01666_19710101_20071231_hist.zip
Downloaded: stundenwerte_FF_01666_19710101_20071231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01684_19630101_20241231_hist.zip
Downloaded: stundenwerte_FF_01684_19630101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01689_19900701_19920630_hist.zip
Downloaded: stundenwerte_FF_01689_19900701_19920630_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01691_19690101_20241231_hist.zip
Downloaded: stundenwerte_FF_01691_19690101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01694_19810901_20241231_hist.zip
Downloaded: stundenwerte_FF_01694_19810901_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01757_19780101_20241231_hist.zip
Downloaded: stundenwerte_FF_01757_19780101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01758_19610101_19771231_hist.zip
Downloaded: stundenwerte_FF_01758_19610101_19771231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01759_20001025_20241231_hist.zip
Downloaded: stundenwerte_FF_01759_20001025_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01766_19820101_20241231_hist.zip
Downloaded: stundenwerte_FF_01766_19820101_20241231_hist.zip
Waiting 3 seconds before next download...

Downloading: stundenwerte_FF_01803_19910101_20241231_hist.zip

# Extrating Solar Zip files

In [6]:
#Extract solar data files into extracted folder
import os
import zipfile
from pathlib import Path
# Folder containing all zip files
zip_folder = Path("Document_Corpus/dwd_solar/zip")

# Output folder for extracted produkt files
output_folder = Path("Document_Corpus/dwd_solar/extracted")
output_folder.mkdir(parents=True, exist_ok=True)

print("ZIP folder:", zip_folder.resolve())
print("Output folder:", output_folder.resolve())



# Check how many ZIP files are available
zip_files = list(zip_folder.glob("*.zip"))
print(f"Total ZIP files found: {len(zip_files)}")

# Show first few zip names
for z in zip_files[:10]:
    print(z.name)

# Extract only files starting with produkt_st_stunde
extracted_files = []
errors = []

for zip_path in zip_files:
    try:
        with zipfile.ZipFile(zip_path, 'r') as z:
            matched = False
            
            for file_name in z.namelist():
                base_name = os.path.basename(file_name)
                
                if base_name.startswith("produkt_st_stunde"):
                    
                    
                    matched = True
                    
                    # Add zip filename prefix to avoid overwriting files
                    #new_name = f"{zip_path.stem}_{base_name}"
                    new_name = f"{base_name}"
                    target_path = output_folder / new_name

                    with z.open(file_name) as source, open(target_path, "wb") as target:
                        target.write(source.read())

                    extracted_files.append(target_path.name)
                    print(f"Extracted: {target_path.name}")
            
            if not matched:
                print(f"No produkt_st_stunde file found in: {zip_path.name}")

    except Exception as e:
        errors.append((zip_path.name, str(e)))
        print(f"Error with {zip_path.name}: {e}")



# Summary
print("="*50)
print("EXTRACTION SUMMARY")
print("="*50)
print(f"ZIP files scanned: {len(zip_files)}")
print(f"Files extracted: {len(extracted_files)}")
print(f"Errors: {len(errors)}")

ZIP folder: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\dwd_solar\zip
Output folder: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\dwd_solar\extracted
Total ZIP files found: 54
stundenwerte_ST_00183_row.zip
stundenwerte_ST_00656_row.zip
stundenwerte_ST_00662_row.zip
stundenwerte_ST_00691_row.zip
stundenwerte_ST_00853_row.zip
stundenwerte_ST_00867_row.zip
stundenwerte_ST_01048_row.zip
stundenwerte_ST_01303_row.zip
stundenwerte_ST_01346_row.zip
stundenwerte_ST_01358_row.zip
Extracted: produkt_st_stunde_19810101_20260228_00183.txt
Extracted: produkt_st_stunde_19570101_20000731_00656.txt
Extracted: produkt_st_stunde_19580101_20260228_00662.txt
Extracted: produkt_st_stunde_20090101_20260228_00691.txt
Extracted: produkt_st_stunde_19810101_20260228_00853.txt
Extracted: produkt_st_stunde_20210101_20260228_00867.txt
Extracted: produkt_st_stunde_19960901_20260228_01048.txt
Extracted: produkt_st_stunde_20230831_20241231_01303.txt
Extracted: produkt_st_stunde_20230101_20260228_01346.txt
Extracted: produkt_st_stunde_19580101_20260228_01358.txt
Extracted: produkt_st_stunde_19730101_20150131_01443.txt
Extracted: produkt_st_stunde_19760101_20131231_01580.txt
Extracted: produkt_st_stunde_19740101_19901231_01594.txt
Extracted: produkt_st_stunde_20240101_20260228_01639.txt
Extracted: produkt_st_stunde_20010101_20260228_01684.txt
Extracted: produkt_st_stunde_19810101_20150131_01957.txt
Extracted: produkt_st_stunde_20050101_20260228_01975.txt
Extracted: produkt_st_stunde_19530101_20260228_02290.txt
Extracted: produkt_st_stunde_20250101_20260228_02483.txt
Extracted: produkt_st_stunde_19790101_20021231_02532.txt
Extracted: produkt_st_stunde_19770101_20260228_02712.txt
Extracted: produkt_st_stunde_20210101_20260228_02925.txt
Extracted: produkt_st_stunde_20061001_20190531_02928.txt
Extracted: produkt_st_stunde_20190501_20230930_02932.txt
Extracted: produkt_st_stunde_19810101_20260228_03015.txt
Extracted: produkt_st_stunde_19820101_20110831_03028.txt
Extracted: produkt_st_stunde_19720101_20150131_03032.txt
Extracted: produkt_st_stunde_20060101_20130731_03098.txt
Extracted: produkt_st_stunde_19910101_20031231_03478.txt
Extracted: produkt_st_stunde_19640101_20260228_03631.txt
Extracted: produkt_st_stunde_20090101_20260228_03668.txt
Extracted: produkt_st_stunde_19770101_20011231_03815.txt
Extracted: produkt_st_stunde_19451231_20260228_03987.txt
Extracted: produkt_st_stunde_19980101_20260228_04271.txt
Extracted: produkt_st_stunde_19810101_20260228_04336.txt
Extracted: produkt_st_stunde_20080701_20260228_04393.txt
Extracted: produkt_st_stunde_19800101_20260228_04466.txt
Extracted: produkt_st_stunde_19910101_20260228_04642.txt
Extracted: produkt_st_stunde_19790101_20260228_04928.txt
Extracted: produkt_st_stunde_19580101_20260228_05100.txt
Extracted: produkt_st_stunde_20220101_20260228_05142.txt
Extracted: produkt_st_stunde_19500101_19960831_05282.txt
Extracted: produkt_st_stunde_19610101_20260228_05404.txt
Extracted: produkt_st_stunde_19490101_20070430_05419.txt
Extracted: produkt_st_stunde_19810101_20140930_05440.txt
Extracted: produkt_st_stunde_19570101_20260228_05705.txt
Extracted: produkt_st_stunde_19810101_20260228_05779.txt
Extracted: produkt_st_stunde_20130101_20260228_05792.txt
Extracted: produkt_st_stunde_19970102_20260228_05856.txt
Extracted: produkt_st_stunde_19790101_20260228_05906.txt
Extracted: produkt_st_stunde_20220101_20260228_06197.txt
Extracted: produkt_st_stunde_20090101_20260228_07365.txt
Extracted: produkt_st_stunde_20210101_20260228_07370.txt
Extracted: produkt_st_stunde_20230101_20260228_15000.txt
==================================================
EXTRACTION SUMMARY
==================================================
ZIP files scanned: 54
Files extracted: 54
Errors: 0

# Extracting Temp Historical

In [7]:
#Extract Temperature HISTORICAL data files into extracted folder
import os
import zipfile
from pathlib import Path
# Folder containing all zip files
zip_folder = Path("Document_Corpus/dwd_temp/historical_zip")

# Output folder for extracted produkt files
output_folder = Path("Document_Corpus/dwd_temp/extracted")
output_folder.mkdir(parents=True, exist_ok=True)

print("ZIP folder:", zip_folder.resolve())
print("Output folder:", output_folder.resolve())



# Check how many ZIP files are available
zip_files = list(zip_folder.glob("*.zip"))
print(f"Total ZIP files found: {len(zip_files)}")

# Show first few zip names
for z in zip_files[:10]:
    print(z.name)

# Extract only files starting with produkt_st_stunde
extracted_files = []
errors = []

for zip_path in zip_files:
    try:
        with zipfile.ZipFile(zip_path, 'r') as z:
            matched = False
            
            for file_name in z.namelist():
                base_name = os.path.basename(file_name)
                
                if base_name.startswith("produkt_tu_stunde"):
                    
                    
                    matched = True
                    
                    # Add zip filename prefix to avoid overwriting files
                    #new_name = f"{zip_path.stem}_{base_name}"
                    new_name = f"{base_name}"
                    target_path = output_folder / new_name

                    with z.open(file_name) as source, open(target_path, "wb") as target:
                        target.write(source.read())

                    extracted_files.append(target_path.name)
                    print(f"Extracted: {target_path.name}")
            
            if not matched:
                print(f"No produkt_st_stunde file found in: {zip_path.name}")

    except Exception as e:
        errors.append((zip_path.name, str(e)))
        print(f"Error with {zip_path.name}: {e}")



# Summary
print("="*50)
print("EXTRACTION SUMMARY")
print("="*50)
print(f"ZIP files scanned: {len(zip_files)}")
print(f"Files extracted: {len(extracted_files)}")
print(f"Errors: {len(errors)}")

ZIP folder: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\dwd_temp\historical_zip
Output folder: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\dwd_temp\extracted
Total ZIP files found: 636
stundenwerte_TU_00003_19500401_20110331_hist.zip
stundenwerte_TU_00044_20070401_20241231_hist.zip
stundenwerte_TU_00052_19760101_19880101_hist.zip
stundenwerte_TU_00071_20091201_20191231_hist.zip
stundenwerte_TU_00073_20070401_20241231_hist.zip
stundenwerte_TU_00078_20041101_20241231_hist.zip
stundenwerte_TU_00091_20040901_20241231_hist.zip
stundenwerte_TU_00096_20190409_20241231_hist.zip
stundenwerte_TU_00102_20020101_20241231_hist.zip
stundenwerte_TU_00125_19710104_20241231_hist.zip
Extracted: produkt_tu_stunde_19500401_20110331_00003.txt
Extracted: produkt_tu_stunde_20070401_20241231_00044.txt
Extracted: produkt_tu_stunde_19760101_19880101_00052.txt
Extracted: produkt_tu_stunde_20091201_20191231_00071.txt
Extracted: produkt_tu_stunde_20070401_20241231_00073.txt
Extracted: produkt_tu_stunde_20041101_20241231_00078.txt
Extracted: produkt_tu_stunde_20040901_20241231_00091.txt
Extracted: produkt_tu_stunde_20190409_20241231_00096.txt
Extracted: produkt_tu_stunde_20020101_20241231_00102.txt
Extracted: produkt_tu_stunde_19710104_20241231_00125.txt
Extracted: produkt_tu_stunde_20041101_20241231_00131.txt
Extracted: produkt_tu_stunde_19820101_20241231_00142.txt
Extracted: produkt_tu_stunde_20050701_20241231_00150.txt
Extracted: produkt_tu_stunde_20050301_20241231_00151.txt
Extracted: produkt_tu_stunde_20050301_20241231_00154.txt
Extracted: produkt_tu_stunde_20110901_20241231_00161.txt
Extracted: produkt_tu_stunde_19560101_20241231_00164.txt
Extracted: produkt_tu_stunde_20040901_20241231_00167.txt
Extracted: produkt_tu_stunde_19550101_19751231_00175.txt
Extracted: produkt_tu_stunde_19990928_20081103_00181.txt
Extracted: produkt_tu_stunde_19730101_20241231_00183.txt
Extracted: produkt_tu_stunde_20041104_20241231_00191.txt
Extracted: produkt_tu_stunde_19610101_20241231_00198.txt
Extracted: produkt_tu_stunde_20050101_20241231_00217.txt
Extracted: produkt_tu_stunde_19820101_20241231_00222.txt
Extracted: produkt_tu_stunde_19550101_20241231_00232.txt
Extracted: produkt_tu_stunde_20021101_20241231_00257.txt
Extracted: produkt_tu_stunde_20040701_20241231_00259.txt
Extracted: produkt_tu_stunde_19610101_20241231_00282.txt
Extracted: produkt_tu_stunde_19470101_19550101_00284.txt
Extracted: produkt_tu_stunde_20040701_20241231_00294.txt
Extracted: produkt_tu_stunde_19810101_20241231_00298.txt
Extracted: produkt_tu_stunde_19930819_20241231_00303.txt
Extracted: produkt_tu_stunde_20040501_20241231_00314.txt
Extracted: produkt_tu_stunde_20060701_20241231_00320.txt
Extracted: produkt_tu_stunde_20040701_20130708_00326.txt
Extracted: produkt_tu_stunde_20040801_20241231_00330.txt
Extracted: produkt_tu_stunde_20101201_20241231_00342.txt
Extracted: produkt_tu_stunde_19891215_20110901_00348.txt
Extracted: produkt_tu_stunde_19480101_19760101_00361.txt
Extracted: produkt_tu_stunde_20020101_20241231_00368.txt
Extracted: produkt_tu_stunde_20041001_20241231_00377.txt
Extracted: produkt_tu_stunde_20170901_20241231_00379.txt
Extracted: produkt_tu_stunde_20040701_20241231_00390.txt
Extracted: produkt_tu_stunde_19691201_20110801_00399.txt
Extracted: produkt_tu_stunde_19910101_20241231_00400.txt
Extracted: produkt_tu_stunde_20020101_20241231_00403.txt
Extracted: produkt_tu_stunde_20040501_20200615_00410.txt
Extracted: produkt_tu_stunde_20070801_20241231_00420.txt
Extracted: produkt_tu_stunde_19610101_19810101_00424.txt
Extracted: produkt_tu_stunde_19730101_20241231_00427.txt
Extracted: produkt_tu_stunde_19860101_20210505_00430.txt
Extracted: produkt_tu_stunde_19510101_20241231_00433.txt
Extracted: produkt_tu_stunde_20050701_20241231_00445.txt
Extracted: produkt_tu_stunde_20051101_20121204_00450.txt
Extracted: produkt_tu_stunde_19610101_20241231_00460.txt
Extracted: produkt_tu_stunde_19750601_19780601_00474.txt
Extracted: produkt_tu_stunde_20040601_20241231_00535.txt
Extracted: produkt_tu_stunde_19510101_19740901_00553.txt
Extracted: produkt_tu_stunde_19740901_20060228_00554.txt
Extracted: produkt_tu_stunde_20080101_20241231_00555.txt
Extracted: produkt_tu_stunde_19730101_20241231_00591.txt
Extracted: produkt_tu_stunde_19730101_20241231_00596.txt
Extracted: produkt_tu_stunde_19490101_19570101_00598.txt
Extracted: produkt_tu_stunde_19840101_19971201_00599.txt
Extracted: produkt_tu_stunde_20010403_20241231_00603.txt
Extracted: produkt_tu_stunde_20040601_20241231_00617.txt
Extracted: produkt_tu_stunde_19480101_20241231_00656.txt
Extracted: produkt_tu_stunde_19510101_20241231_00662.txt
Extracted: produkt_tu_stunde_20020101_20061031_00685.txt
Extracted: produkt_tu_stunde_19490101_20241231_00691.txt
Extracted: produkt_tu_stunde_19490101_20241231_00701.txt
Extracted: produkt_tu_stunde_19910101_20241231_00704.txt
Extracted: produkt_tu_stunde_19510101_20241231_00722.txt
Extracted: produkt_tu_stunde_20040601_20241231_00755.txt
Extracted: produkt_tu_stunde_20040601_20241231_00757.txt
Extracted: produkt_tu_stunde_20171201_20241231_00760.txt
Extracted: produkt_tu_stunde_20020101_20241231_00766.txt
Extracted: produkt_tu_stunde_20020101_20241231_00769.txt
Extracted: produkt_tu_stunde_20050201_20241231_00817.txt
Extracted: produkt_tu_stunde_19910101_20241231_00840.txt
Extracted: produkt_tu_stunde_20020101_20241231_00850.txt
Extracted: produkt_tu_stunde_19510101_20241231_00853.txt
Extracted: produkt_tu_stunde_19910101_20241231_00856.txt
Extracted: produkt_tu_stunde_20231001_20241231_00860.txt
Extracted: produkt_tu_stunde_20071001_20120403_00863.txt
Extracted: produkt_tu_stunde_19470101_20241231_00867.txt
Extracted: produkt_tu_stunde_19730101_19890101_00876.txt
Extracted: produkt_tu_stunde_20020101_20030611_00879.txt
Extracted: produkt_tu_stunde_19560101_20241231_00880.txt
Extracted: produkt_tu_stunde_19510101_20241231_00891.txt
Extracted: produkt_tu_stunde_20040801_20241231_00896.txt
Extracted: produkt_tu_stunde_20040901_20241231_00917.txt
Extracted: produkt_tu_stunde_19580101_19720101_00919.txt
Extracted: produkt_tu_stunde_19550101_20241231_00953.txt
Extracted: produkt_tu_stunde_20000501_20241231_00954.txt
Extracted: produkt_tu_stunde_19940103_20241231_00963.txt
Extracted: produkt_tu_stunde_20040901_20230313_00979.txt
Extracted: produkt_tu_stunde_19760101_19780601_00982.txt
Extracted: produkt_tu_stunde_20061201_20241231_00983.txt
Extracted: produkt_tu_stunde_20050201_20241231_00991.txt
Extracted: produkt_tu_stunde_19810101_20241231_01001.txt
Extracted: produkt_tu_stunde_19730101_20241231_01048.txt
Extracted: produkt_tu_stunde_20060401_20241231_01050.txt
Extracted: produkt_tu_stunde_20070301_20230814_01051.txt
Extracted: produkt_tu_stunde_20040701_20241231_01052.txt
Extracted: produkt_tu_stunde_20040601_20241231_01072.txt
Extracted: produkt_tu_stunde_19760301_20241231_01078.txt
Extracted: produkt_tu_stunde_20061001_20241231_01103.txt
Extracted: produkt_tu_stunde_20041201_20241231_01107.txt
Extracted: produkt_tu_stunde_20020101_20050422_01130.txt
Extracted: produkt_tu_stunde_20050201_20241231_01161.txt
Extracted: produkt_tu_stunde_19480101_20241231_01197.txt
Extracted: produkt_tu_stunde_20020101_20241231_01200.txt
Extracted: produkt_tu_stunde_20060301_20241231_01207.txt
Extracted: produkt_tu_stunde_20040801_20241231_01214.txt
Extracted: produkt_tu_stunde_19710101_19981102_01219.txt
Extracted: produkt_tu_stunde_19490101_19710101_01221.txt
Extracted: produkt_tu_stunde_20021201_20241231_01224.txt
Extracted: produkt_tu_stunde_20020101_20241231_01228.txt
Extracted: produkt_tu_stunde_20040701_20080923_01239.txt
Extracted: produkt_tu_stunde_20150801_20241231_01246.txt
Extracted: produkt_tu_stunde_20021201_20241231_01255.txt
Extracted: produkt_tu_stunde_19920517_20241231_01262.txt
Extracted: produkt_tu_stunde_20040601_20241231_01266.txt
Extracted: produkt_tu_stunde_19510101_20241231_01270.txt
Extracted: produkt_tu_stunde_19861101_20241231_01279.txt
Extracted: produkt_tu_stunde_20041001_20241231_01297.txt
Extracted: produkt_tu_stunde_20040601_20241231_01300.txt
Extracted: produkt_tu_stunde_19510101_20241231_01303.txt
Extracted: produkt_tu_stunde_20040801_20241231_01327.txt
Extracted: produkt_tu_stunde_20050301_20241231_01332.txt
Extracted: produkt_tu_stunde_20020101_20241231_01339.txt
Extracted: produkt_tu_stunde_20081201_20110929_01341.txt
Extracted: produkt_tu_stunde_19520101_20241231_01346.txt
Extracted: produkt_tu_stunde_20050301_20241231_01357.txt
Extracted: produkt_tu_stunde_19510101_20241231_01358.txt
Extracted: produkt_tu_stunde_20070101_20241231_01411.txt
Extracted: produkt_tu_stunde_19810101_20241231_01420.txt
Extracted: produkt_tu_stunde_19620101_19840901_01421.txt
Extracted: produkt_tu_stunde_20080801_20241231_01424.txt
Extracted: produkt_tu_stunde_19480101_19620101_01425.txt
Extracted: produkt_tu_stunde_19610101_19850101_01426.txt
Extracted: produkt_tu_stunde_19510101_20241231_01443.txt
Extracted: produkt_tu_stunde_20040601_20241231_01451.txt
Extracted: produkt_tu_stunde_19510101_20241231_01468.txt
Extracted: produkt_tu_stunde_20060101_20190228_01473.txt
Extracted: produkt_tu_stunde_19650101_19770801_01490.txt
Extracted: produkt_tu_stunde_20121001_20241231_01503.txt
Extracted: produkt_tu_stunde_20020101_20241231_01504.txt
Extracted: produkt_tu_stunde_20021104_20030814_01515.txt
Extracted: produkt_tu_stunde_20041101_20241231_01526.txt
Extracted: produkt_tu_stunde_19510101_20241231_01544.txt
Extracted: produkt_tu_stunde_19480101_20241231_01550.txt
Extracted: produkt_tu_stunde_20020101_20241231_01572.txt
Extracted: produkt_tu_stunde_19460101_20241231_01580.txt
Extracted: produkt_tu_stunde_19510101_19710101_01583.txt
Extracted: produkt_tu_stunde_20090601_20241031_01584.txt
Extracted: produkt_tu_stunde_19910101_20241231_01587.txt
Extracted: produkt_tu_stunde_20030701_20241231_01590.txt
Extracted: produkt_tu_stunde_20040701_20241231_01602.txt
Extracted: produkt_tu_stunde_19820101_20241231_01605.txt
Extracted: produkt_tu_stunde_19730101_20241231_01612.txt
Extracted: produkt_tu_stunde_19500101_20241231_01639.txt
Extracted: produkt_tu_stunde_20040501_20241231_01645.txt
Extracted: produkt_tu_stunde_20020101_20241231_01666.txt
Extracted: produkt_tu_stunde_19510101_20241231_01684.txt
Extracted: produkt_tu_stunde_19480101_20241231_01691.txt
Extracted: produkt_tu_stunde_19810101_20241231_01694.txt
Extracted: produkt_tu_stunde_20061001_20241231_01721.txt
Extracted: produkt_tu_stunde_20050301_20241231_01735.txt
Extracted: produkt_tu_stunde_20020124_20241231_01736.txt
Extracted: produkt_tu_stunde_19780101_20241231_01757.txt
Extracted: produkt_tu_stunde_19510101_19780101_01758.txt
Extracted: produkt_tu_stunde_20001025_20241231_01759.txt
Extracted: produkt_tu_stunde_19891001_20241231_01766.txt
Extracted: produkt_tu_stunde_20200814_20241231_01792.txt
Extracted: produkt_tu_stunde_19910101_20241231_01803.txt
Extracted: produkt_tu_stunde_19821101_20241231_01832.txt
Extracted: produkt_tu_stunde_19480101_19821101_01833.txt
Extracted: produkt_tu_stunde_19510101_19780701_01834.txt
Extracted: produkt_tu_stunde_20071201_20241231_01863.txt
Extracted: produkt_tu_stunde_19810101_20241231_01869.txt
Extracted: produkt_tu_stunde_20160901_20241231_01886.txt
Extracted: produkt_tu_stunde_19530101_20150323_01957.txt
Extracted: produkt_tu_stunde_19600101_19710101_01960.txt
Extracted: produkt_tu_stunde_20050501_20241231_01964.txt
Extracted: produkt_tu_stunde_19490101_20241231_01975.txt
Extracted: produkt_tu_stunde_20050301_20241231_01981.txt
Extracted: produkt_tu_stunde_19490101_20241231_02014.txt
Extracted: produkt_tu_stunde_20020101_20241231_02023.txt
Extracted: produkt_tu_stunde_20061101_20241231_02039.txt
Extracted: produkt_tu_stunde_19810101_20241231_02044.txt
Extracted: produkt_tu_stunde_20040601_20241231_02074.txt
Extracted: produkt_tu_stunde_20040701_20120912_02080.txt
Extracted: produkt_tu_stunde_19480101_19550101_02081.txt
Extracted: produkt_tu_stunde_20040601_20050512_02088.txt
Extracted: produkt_tu_stunde_20030101_20241201_02110.txt
Extracted: produkt_tu_stunde_19520501_20241231_02115.txt
Extracted: produkt_tu_stunde_19820101_19910502_02166.txt
Extracted: produkt_tu_stunde_20050301_20120402_02167.txt
Extracted: produkt_tu_stunde_19510101_20241231_02171.txt
Extracted: produkt_tu_stunde_20101101_20241231_02174.txt
Extracted: produkt_tu_stunde_20050801_20241231_02201.txt
Extracted: produkt_tu_stunde_20041001_20241231_02211.txt
Extracted: produkt_tu_stunde_20050701_20241231_02252.txt
Extracted: produkt_tu_stunde_19480101_20241231_02261.txt
Extracted: produkt_tu_stunde_19470101_20241231_02290.txt
Extracted: produkt_tu_stunde_20020101_20241231_02303.txt
Extracted: produkt_tu_stunde_20050801_20241231_02306.txt
Extracted: produkt_tu_stunde_20021101_20241231_02315.txt
Extracted: produkt_tu_stunde_20050601_20241231_02319.txt
Extracted: produkt_tu_stunde_20060701_20241231_02323.txt
Extracted: produkt_tu_stunde_20020101_20051223_02338.txt
Extracted: produkt_tu_stunde_20040801_20241231_02362.txt
Extracted: produkt_tu_stunde_19490101_19740701_02374.txt
Extracted: produkt_tu_stunde_20020101_20241231_02385.txt
Extracted: produkt_tu_stunde_19610102_20241231_02410.txt
Extracted: produkt_tu_stunde_20020101_20241231_02429.txt
Extracted: produkt_tu_stunde_20020101_20241231_02437.txt
Extracted: produkt_tu_stunde_19910801_20241231_02444.txt
Extracted: produkt_tu_stunde_20011017_20050826_02456.txt
Extracted: produkt_tu_stunde_20040901_20241231_02480.txt
Extracted: produkt_tu_stunde_19510101_20241231_02483.txt
Extracted: produkt_tu_stunde_20110502_20241231_02485.txt
Extracted: produkt_tu_stunde_20050301_20241231_02486.txt
Extracted: produkt_tu_stunde_19820101_20021001_02488.txt
Extracted: produkt_tu_stunde_20020101_20131020_02494.txt
Extracted: produkt_tu_stunde_20040801_20241231_02497.txt
Extracted: produkt_tu_stunde_19510101_20030505_02503.txt
Extracted: produkt_tu_stunde_19820101_19940401_02521.txt
Extracted: produkt_tu_stunde_19480101_20081031_02522.txt
Extracted: produkt_tu_stunde_19480101_20131031_02532.txt
Extracted: produkt_tu_stunde_19750601_20160402_02542.txt
Extracted: produkt_tu_stunde_19550101_20241231_02559.txt
Extracted: produkt_tu_stunde_20020101_20241231_02564.txt
Extracted: produkt_tu_stunde_19490101_19881015_02565.txt
Extracted: produkt_tu_stunde_20070523_20241231_02575.txt
Extracted: produkt_tu_stunde_20040701_20241231_02578.txt
Extracted: produkt_tu_stunde_19480101_20241231_02597.txt
Extracted: produkt_tu_stunde_20050301_20241231_02600.txt
Extracted: produkt_tu_stunde_19480101_20241231_02601.txt
Extracted: produkt_tu_stunde_20041001_20241231_02618.txt
Extracted: produkt_tu_stunde_20040701_20241231_02627.txt
Extracted: produkt_tu_stunde_20040701_20241231_02629.txt
Extracted: produkt_tu_stunde_19650701_20241231_02638.txt
Extracted: produkt_tu_stunde_20040901_20241231_02641.txt
Extracted: produkt_tu_stunde_19550101_19900101_02656.txt
Extracted: produkt_tu_stunde_19600101_20241231_02667.txt
Extracted: produkt_tu_stunde_20050601_20241231_02680.txt
Extracted: produkt_tu_stunde_19940401_19941101_02691.txt
Extracted: produkt_tu_stunde_20041201_20241231_02700.txt
Extracted: produkt_tu_stunde_20040501_20241231_02704.txt
Extracted: produkt_tu_stunde_20060701_20241231_02708.txt
Extracted: produkt_tu_stunde_19710101_20241231_02712.txt
Extracted: produkt_tu_stunde_19980101_19980201_02738.txt
Extracted: produkt_tu_stunde_20051101_20241231_02750.txt
Extracted: produkt_tu_stunde_19750601_19780601_02761.txt
Extracted: produkt_tu_stunde_20020101_20241231_02773.txt
Extracted: produkt_tu_stunde_19890101_20241231_02794.txt
Extracted: produkt_tu_stunde_20020101_20241231_02796.txt
Extracted: produkt_tu_stunde_19950101_20241231_02812.txt
Extracted: produkt_tu_stunde_19750601_20241231_02814.txt
Extracted: produkt_tu_stunde_19660101_20180710_02829.txt
Extracted: produkt_tu_stunde_20040701_20241231_02856.txt
Extracted: produkt_tu_stunde_20170801_20241231_02878.txt
Extracted: produkt_tu_stunde_20020101_20241231_02886.txt
Extracted: produkt_tu_stunde_20020101_20241231_02905.txt
Extracted: produkt_tu_stunde_19910101_20241231_02907.txt
Extracted: produkt_tu_stunde_19820101_19841101_02920.txt
Extracted: produkt_tu_stunde_19560101_20241231_02925.txt
Extracted: produkt_tu_stunde_19510101_20241231_02928.txt
Extracted: produkt_tu_stunde_19720501_20241231_02932.txt
Extracted: produkt_tu_stunde_20061001_20241231_02947.txt
Extracted: produkt_tu_stunde_20040601_20241231_02951.txt
Extracted: produkt_tu_stunde_20070401_20241231_02953.txt
Extracted: produkt_tu_stunde_20020101_20241231_02961.txt
Extracted: produkt_tu_stunde_20081201_20240831_02968.txt
Extracted: produkt_tu_stunde_19910305_20241231_02985.txt
Extracted: produkt_tu_stunde_19510101_20241231_03015.txt
Extracted: produkt_tu_stunde_19510101_20161231_03023.txt
Extracted: produkt_tu_stunde_19710401_20241231_03028.txt
Extracted: produkt_tu_stunde_20040701_20241231_03031.txt
Extracted: produkt_tu_stunde_19490101_20241231_03032.txt
Extracted: produkt_tu_stunde_20070101_20241231_03034.txt
Extracted: produkt_tu_stunde_20080601_20241231_03042.txt
Extracted: produkt_tu_stunde_20070701_20180601_03044.txt
Extracted: produkt_tu_stunde_20050101_20241231_03083.txt
Extracted: produkt_tu_stunde_19510101_19850301_03085.txt
Extracted: produkt_tu_stunde_19850301_20241231_03086.txt
Extracted: produkt_tu_stunde_19541201_20241231_03093.txt
Extracted: produkt_tu_stunde_19940101_20241231_03098.txt
Extracted: produkt_tu_stunde_19550101_20241231_03126.txt
Extracted: produkt_tu_stunde_20080501_20241231_03137.txt
Extracted: produkt_tu_stunde_19831101_20050101_03139.txt
Extracted: produkt_tu_stunde_19850101_20241231_03147.txt
Extracted: produkt_tu_stunde_20040801_20241231_03155.txt
Extracted: produkt_tu_stunde_19890101_20241231_03158.txt
Extracted: produkt_tu_stunde_20060701_20241231_03164.txt
Extracted: produkt_tu_stunde_19820101_20241231_03166.txt
Extracted: produkt_tu_stunde_19621201_20241231_03167.txt
Extracted: produkt_tu_stunde_20020101_20121221_03170.txt
Extracted: produkt_tu_stunde_20210801_20241231_03181.txt
Extracted: produkt_tu_stunde_19810101_20241231_03196.txt
Extracted: produkt_tu_stunde_20080701_20241231_03204.txt
Extracted: produkt_tu_stunde_20060801_20241231_03226.txt
Extracted: produkt_tu_stunde_19790101_20241231_03231.txt
Extracted: produkt_tu_stunde_20050201_20241231_03234.txt
Extracted: produkt_tu_stunde_19750601_20241231_03244.txt
Extracted: produkt_tu_stunde_20020102_20021120_03245.txt
Extracted: produkt_tu_stunde_20020101_20070613_03246.txt
Extracted: produkt_tu_stunde_20020102_20241231_03254.txt
Extracted: produkt_tu_stunde_20040601_20241231_03257.txt
Extracted: produkt_tu_stunde_20021101_20241231_03268.txt
Extracted: produkt_tu_stunde_20041101_20241231_03271.txt
Extracted: produkt_tu_stunde_19921001_19941001_03274.txt
Extracted: produkt_tu_stunde_20090401_20241231_03278.txt
Extracted: produkt_tu_stunde_20050501_20241231_03284.txt
Extracted: produkt_tu_stunde_19871001_20241231_03287.txt
Extracted: produkt_tu_stunde_20041101_20241231_03289.txt
Extracted: produkt_tu_stunde_20080401_20241231_03307.txt
Extracted: produkt_tu_stunde_20060901_20241231_03319.txt
Extracted: produkt_tu_stunde_20230501_20241231_03321.txt
Extracted: produkt_tu_stunde_20050501_20220329_03340.txt
Extracted: produkt_tu_stunde_20040601_20241231_03348.txt
Extracted: produkt_tu_stunde_20020101_20241231_03362.txt
Extracted: produkt_tu_stunde_19550101_20241231_03366.txt
Extracted: produkt_tu_stunde_19910101_20241231_03376.txt
Extracted: produkt_tu_stunde_19970701_20241231_03379.txt
Extracted: produkt_tu_stunde_19480101_19540101_03382.txt
Extracted: produkt_tu_stunde_19820101_19990331_03385.txt
Extracted: produkt_tu_stunde_19490101_19920517_03390.txt
Extracted: produkt_tu_stunde_20021101_20241231_03402.txt
Extracted: produkt_tu_stunde_19480101_19891001_03404.txt
Extracted: produkt_tu_stunde_20040601_20241231_03426.txt
Extracted: produkt_tu_stunde_20041001_20241231_03442.txt
Extracted: produkt_tu_stunde_19760701_20050818_03478.txt
Extracted: produkt_tu_stunde_20020101_20241231_03484.txt

# Extracting Temperature Recent

In [8]:
#Extract Temperature RECENT data files into extracted folder
import os
import zipfile
from pathlib import Path
# Folder containing all zip files
zip_folder = Path("Document_Corpus/dwd_temp/recent_zip")

# Output folder for extracted produkt files
output_folder = Path("Document_Corpus/dwd_temp/extracted")
output_folder.mkdir(parents=True, exist_ok=True)

print("ZIP folder:", zip_folder.resolve())
print("Output folder:", output_folder.resolve())



# Check how many ZIP files are available
zip_files = list(zip_folder.glob("*.zip"))
print(f"Total ZIP files found: {len(zip_files)}")

# Show first few zip names
for z in zip_files[:10]:
    print(z.name)

# Extract only files starting with produkt_st_stunde
extracted_files = []
errors = []

for zip_path in zip_files:
    try:
        with zipfile.ZipFile(zip_path, 'r') as z:
            matched = False
            
            for file_name in z.namelist():
                base_name = os.path.basename(file_name)
                
                if base_name.startswith("produkt_tu_stunde"):
                    
                    
                    matched = True
                    
                    # Add zip filename prefix to avoid overwriting files
                    #new_name = f"{zip_path.stem}_{base_name}"
                    new_name = f"{base_name}"
                    target_path = output_folder / new_name

                    with z.open(file_name) as source, open(target_path, "wb") as target:
                        target.write(source.read())

                    extracted_files.append(target_path.name)
                    print(f"Extracted: {target_path.name}")
            
            if not matched:
                print(f"No produkt_st_stunde file found in: {zip_path.name}")

    except Exception as e:
        errors.append((zip_path.name, str(e)))
        print(f"Error with {zip_path.name}: {e}")



# Summary
print("="*50)
print("EXTRACTION SUMMARY")
print("="*50)
print(f"ZIP files scanned: {len(zip_files)}")
print(f"Files extracted: {len(extracted_files)}")
print(f"Errors: {len(errors)}")

ZIP folder: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\dwd_temp\recent_zip
Output folder: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\dwd_temp\extracted
Total ZIP files found: 503
stundenwerte_TU_00044_akt.zip
stundenwerte_TU_00073_akt.zip
stundenwerte_TU_00078_akt.zip
stundenwerte_TU_00091_akt.zip
stundenwerte_TU_00096_akt.zip
stundenwerte_TU_00102_akt.zip
stundenwerte_TU_00125_akt.zip
stundenwerte_TU_00131_akt.zip
stundenwerte_TU_00142_akt.zip
stundenwerte_TU_00150_akt.zip
Extracted: produkt_tu_stunde_20241004_20260406_00044.txt
Extracted: produkt_tu_stunde_20241004_20260406_00073.txt
Extracted: produkt_tu_stunde_20241004_20260406_00078.txt
Extracted: produkt_tu_stunde_20241004_20260406_00091.txt
Extracted: produkt_tu_stunde_20241004_20260406_00096.txt
Extracted: produkt_tu_stunde_20241004_20260406_00102.txt
Extracted: produkt_tu_stunde_20241004_20260406_00125.txt
Extracted: produkt_tu_stunde_20241004_20260406_00131.txt
Extracted: produkt_tu_stunde_20241004_20260406_00142.txt
Extracted: produkt_tu_stunde_20241004_20260406_00150.txt
Extracted: produkt_tu_stunde_20241004_20260406_00151.txt
Extracted: produkt_tu_stunde_20241004_20260406_00154.txt
Extracted: produkt_tu_stunde_20241004_20260406_00161.txt
Extracted: produkt_tu_stunde_20241004_20260406_00164.txt
Extracted: produkt_tu_stunde_20241004_20260406_00167.txt
Extracted: produkt_tu_stunde_20241004_20260406_00183.txt
Extracted: produkt_tu_stunde_20241004_20260406_00191.txt
Extracted: produkt_tu_stunde_20241004_20260406_00198.txt
Extracted: produkt_tu_stunde_20241004_20260406_00217.txt
Extracted: produkt_tu_stunde_20241004_20260406_00222.txt
Extracted: produkt_tu_stunde_20241004_20260406_00232.txt
Extracted: produkt_tu_stunde_20241004_20260406_00257.txt
Extracted: produkt_tu_stunde_20241004_20260406_00259.txt
Extracted: produkt_tu_stunde_20241004_20260406_00282.txt
Extracted: produkt_tu_stunde_20241004_20260406_00294.txt
Extracted: produkt_tu_stunde_20241004_20260406_00298.txt
Extracted: produkt_tu_stunde_20241004_20260406_00303.txt
Extracted: produkt_tu_stunde_20241004_20260406_00314.txt
Extracted: produkt_tu_stunde_20241004_20260406_00320.txt
Extracted: produkt_tu_stunde_20241004_20260406_00330.txt
Extracted: produkt_tu_stunde_20241004_20260406_00342.txt
Extracted: produkt_tu_stunde_20241004_20260406_00368.txt
Extracted: produkt_tu_stunde_20241004_20260406_00377.txt
Extracted: produkt_tu_stunde_20241004_20260406_00379.txt
Extracted: produkt_tu_stunde_20241004_20260406_00390.txt
Extracted: produkt_tu_stunde_20241004_20260406_00400.txt
Extracted: produkt_tu_stunde_20241004_20260406_00403.txt
Extracted: produkt_tu_stunde_20241004_20260406_00420.txt
Extracted: produkt_tu_stunde_20241004_20260406_00427.txt
Extracted: produkt_tu_stunde_20241004_20260406_00433.txt
Extracted: produkt_tu_stunde_20241004_20260406_00445.txt
Extracted: produkt_tu_stunde_20241004_20260406_00460.txt
Extracted: produkt_tu_stunde_20241004_20260406_00535.txt
Extracted: produkt_tu_stunde_20241004_20260406_00555.txt
Extracted: produkt_tu_stunde_20241004_20260406_00591.txt
Extracted: produkt_tu_stunde_20241004_20260406_00596.txt
Extracted: produkt_tu_stunde_20241004_20260406_00603.txt
Extracted: produkt_tu_stunde_20241004_20260406_00617.txt
Extracted: produkt_tu_stunde_20241004_20260406_00656.txt
Extracted: produkt_tu_stunde_20241004_20260406_00662.txt
Extracted: produkt_tu_stunde_20241004_20260406_00691.txt
Extracted: produkt_tu_stunde_20241004_20260326_00701.txt
Extracted: produkt_tu_stunde_20241004_20260406_00704.txt
Extracted: produkt_tu_stunde_20241004_20260406_00722.txt
Extracted: produkt_tu_stunde_20241004_20260406_00755.txt
Extracted: produkt_tu_stunde_20241004_20260406_00757.txt
Extracted: produkt_tu_stunde_20241004_20260406_00760.txt
Extracted: produkt_tu_stunde_20241004_20260406_00766.txt
Extracted: produkt_tu_stunde_20241004_20260406_00769.txt
Extracted: produkt_tu_stunde_20241004_20260406_00817.txt
Extracted: produkt_tu_stunde_20241004_20260406_00840.txt
Extracted: produkt_tu_stunde_20241004_20260406_00850.txt
Extracted: produkt_tu_stunde_20241004_20260406_00853.txt
Extracted: produkt_tu_stunde_20241004_20260406_00856.txt
Extracted: produkt_tu_stunde_20241004_20260406_00860.txt
Extracted: produkt_tu_stunde_20241004_20260406_00867.txt
Extracted: produkt_tu_stunde_20241004_20260406_00880.txt
Extracted: produkt_tu_stunde_20241004_20260406_00891.txt
Extracted: produkt_tu_stunde_20241004_20260406_00896.txt
Extracted: produkt_tu_stunde_20241004_20260406_00917.txt
Extracted: produkt_tu_stunde_20241004_20260406_00953.txt
Extracted: produkt_tu_stunde_20241004_20260406_00954.txt
Extracted: produkt_tu_stunde_20241004_20260406_00963.txt
Extracted: produkt_tu_stunde_20241004_20260406_00983.txt
Extracted: produkt_tu_stunde_20241004_20260406_00991.txt
Extracted: produkt_tu_stunde_20241004_20260406_01001.txt
Extracted: produkt_tu_stunde_20241004_20260406_01048.txt
Extracted: produkt_tu_stunde_20241004_20260406_01050.txt
Extracted: produkt_tu_stunde_20230814_20230814_01051.txt
Extracted: produkt_tu_stunde_20241004_20260406_01052.txt
Extracted: produkt_tu_stunde_20241004_20260406_01072.txt
Extracted: produkt_tu_stunde_20241004_20260406_01078.txt
Extracted: produkt_tu_stunde_20241004_20260406_01103.txt
Extracted: produkt_tu_stunde_20241004_20260406_01107.txt
Extracted: produkt_tu_stunde_20241004_20260406_01161.txt
Extracted: produkt_tu_stunde_20241004_20260406_01197.txt
Extracted: produkt_tu_stunde_20241004_20260406_01200.txt
Extracted: produkt_tu_stunde_20241004_20260406_01207.txt
Extracted: produkt_tu_stunde_20241004_20260406_01214.txt
Extracted: produkt_tu_stunde_20241004_20260406_01224.txt
Extracted: produkt_tu_stunde_20241004_20250723_01228.txt
Extracted: produkt_tu_stunde_20241004_20260406_01246.txt
Extracted: produkt_tu_stunde_20241004_20260406_01255.txt
Extracted: produkt_tu_stunde_20241004_20260406_01262.txt
Extracted: produkt_tu_stunde_20241004_20260406_01266.txt
Extracted: produkt_tu_stunde_20241004_20260406_01270.txt
Extracted: produkt_tu_stunde_20241004_20260406_01279.txt
Extracted: produkt_tu_stunde_20241004_20260406_01297.txt
Extracted: produkt_tu_stunde_20241004_20260406_01300.txt
Extracted: produkt_tu_stunde_20241004_20260406_01303.txt
Extracted: produkt_tu_stunde_20241004_20260406_01327.txt
Extracted: produkt_tu_stunde_20241004_20260406_01332.txt
Extracted: produkt_tu_stunde_20241004_20260406_01339.txt
Extracted: produkt_tu_stunde_20241004_20260406_01346.txt
Extracted: produkt_tu_stunde_20241004_20260406_01357.txt
Extracted: produkt_tu_stunde_20241004_20260406_01358.txt
Extracted: produkt_tu_stunde_20241004_20260406_01411.txt
Extracted: produkt_tu_stunde_20241004_20260406_01420.txt
Extracted: produkt_tu_stunde_20241004_20260406_01424.txt
Extracted: produkt_tu_stunde_20241004_20260406_01443.txt
Extracted: produkt_tu_stunde_20241004_20260406_01451.txt
Extracted: produkt_tu_stunde_20241004_20260406_01468.txt
Extracted: produkt_tu_stunde_20241004_20260406_01503.txt
Extracted: produkt_tu_stunde_20241004_20260406_01504.txt
Extracted: produkt_tu_stunde_20241004_20260406_01526.txt
Extracted: produkt_tu_stunde_20241004_20260406_01544.txt
Extracted: produkt_tu_stunde_20241004_20260406_01550.txt
Extracted: produkt_tu_stunde_20241004_20260406_01572.txt
Extracted: produkt_tu_stunde_20241004_20260406_01580.txt
Extracted: produkt_tu_stunde_20241004_20241031_01584.txt
Extracted: produkt_tu_stunde_20241004_20260406_01587.txt
Extracted: produkt_tu_stunde_20241004_20260406_01590.txt
Extracted: produkt_tu_stunde_20241004_20260406_01602.txt
Extracted: produkt_tu_stunde_20241004_20260406_01605.txt
Extracted: produkt_tu_stunde_20241004_20260406_01612.txt
Extracted: produkt_tu_stunde_20241004_20260406_01639.txt
Extracted: produkt_tu_stunde_20241004_20260406_01645.txt
Extracted: produkt_tu_stunde_20241004_20260406_01666.txt
Extracted: produkt_tu_stunde_20241004_20260406_01684.txt
Extracted: produkt_tu_stunde_20241004_20260406_01691.txt
Extracted: produkt_tu_stunde_20241004_20260406_01694.txt
Extracted: produkt_tu_stunde_20241004_20260406_01721.txt
Extracted: produkt_tu_stunde_20241004_20260406_01735.txt
Extracted: produkt_tu_stunde_20241004_20260406_01736.txt
Extracted: produkt_tu_stunde_20241004_20260406_01757.txt
Extracted: produkt_tu_stunde_20241004_20260406_01759.txt
Extracted: produkt_tu_stunde_20241004_20260406_01766.txt
Extracted: produkt_tu_stunde_20241004_20260406_01792.txt
Extracted: produkt_tu_stunde_20241004_20260406_01803.txt
Extracted: produkt_tu_stunde_20241004_20260406_01832.txt
Extracted: produkt_tu_stunde_20241004_20260406_01863.txt
Extracted: produkt_tu_stunde_20241004_20260406_01869.txt
Extracted: produkt_tu_stunde_20241004_20260406_01886.txt
Extracted: produkt_tu_stunde_20241004_20260406_01964.txt
Extracted: produkt_tu_stunde_20241004_20260406_01975.txt
Extracted: produkt_tu_stunde_20241004_20260406_01981.txt
Extracted: produkt_tu_stunde_20241004_20260406_02014.txt
Extracted: produkt_tu_stunde_20241004_20260406_02023.txt
Extracted: produkt_tu_stunde_20241004_20260406_02039.txt
Extracted: produkt_tu_stunde_20241004_20260406_02044.txt
Extracted: produkt_tu_stunde_20241004_20260406_02074.txt
Extracted: produkt_tu_stunde_20241004_20241201_02110.txt
Extracted: produkt_tu_stunde_20241004_20260406_02115.txt
Extracted: produkt_tu_stunde_20241004_20260406_02171.txt
Extracted: produkt_tu_stunde_20241004_20260406_02174.txt
Extracted: produkt_tu_stunde_20241004_20260406_02201.txt
Extracted: produkt_tu_stunde_20241004_20260406_02211.txt
Extracted: produkt_tu_stunde_20241004_20260406_02252.txt
Extracted: produkt_tu_stunde_20241004_20260406_02261.txt
Extracted: produkt_tu_stunde_20241004_20260406_02290.txt
Extracted: produkt_tu_stunde_20241004_20260406_02303.txt
Extracted: produkt_tu_stunde_20241004_20260406_02306.txt
Extracted: produkt_tu_stunde_20241004_20260406_02315.txt
Extracted: produkt_tu_stunde_20241004_20260406_02319.txt
Extracted: produkt_tu_stunde_20241004_20260406_02323.txt
Extracted: produkt_tu_stunde_20241004_20260406_02362.txt
Extracted: produkt_tu_stunde_20241004_20260406_02385.txt
Extracted: produkt_tu_stunde_20241004_20260406_02410.txt
Extracted: produkt_tu_stunde_20241004_20260406_02429.txt
Extracted: produkt_tu_stunde_20241004_20260406_02437.txt
Extracted: produkt_tu_stunde_20241004_20260406_02444.txt
Extracted: produkt_tu_stunde_20241004_20260406_02480.txt
Extracted: produkt_tu_stunde_20241004_20260406_02483.txt
Extracted: produkt_tu_stunde_20241004_20260406_02485.txt
Extracted: produkt_tu_stunde_20241004_20260406_02486.txt
Extracted: produkt_tu_stunde_20241004_20260406_02497.txt
Extracted: produkt_tu_stunde_20241004_20260406_02559.txt
Extracted: produkt_tu_stunde_20241004_20260406_02564.txt
Extracted: produkt_tu_stunde_20241004_20260406_02575.txt
Extracted: produkt_tu_stunde_20241004_20260406_02578.txt
Extracted: produkt_tu_stunde_20241004_20260406_02597.txt
Extracted: produkt_tu_stunde_20241004_20260406_02600.txt
Extracted: produkt_tu_stunde_20241004_20260406_02601.txt
Extracted: produkt_tu_stunde_20241004_20260406_02618.txt
Extracted: produkt_tu_stunde_20241004_20260406_02627.txt
Extracted: produkt_tu_stunde_20241004_20260406_02629.txt
Extracted: produkt_tu_stunde_20241004_20260406_02638.txt
Extracted: produkt_tu_stunde_20241004_20260406_02641.txt
Extracted: produkt_tu_stunde_20241004_20260406_02667.txt
Extracted: produkt_tu_stunde_20241004_20260406_02680.txt
Extracted: produkt_tu_stunde_20241004_20260406_02700.txt
Extracted: produkt_tu_stunde_20241004_20260406_02704.txt
Extracted: produkt_tu_stunde_20241004_20260406_02708.txt
Extracted: produkt_tu_stunde_20241004_20260406_02712.txt
Extracted: produkt_tu_stunde_20241004_20260406_02750.txt
Extracted: produkt_tu_stunde_20241004_20260406_02773.txt
Extracted: produkt_tu_stunde_20241004_20260406_02794.txt
Extracted: produkt_tu_stunde_20241004_20260406_02796.txt
Extracted: produkt_tu_stunde_20241004_20260406_02812.txt
Extracted: produkt_tu_stunde_20241004_20260228_02814.txt
Extracted: produkt_tu_stunde_20241004_20260406_02856.txt
Extracted: produkt_tu_stunde_20241004_20260406_02878.txt
Extracted: produkt_tu_stunde_20241004_20260406_02886.txt
Extracted: produkt_tu_stunde_20241004_20260406_02905.txt
Extracted: produkt_tu_stunde_20241004_20260406_02907.txt
Extracted: produkt_tu_stunde_20241004_20260406_02925.txt
Extracted: produkt_tu_stunde_20241004_20260406_02928.txt
Extracted: produkt_tu_stunde_20241004_20260406_02932.txt
Extracted: produkt_tu_stunde_20241004_20260406_02947.txt
Extracted: produkt_tu_stunde_20241004_20260406_02951.txt
Extracted: produkt_tu_stunde_20241004_20260406_02953.txt
Extracted: produkt_tu_stunde_20241004_20260406_02961.txt
Extracted: produkt_tu_stunde_20240831_20240831_02968.txt
Extracted: produkt_tu_stunde_20241004_20260406_02985.txt
Extracted: produkt_tu_stunde_20241004_20260406_03015.txt
Extracted: produkt_tu_stunde_20241004_20260406_03028.txt
Extracted: produkt_tu_stunde_20241004_20260406_03031.txt
Extracted: produkt_tu_stunde_20241004_20260406_03032.txt
Extracted: produkt_tu_stunde_20241004_20260406_03034.txt
Extracted: produkt_tu_stunde_20241004_20260406_03042.txt
Extracted: produkt_tu_stunde_20241004_20260406_03083.txt
Extracted: produkt_tu_stunde_20241004_20260406_03086.txt
Extracted: produkt_tu_stunde_20241004_20260406_03093.txt
Extracted: produkt_tu_stunde_20241004_20260406_03098.txt
Extracted: produkt_tu_stunde_20241004_20260406_03126.txt
Extracted: produkt_tu_stunde_20241004_20260406_03137.txt
Extracted: produkt_tu_stunde_20241004_20260406_03147.txt
Extracted: produkt_tu_stunde_20241004_20260406_03155.txt
Extracted: produkt_tu_stunde_20241004_20260406_03158.txt
Extracted: produkt_tu_stunde_20241004_20260406_03164.txt
Extracted: produkt_tu_stunde_20241004_20260406_03166.txt
Extracted: produkt_tu_stunde_20241004_20260406_03167.txt
Extracted: produkt_tu_stunde_20241004_20260406_03181.txt
Extracted: produkt_tu_stunde_20241004_20260406_03196.txt
Extracted: produkt_tu_stunde_20241004_20260406_03204.txt
Extracted: produkt_tu_stunde_20241004_20260406_03226.txt
Extracted: produkt_tu_stunde_20241004_20260406_03231.txt
Extracted: produkt_tu_stunde_20241004_20260406_03234.txt
Extracted: produkt_tu_stunde_20241004_20260406_03244.txt
Extracted: produkt_tu_stunde_20241004_20260406_03254.txt
Extracted: produkt_tu_stunde_20241004_20260406_03257.txt
Extracted: produkt_tu_stunde_20241004_20260406_03268.txt
Extracted: produkt_tu_stunde_20241004_20260406_03271.txt
Extracted: produkt_tu_stunde_20241004_20260406_03278.txt
Extracted: produkt_tu_stunde_20241004_20260406_03284.txt
Extracted: produkt_tu_stunde_20241004_20260406_03287.txt
Extracted: produkt_tu_stunde_20241004_20260406_03289.txt
Extracted: produkt_tu_stunde_20241004_20260406_03307.txt
Extracted: produkt_tu_stunde_20241004_20260406_03319.txt
Extracted: produkt_tu_stunde_20241004_20260406_03321.txt
Extracted: produkt_tu_stunde_20241004_20260406_03348.txt
Extracted: produkt_tu_stunde_20241004_20260406_03362.txt
Extracted: produkt_tu_stunde_20241004_20260406_03366.txt
Extracted: produkt_tu_stunde_20241004_20260406_03376.txt
Extracted: produkt_tu_stunde_20241004_20260406_03379.txt
Extracted: produkt_tu_stunde_20241004_20260406_03402.txt
Extracted: produkt_tu_stunde_20241004_20260406_03426.txt
Extracted: produkt_tu_stunde_20241004_20260406_03442.txt
Extracted: produkt_tu_stunde_20241004_20260406_03484.txt
Extracted: produkt_tu_stunde_20241004_20260406_03485.txt
Extracted: produkt_tu_stunde_20241004_20260406_03490.txt
Extracted: produkt_tu_stunde_20241004_20260406_03509.txt
Extracted: produkt_tu_stunde_20241004_20260406_03513.txt
Extracted: produkt_tu_stunde_20241004_20260406_03527.txt
Extracted: produkt_tu_stunde_20241004_20260406_03540.txt
Extracted: produkt_tu_stunde_20241004_20260406_03545.txt
Extracted: produkt_tu_stunde_20241004_20260406_03571.txt
Extracted: produkt_tu_stunde_20241004_20260406_03591.txt
Extracted: produkt_tu_stunde_20241004_20260406_03603.txt
Extracted: produkt_tu_stunde_20241004_20250630_03612.txt
Extracted: produkt_tu_stunde_20241004_20260406_03621.txt
Extracted: produkt_tu_stunde_20241004_20260406_03623.txt
Extracted: produkt_tu_stunde_20241004_20260406_03631.txt
Extracted: produkt_tu_stunde_20241004_20260406_03639.txt
Extracted: produkt_tu_stunde_20241004_20260406_03660.txt
Extracted: produkt_tu_stunde_20241004_20260406_03667.txt
Extracted: produkt_tu_stunde_20241004_20260406_03668.txt
Extracted: produkt_tu_stunde_20241004_20260406_03679.txt
Extracted: produkt_tu_stunde_20241004_20260406_03730.txt
Extracted: produkt_tu_stunde_20241004_20260406_03734.txt
Extracted: produkt_tu_stunde_20241004_20260406_03739.txt
Extracted: produkt_tu_stunde_20241004_20260406_03761.txt
Extracted: produkt_tu_stunde_20241004_20260406_03811.txt
Extracted: produkt_tu_stunde_20241004_20260406_03821.txt
Extracted: produkt_tu_stunde_20241004_20260406_03836.txt
Extracted: produkt_tu_stunde_20241004_20260406_03857.txt
Extracted: produkt_tu_stunde_20241004_20260406_03875.txt
Extracted: produkt_tu_stunde_20241004_20260406_03897.txt
Extracted: produkt_tu_stunde_20241004_20260406_03904.txt
Extracted: produkt_tu_stunde_20241004_20260406_03925.txt
Extracted: produkt_tu_stunde_20241004_20260406_03927.txt
Extracted: produkt_tu_stunde_20241004_20260406_03939.txt
Extracted: produkt_tu_stunde_20241004_20260406_03946.txt
Extracted: produkt_tu_stunde_20241004_20260406_03975.txt
Extracted: produkt_tu_stunde_20241004_20260406_03987.txt
Extracted: produkt_tu_stunde_20241004_20260406_04024.txt
Extracted: produkt_tu_stunde_20241004_20260406_04032.txt
Extracted: produkt_tu_stunde_20241004_20260406_04036.txt
Extracted: produkt_tu_stunde_20241004_20260406_04039.txt
Extracted: produkt_tu_stunde_20241004_20260406_04063.txt
Extracted: produkt_tu_stunde_20241004_20260406_04094.txt
Extracted: produkt_tu_stunde_20241004_20260406_04104.txt
Extracted: produkt_tu_stunde_20241004_20260406_04127.txt
Extracted: produkt_tu_stunde_20241004_20260406_04160.txt
Extracted: produkt_tu_stunde_20241004_20260406_04169.txt
Extracted: produkt_tu_stunde_20241004_20260406_04175.txt
Extracted: produkt_tu_stunde_20241004_20260406_04177.txt
Extracted: produkt_tu_stunde_20241004_20260406_04189.txt
Extracted: produkt_tu_stunde_20240412_20240412_04261.txt
Extracted: produkt_tu_stunde_20241004_20260406_04271.txt
Extracted: produkt_tu_stunde_20241004_20260406_04275.txt
Extracted: produkt_tu_stunde_20241004_20260406_04280.txt
Extracted: produkt_tu_stunde_20241004_20260406_04287.txt
Extracted: produkt_tu_stunde_20241004_20260406_04300.txt
Extracted: produkt_tu_stunde_20241004_20260406_04301.txt
Extracted: produkt_tu_stunde_20241004_20260406_04323.txt
Extracted: produkt_tu_stunde_20241004_20260406_04336.txt
Extracted: produkt_tu_stunde_20241004_20260406_04349.txt
Extracted: produkt_tu_stunde_20241004_20260406_04354.txt
Extracted: produkt_tu_stunde_20241004_20260406_04371.txt
Extracted: produkt_tu_stunde_20241004_20260406_04377.txt
Extracted: produkt_tu_stunde_20241004_20260406_04393.txt
Extracted: produkt_tu_stunde_20241004_20260406_04411.txt
Extracted: produkt_tu_stunde_20241004_20260406_04445.txt
Extracted: produkt_tu_stunde_20241004_20260406_04464.txt
Extracted: produkt_tu_stunde_20241004_20260406_04466.txt
Extracted: produkt_tu_stunde_20241004_20260406_04480.txt
Extracted: produkt_tu_stunde_20241004_20260406_04501.txt
Extracted: produkt_tu_stunde_20241004_20260406_04508.txt
Extracted: produkt_tu_stunde_20241004_20260406_04548.txt
Extracted: produkt_tu_stunde_20241004_20260406_04559.txt
Extracted: produkt_tu_stunde_20241004_20260406_04592.txt
Extracted: produkt_tu_stunde_20241004_20260406_04605.txt
Extracted: produkt_tu_stunde_20241004_20260406_04625.txt
Extracted: produkt_tu_stunde_20241004_20260406_04642.txt
Extracted: produkt_tu_stunde_20241004_20260406_04651.txt
Extracted: produkt_tu_stunde_20241004_20260406_04703.txt
Extracted: produkt_tu_stunde_20241004_20260406_04704.txt
Extracted: produkt_tu_stunde_20241004_20260406_04706.txt
Extracted: produkt_tu_stunde_20241004_20260406_04709.txt
Extracted: produkt_tu_stunde_20241004_20260406_04745.txt

# Extracting Wind Historical

In [9]:
#Extract Wind HISTORICAL data files into extracted folder
import os
import zipfile
from pathlib import Path
# Folder containing all zip files
zip_folder = Path("Document_Corpus/dwd_wind/historical_zip")

# Output folder for extracted produkt files
output_folder = Path("Document_Corpus/dwd_wind/extracted")
output_folder.mkdir(parents=True, exist_ok=True)

print("ZIP folder:", zip_folder.resolve())
print("Output folder:", output_folder.resolve())



# Check how many ZIP files are available
zip_files = list(zip_folder.glob("*.zip"))
print(f"Total ZIP files found: {len(zip_files)}")

# Show first few zip names
for z in zip_files[:10]:
    print(z.name)

# Extract only files starting with produkt_st_stunde
extracted_files = []
errors = []

for zip_path in zip_files:
    try:
        with zipfile.ZipFile(zip_path, 'r') as z:
            matched = False
            
            for file_name in z.namelist():
                base_name = os.path.basename(file_name)
                
                if base_name.startswith("produkt_ff_stunde"):
                    
                    
                    matched = True
                    
                    # Add zip filename prefix to avoid overwriting files
                    #new_name = f"{zip_path.stem}_{base_name}"
                    new_name = f"{base_name}"
                    target_path = output_folder / new_name

                    with z.open(file_name) as source, open(target_path, "wb") as target:
                        target.write(source.read())

                    extracted_files.append(target_path.name)
                    print(f"Extracted: {target_path.name}")
            
            if not matched:
                print(f"No produkt_st_stunde file found in: {zip_path.name}")

    except Exception as e:
        errors.append((zip_path.name, str(e)))
        print(f"Error with {zip_path.name}: {e}")



# Summary
print("="*50)
print("EXTRACTION SUMMARY")
print("="*50)
print(f"ZIP files scanned: {len(zip_files)}")
print(f"Files extracted: {len(extracted_files)}")
print(f"Errors: {len(errors)}")

ZIP folder: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\dwd_wind\historical_zip
Output folder: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\dwd_wind\extracted
Total ZIP files found: 453
stundenwerte_FF_00003_19370101_20110331_hist.zip
stundenwerte_FF_00011_19800901_20241231_hist.zip
stundenwerte_FF_00044_19690101_19951130_hist.zip
stundenwerte_FF_00052_19690101_20011231_hist.zip
stundenwerte_FF_00072_19780901_19950531_hist.zip
stundenwerte_FF_00090_19880219_20241231_hist.zip
stundenwerte_FF_00096_20190409_20241231_hist.zip
stundenwerte_FF_00102_20010404_20241231_hist.zip
stundenwerte_FF_00125_19740301_20241231_hist.zip
stundenwerte_FF_00126_19791101_20101130_hist.zip
Extracted: produkt_ff_stunde_19370101_20110331_00003.txt
Extracted: produkt_ff_stunde_19800901_20241231_00011.txt
Extracted: produkt_ff_stunde_19690101_19951130_00044.txt
Extracted: produkt_ff_stunde_19690101_20011231_00052.txt
Extracted: produkt_ff_stunde_19780901_19950531_00072.txt
Extracted: produkt_ff_stunde_19880219_20241231_00090.txt
Extracted: produkt_ff_stunde_20190409_20241231_00096.txt
Extracted: produkt_ff_stunde_20010404_20241231_00102.txt
Extracted: produkt_ff_stunde_19740301_20241231_00125.txt
Extracted: produkt_ff_stunde_19791101_20101130_00126.txt
Extracted: produkt_ff_stunde_19801201_20241231_00161.txt
Extracted: produkt_ff_stunde_19790101_20241231_00164.txt
Extracted: produkt_ff_stunde_19740201_19760430_00175.txt
Extracted: produkt_ff_stunde_19991101_20081102_00181.txt
Extracted: produkt_ff_stunde_19730101_20241231_00183.txt
Extracted: produkt_ff_stunde_19790901_19871231_00193.txt
Extracted: produkt_ff_stunde_19900801_20241231_00197.txt
Extracted: produkt_ff_stunde_19610101_20241231_00198.txt
Extracted: produkt_ff_stunde_19820101_20080701_00222.txt
Extracted: produkt_ff_stunde_19610101_20241231_00232.txt
Extracted: produkt_ff_stunde_19780501_19930731_00259.txt
Extracted: produkt_ff_stunde_19710801_20241231_00282.txt
Extracted: produkt_ff_stunde_19810101_20241231_00298.txt
Extracted: produkt_ff_stunde_19930906_20241231_00303.txt
Extracted: produkt_ff_stunde_19790101_19970131_00320.txt
Extracted: produkt_ff_stunde_19770301_20080531_00330.txt
Extracted: produkt_ff_stunde_20101201_20241231_00342.txt
Extracted: produkt_ff_stunde_19891214_20110901_00348.txt
Extracted: produkt_ff_stunde_19730101_20241231_00368.txt
Extracted: produkt_ff_stunde_19750401_20150630_00399.txt
Extracted: produkt_ff_stunde_19910101_20001025_00400.txt
Extracted: produkt_ff_stunde_19750101_19801231_00424.txt
Extracted: produkt_ff_stunde_19730101_20241231_00427.txt
Extracted: produkt_ff_stunde_19870101_20210505_00430.txt
Extracted: produkt_ff_stunde_19740101_20241231_00433.txt
Extracted: produkt_ff_stunde_19690101_20241231_00460.txt
Extracted: produkt_ff_stunde_19700601_19741231_00553.txt
Extracted: produkt_ff_stunde_19750101_20060228_00554.txt
Extracted: produkt_ff_stunde_19730101_20241231_00591.txt
Extracted: produkt_ff_stunde_19730101_20241231_00596.txt
Extracted: produkt_ff_stunde_19750101_19990228_00599.txt
Extracted: produkt_ff_stunde_19860801_20241231_00603.txt
Extracted: produkt_ff_stunde_19870501_20241231_00619.txt
Extracted: produkt_ff_stunde_19810101_20241231_00642.txt
Extracted: produkt_ff_stunde_19370101_20241231_00656.txt
Extracted: produkt_ff_stunde_19660101_20241231_00662.txt
Extracted: produkt_ff_stunde_19260101_20241231_00691.txt
Extracted: produkt_ff_stunde_19520101_20241231_00701.txt
Extracted: produkt_ff_stunde_19790401_20241231_00704.txt
Extracted: produkt_ff_stunde_19690901_19920831_00706.txt
Extracted: produkt_ff_stunde_19560101_20241231_00722.txt
Extracted: produkt_ff_stunde_19650101_20241231_00766.txt
Extracted: produkt_ff_stunde_19720101_20060930_00769.txt
Extracted: produkt_ff_stunde_19650101_20241231_00788.txt
Extracted: produkt_ff_stunde_19900501_20241231_00840.txt
Extracted: produkt_ff_stunde_19740801_20150630_00850.txt
Extracted: produkt_ff_stunde_19610101_20241231_00853.txt
Extracted: produkt_ff_stunde_20030101_20241231_00856.txt
Extracted: produkt_ff_stunde_19720101_20241231_00867.txt
Extracted: produkt_ff_stunde_19730101_19881231_00876.txt
Extracted: produkt_ff_stunde_19830101_20241231_00880.txt
Extracted: produkt_ff_stunde_19690101_20241231_00891.txt
Extracted: produkt_ff_stunde_19690101_20241231_00953.txt
Extracted: produkt_ff_stunde_20010403_20241231_00954.txt
Extracted: produkt_ff_stunde_19740101_20241231_00963.txt
Extracted: produkt_ff_stunde_19500101_20090201_00998.txt
Extracted: produkt_ff_stunde_19810101_20241231_01001.txt
Extracted: produkt_ff_stunde_19870401_20080923_01010.txt
Extracted: produkt_ff_stunde_19901011_20241231_01011.txt
Extracted: produkt_ff_stunde_19800401_20241231_01013.txt
Extracted: produkt_ff_stunde_19730101_20241231_01048.txt
Extracted: produkt_ff_stunde_19520101_20241231_01078.txt
Extracted: produkt_ff_stunde_19720401_20040229_01130.txt
Extracted: produkt_ff_stunde_20070101_20241231_01200.txt
Extracted: produkt_ff_stunde_19750101_19980310_01219.txt
Extracted: produkt_ff_stunde_19500301_19741231_01221.txt
Extracted: produkt_ff_stunde_20010424_20241231_01228.txt
Extracted: produkt_ff_stunde_19690101_19920731_01261.txt
Extracted: produkt_ff_stunde_19920519_20241231_01262.txt
Extracted: produkt_ff_stunde_19730101_20241231_01270.txt
Extracted: produkt_ff_stunde_19801201_19850718_01297.txt
Extracted: produkt_ff_stunde_19630101_20241231_01303.txt
Extracted: produkt_ff_stunde_19710101_20241231_01339.txt
Extracted: produkt_ff_stunde_19550101_20241231_01346.txt
Extracted: produkt_ff_stunde_19931215_20241231_01357.txt
Extracted: produkt_ff_stunde_19550101_20241231_01358.txt
Extracted: produkt_ff_stunde_19820101_19921126_01359.txt
Extracted: produkt_ff_stunde_19821201_20241231_01379.txt
Extracted: produkt_ff_stunde_19760601_19881231_01415.txt
Extracted: produkt_ff_stunde_19840401_19871231_01416.txt
Extracted: produkt_ff_stunde_19670101_20241231_01420.txt
Extracted: produkt_ff_stunde_19730801_19890430_01422.txt
Extracted: produkt_ff_stunde_19720501_19871231_01423.txt
Extracted: produkt_ff_stunde_19510501_19621231_01425.txt
Extracted: produkt_ff_stunde_19640101_19841231_01426.txt
Extracted: produkt_ff_stunde_19550101_20241231_01443.txt
Extracted: produkt_ff_stunde_19701001_20241231_01468.txt
Extracted: produkt_ff_stunde_19650101_20241231_01490.txt
Extracted: produkt_ff_stunde_20121001_20241231_01503.txt
Extracted: produkt_ff_stunde_19750101_20071031_01505.txt
Extracted: produkt_ff_stunde_19690101_19911231_01515.txt
Extracted: produkt_ff_stunde_19770301_19930729_01526.txt
Extracted: produkt_ff_stunde_19590101_20241231_01544.txt
Extracted: produkt_ff_stunde_19690101_20241231_01550.txt
Extracted: produkt_ff_stunde_19821201_20041231_01572.txt
Extracted: produkt_ff_stunde_19510101_20241231_01580.txt
Extracted: produkt_ff_stunde_20031210_20241231_01587.txt
Extracted: produkt_ff_stunde_19820101_20241231_01605.txt
Extracted: produkt_ff_stunde_19730101_20241231_01612.txt
Extracted: produkt_ff_stunde_19390101_20241231_01639.txt
Extracted: produkt_ff_stunde_19710101_20071231_01666.txt
Extracted: produkt_ff_stunde_19630101_20241231_01684.txt
Extracted: produkt_ff_stunde_19900701_19920630_01689.txt
Extracted: produkt_ff_stunde_19690101_20241231_01691.txt
Extracted: produkt_ff_stunde_19810901_20241231_01694.txt
Extracted: produkt_ff_stunde_19780101_20241231_01757.txt
Extracted: produkt_ff_stunde_19610101_19771231_01758.txt
Extracted: produkt_ff_stunde_20001025_20241231_01759.txt
Extracted: produkt_ff_stunde_19820101_20241231_01766.txt
Extracted: produkt_ff_stunde_19910101_20241231_01803.txt
Extracted: produkt_ff_stunde_19830901_20040827_01831.txt
Extracted: produkt_ff_stunde_19821101_20241231_01832.txt
Extracted: produkt_ff_stunde_19730101_19780630_01834.txt
Extracted: produkt_ff_stunde_19810101_20241231_01869.txt
Extracted: produkt_ff_stunde_20091126_20241231_01886.txt
Extracted: produkt_ff_stunde_19790401_20030331_01920.txt
Extracted: produkt_ff_stunde_19720101_20150323_01957.txt
Extracted: produkt_ff_stunde_19450101_19751231_01960.txt
Extracted: produkt_ff_stunde_19690101_20241231_01963.txt
Extracted: produkt_ff_stunde_19500101_20241231_01975.txt
Extracted: produkt_ff_stunde_19690101_19970331_01987.txt
Extracted: produkt_ff_stunde_19761201_20241231_01993.txt
Extracted: produkt_ff_stunde_19500101_20241231_02014.txt
Extracted: produkt_ff_stunde_20021113_20241231_02023.txt
Extracted: produkt_ff_stunde_19810101_20241231_02044.txt
Extracted: produkt_ff_stunde_19871113_20141228_02055.txt
Extracted: produkt_ff_stunde_19690101_19820930_02093.txt
Extracted: produkt_ff_stunde_20181201_20191117_02100.txt
Extracted: produkt_ff_stunde_19590101_20241231_02115.txt
Extracted: produkt_ff_stunde_19820101_19910502_02166.txt
Extracted: produkt_ff_stunde_19760401_20241231_02171.txt
Extracted: produkt_ff_stunde_19590108_19790618_02201.txt
Extracted: produkt_ff_stunde_19740301_19781231_02207.txt
Extracted: produkt_ff_stunde_19790101_20041231_02228.txt
Extracted: produkt_ff_stunde_19971105_20241231_02252.txt
Extracted: produkt_ff_stunde_19831001_19960731_02253.txt
Extracted: produkt_ff_stunde_19480101_20241231_02261.txt
Extracted: produkt_ff_stunde_19390101_20241231_02290.txt
Extracted: produkt_ff_stunde_19690101_20241231_02303.txt
Extracted: produkt_ff_stunde_20090101_20241231_02315.txt
Extracted: produkt_ff_stunde_19740601_20051223_02338.txt
Extracted: produkt_ff_stunde_19891030_20241231_02349.txt
Extracted: produkt_ff_stunde_19650101_19711016_02374.txt
Extracted: produkt_ff_stunde_19810101_20241231_02377.txt
Extracted: produkt_ff_stunde_19740401_20241231_02385.txt
Extracted: produkt_ff_stunde_19740101_20241231_02410.txt
Extracted: produkt_ff_stunde_19880301_20241231_02429.txt
Extracted: produkt_ff_stunde_19710101_20080131_02437.txt
Extracted: produkt_ff_stunde_19920201_19980331_02444.txt
Extracted: produkt_ff_stunde_19690101_20040630_02456.txt
Extracted: produkt_ff_stunde_19810501_19901231_02465.txt
Extracted: produkt_ff_stunde_19781201_19800430_02482.txt
Extracted: produkt_ff_stunde_19690101_20241231_02483.txt
Extracted: produkt_ff_stunde_20110502_20241231_02485.txt
Extracted: produkt_ff_stunde_19770301_19940531_02486.txt
Extracted: produkt_ff_stunde_19930101_20130930_02494.txt
Extracted: produkt_ff_stunde_19790101_20241231_02497.txt
Extracted: produkt_ff_stunde_19530101_20030505_02503.txt
Extracted: produkt_ff_stunde_19480101_20081031_02522.txt
Extracted: produkt_ff_stunde_19540101_20131031_02532.txt
Extracted: produkt_ff_stunde_19660101_20241231_02559.txt
Extracted: produkt_ff_stunde_19740101_20241231_02564.txt
Extracted: produkt_ff_stunde_19530101_19881015_02565.txt
Extracted: produkt_ff_stunde_19870610_20241231_02573.txt
Extracted: produkt_ff_stunde_19721201_20241231_02597.txt
Extracted: produkt_ff_stunde_19660101_20241231_02601.txt
Extracted: produkt_ff_stunde_19690101_20241231_02638.txt
Extracted: produkt_ff_stunde_19700701_19891231_02656.txt
Extracted: produkt_ff_stunde_19570701_20241231_02667.txt
Extracted: produkt_ff_stunde_19590701_20241231_02712.txt
Extracted: produkt_ff_stunde_19980101_19980201_02738.txt
Extracted: produkt_ff_stunde_19740101_20241231_02773.txt
Extracted: produkt_ff_stunde_19890101_20241231_02794.txt
Extracted: produkt_ff_stunde_19770127_20241231_02812.txt
Extracted: produkt_ff_stunde_19690101_20171222_02829.txt
Extracted: produkt_ff_stunde_19990501_20241231_02856.txt
Extracted: produkt_ff_stunde_20170801_20241231_02878.txt
Extracted: produkt_ff_stunde_19700101_20241231_02886.txt
Extracted: produkt_ff_stunde_19900830_20241231_02897.txt
Extracted: produkt_ff_stunde_19690101_20241231_02905.txt
Extracted: produkt_ff_stunde_19710101_19741031_02906.txt
Extracted: produkt_ff_stunde_19741201_20241231_02907.txt
Extracted: produkt_ff_stunde_19730101_20241231_02925.txt
Extracted: produkt_ff_stunde_19710101_19891231_02926.txt
Extracted: produkt_ff_stunde_19580101_20241231_02928.txt
Extracted: produkt_ff_stunde_19720501_20241231_02932.txt
Extracted: produkt_ff_stunde_20010401_20241231_02961.txt
Extracted: produkt_ff_stunde_19911101_20241231_02985.txt
Extracted: produkt_ff_stunde_19510101_20241231_03015.txt
Extracted: produkt_ff_stunde_19700201_20161231_03023.txt
Extracted: produkt_ff_stunde_19710401_20241231_03028.txt
Extracted: produkt_ff_stunde_19500101_20241231_03032.txt
Extracted: produkt_ff_stunde_19800201_19910331_03046.txt
Extracted: produkt_ff_stunde_19510101_19850228_03085.txt
Extracted: produkt_ff_stunde_19850301_20241231_03086.txt
Extracted: produkt_ff_stunde_19720101_20241231_03093.txt
Extracted: produkt_ff_stunde_19690101_19951231_03096.txt
Extracted: produkt_ff_stunde_19940101_20241231_03098.txt
Extracted: produkt_ff_stunde_19761201_19971231_03103.txt
Extracted: produkt_ff_stunde_19570801_20241231_03126.txt
Extracted: produkt_ff_stunde_19890101_20241231_03158.txt
Extracted: produkt_ff_stunde_19820101_20241231_03166.txt
Extracted: produkt_ff_stunde_19690101_20241231_03167.txt
Extracted: produkt_ff_stunde_19810101_20241231_03196.txt
Extracted: produkt_ff_stunde_19810101_19970331_03228.txt
Extracted: produkt_ff_stunde_19790101_20241231_03231.txt
Extracted: produkt_ff_stunde_20110513_20241231_03244.txt
Extracted: produkt_ff_stunde_19690101_20021129_03245.txt
Extracted: produkt_ff_stunde_19841101_20070531_03246.txt
Extracted: produkt_ff_stunde_19730101_20241231_03254.txt
Extracted: produkt_ff_stunde_19850101_19891031_03256.txt
Extracted: produkt_ff_stunde_20131008_20241231_03268.txt
Extracted: produkt_ff_stunde_19921201_19941130_03274.txt
Extracted: produkt_ff_stunde_19871001_20241231_03287.txt
Extracted: produkt_ff_stunde_19781201_19930531_03300.txt
Extracted: produkt_ff_stunde_20080425_20241231_03321.txt
Extracted: produkt_ff_stunde_20060701_20241231_03362.txt
Extracted: produkt_ff_stunde_19550101_20241231_03366.txt
Extracted: produkt_ff_stunde_19800101_20060315_03369.txt
Extracted: produkt_ff_stunde_19910101_20241231_03376.txt
Extracted: produkt_ff_stunde_19850101_20241231_03379.txt
Extracted: produkt_ff_stunde_19500301_19920517_03390.txt
Extracted: produkt_ff_stunde_20080124_20241231_03402.txt
Extracted: produkt_ff_stunde_19650101_19911231_03404.txt
Extracted: produkt_ff_stunde_19730101_19770531_03442.txt
Extracted: produkt_ff_stunde_19760701_20050816_03478.txt
Extracted: produkt_ff_stunde_19730101_20241231_03484.txt
Extracted: produkt_ff_stunde_19890501_20241231_03513.txt
Extracted: produkt_ff_stunde_19710101_19931231_03518.txt
Extracted: produkt_ff_stunde_19810301_20241231_03534.txt
Extracted: produkt_ff_stunde_19730101_20190408_03552.txt
Extracted: produkt_ff_stunde_19710101_19821231_03575.txt
Extracted: produkt_ff_stunde_19560101_19760630_03577.txt
Extracted: produkt_ff_stunde_19690101_20241231_03623.txt
Extracted: produkt_ff_stunde_19690101_20241231_03631.txt
Extracted: produkt_ff_stunde_19740101_20241231_03639.txt
Extracted: produkt_ff_stunde_19920402_20241231_03651.txt
Extracted: produkt_ff_stunde_19830601_20150831_03657.txt
Extracted: produkt_ff_stunde_19720101_19950327_03659.txt
Extracted: produkt_ff_stunde_19950301_20241231_03660.txt
Extracted: produkt_ff_stunde_19600101_19780331_03661.txt
Extracted: produkt_ff_stunde_19490101_20241231_03668.txt
Extracted: produkt_ff_stunde_19510101_20241231_03730.txt
Extracted: produkt_ff_stunde_19520101_20241231_03761.txt
Extracted: produkt_ff_stunde_19780101_19981216_03775.txt
Extracted: produkt_ff_stunde_19690101_20121001_03791.txt
Extracted: produkt_ff_stunde_19830101_20241231_03811.txt
Extracted: produkt_ff_stunde_19590820_20101130_03815.txt
Extracted: produkt_ff_stunde_19860101_20241231_03821.txt
Extracted: produkt_ff_stunde_19660101_19961231_03879.txt
Extracted: produkt_ff_stunde_20060818_20241231_03897.txt
Extracted: produkt_ff_stunde_19900829_20241231_03905.txt
Extracted: produkt_ff_stunde_19740601_19960430_03921.txt
Extracted: produkt_ff_stunde_19890406_20241231_03925.txt
Extracted: produkt_ff_stunde_19730101_20241231_03946.txt
Extracted: produkt_ff_stunde_19700701_19960930_03954.txt
Extracted: produkt_ff_stunde_18930101_20241231_03987.txt
Extracted: produkt_ff_stunde_18930101_20020831_03988.txt
Extracted: produkt_ff_stunde_19820101_20241231_04024.txt
Extracted: produkt_ff_stunde_20080521_20241231_04032.txt
Extracted: produkt_ff_stunde_20091012_20241231_04036.txt
Extracted: produkt_ff_stunde_19821201_20241231_04039.txt
Extracted: produkt_ff_stunde_19971209_20241231_04094.txt
Extracted: produkt_ff_stunde_19490101_20241231_04104.txt
Extracted: produkt_ff_stunde_19710101_20171219_04174.txt
Extracted: produkt_ff_stunde_20081101_20241231_04177.txt
Extracted: produkt_ff_stunde_19790601_20190412_04225.txt
Extracted: produkt_ff_stunde_19540101_20241231_04271.txt
Extracted: produkt_ff_stunde_19890418_20241231_04279.txt
Extracted: produkt_ff_stunde_19710101_20241231_04280.txt
Extracted: produkt_ff_stunde_19560101_20241231_04336.txt
Extracted: produkt_ff_stunde_19690101_20241231_04371.txt
Extracted: produkt_ff_stunde_19690101_20241231_04393.txt
Extracted: produkt_ff_stunde_19891001_19911031_04445.txt
Extracted: produkt_ff_stunde_19890801_20241231_04464.txt
Extracted: produkt_ff_stunde_19580201_20241231_04466.txt
Extracted: produkt_ff_stunde_19810101_20100501_04477.txt
Extracted: produkt_ff_stunde_19780701_20241231_04501.txt
Extracted: produkt_ff_stunde_19770701_19950831_04549.txt
Extracted: produkt_ff_stunde_19911126_20081226_04583.txt
Extracted: produkt_ff_stunde_19540101_20241231_04625.txt
Extracted: produkt_ff_stunde_19721001_19991130_04629.txt
Extracted: produkt_ff_stunde_19761001_20241231_04642.txt
Extracted: produkt_ff_stunde_19820201_20110412_04663.txt
Extracted: produkt_ff_stunde_19690101_19750531_04665.txt
Extracted: produkt_ff_stunde_19700101_19880729_04678.txt
Extracted: produkt_ff_stunde_19580601_20241231_04745.txt
Extracted: produkt_ff_stunde_19580101_20080701_04752.txt
Extracted: produkt_ff_stunde_19841201_20241231_04880.txt
Extracted: produkt_ff_stunde_19520101_20241231_04887.txt
Extracted: produkt_ff_stunde_19740101_20241231_04911.txt
Extracted: produkt_ff_stunde_19771001_20241231_04919.txt
Extracted: produkt_ff_stunde_19490801_19840731_04927.txt
Extracted: produkt_ff_stunde_19760901_20241231_04928.txt
Extracted: produkt_ff_stunde_19840901_19850531_04929.txt
Extracted: produkt_ff_stunde_19530101_20241231_04931.txt
Extracted: produkt_ff_stunde_19690101_19770630_04933.txt
Extracted: produkt_ff_stunde_19880817_20241231_04947.txt
Extracted: produkt_ff_stunde_19730101_20040630_05009.txt
Extracted: produkt_ff_stunde_19750601_20241231_05029.txt
Extracted: produkt_ff_stunde_19790101_20080501_05049.txt
Extracted: produkt_ff_stunde_19840101_19950531_05059.txt
Extracted: produkt_ff_stunde_19580101_19751031_05063.txt
Extracted: produkt_ff_stunde_19710101_20241231_05078.txt
Extracted: produkt_ff_stunde_19370101_20241231_05100.txt
Extracted: produkt_ff_stunde_20131001_20241231_05109.txt
Extracted: produkt_ff_stunde_19690101_19811031_05120.txt
Extracted: produkt_ff_stunde_19790601_19901130_05128.txt
Extracted: produkt_ff_stunde_19820101_20241231_05142.txt
Extracted: produkt_ff_stunde_19740101_19960930_05154.txt
Extracted: produkt_ff_stunde_19690101_20140901_05155.txt
Extracted: produkt_ff_stunde_19890101_20241231_05158.txt
Extracted: produkt_ff_stunde_19870611_20011117_05226.txt
Extracted: produkt_ff_stunde_19760501_19810531_05244.txt
Extracted: produkt_ff_stunde_19871208_19901231_05249.txt
Extracted: produkt_ff_stunde_19410101_19701231_05282.txt
Extracted: produkt_ff_stunde_19830101_20050930_05289.txt
Extracted: produkt_ff_stunde_19830101_20031210_05306.txt
Extracted: produkt_ff_stunde_19810801_20241231_05319.txt
Extracted: produkt_ff_stunde_19810714_20241231_05327.txt
Extracted: produkt_ff_stunde_20021201_20241231_05347.txt
Extracted: produkt_ff_stunde_19810101_20241231_05349.txt
Extracted: produkt_ff_stunde_19590101_20241231_05371.txt
Extracted: produkt_ff_stunde_19520101_20241231_05397.txt
Extracted: produkt_ff_stunde_19720101_20241231_05404.txt
Extracted: produkt_ff_stunde_19910531_20241231_05412.txt
Extracted: produkt_ff_stunde_19500101_20070630_05419.txt
Extracted: produkt_ff_stunde_19731201_20241231_05426.txt

# Extracting Wind Recent

In [10]:
#Extract Wind RECENT data files into extracted folder
import os
import zipfile
from pathlib import Path
# Folder containing all zip files
zip_folder = Path("Document_Corpus/dwd_wind/recent_zip")

# Output folder for extracted produkt files
output_folder = Path("Document_Corpus/dwd_wind/extracted")
output_folder.mkdir(parents=True, exist_ok=True)

print("ZIP folder:", zip_folder.resolve())
print("Output folder:", output_folder.resolve())



# Check how many ZIP files are available
zip_files = list(zip_folder.glob("*.zip"))
print(f"Total ZIP files found: {len(zip_files)}")

# Show first few zip names
for z in zip_files[:10]:
    print(z.name)

# Extract only files starting with produkt_st_stunde
extracted_files = []
errors = []

for zip_path in zip_files:
    try:
        with zipfile.ZipFile(zip_path, 'r') as z:
            matched = False
            
            for file_name in z.namelist():
                base_name = os.path.basename(file_name)
                
                if base_name.startswith("produkt_ff_stunde"):
                    
                    
                    matched = True
                    
                    # Add zip filename prefix to avoid overwriting files
                    #new_name = f"{zip_path.stem}_{base_name}"
                    new_name = f"{base_name}"
                    target_path = output_folder / new_name

                    with z.open(file_name) as source, open(target_path, "wb") as target:
                        target.write(source.read())

                    extracted_files.append(target_path.name)
                    print(f"Extracted: {target_path.name}")
            
            if not matched:
                print(f"No produkt_st_stunde file found in: {zip_path.name}")

    except Exception as e:
        errors.append((zip_path.name, str(e)))
        print(f"Error with {zip_path.name}: {e}")



# Summary
print("="*50)
print("EXTRACTION SUMMARY")
print("="*50)
print(f"ZIP files scanned: {len(zip_files)}")
print(f"Files extracted: {len(extracted_files)}")
print(f"Errors: {len(errors)}")

ZIP folder: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\dwd_wind\recent_zip
Output folder: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\dwd_wind\extracted
Total ZIP files found: 296
stundenwerte_FF_00011_akt.zip
stundenwerte_FF_00090_akt.zip
stundenwerte_FF_00096_akt.zip
stundenwerte_FF_00102_akt.zip
stundenwerte_FF_00125_akt.zip
stundenwerte_FF_00161_akt.zip
stundenwerte_FF_00164_akt.zip
stundenwerte_FF_00183_akt.zip
stundenwerte_FF_00197_akt.zip
stundenwerte_FF_00198_akt.zip
Extracted: produkt_ff_stunde_20241004_20260406_00011.txt
Extracted: produkt_ff_stunde_20241004_20260406_00090.txt
Extracted: produkt_ff_stunde_20241004_20260406_00096.txt
Extracted: produkt_ff_stunde_20241004_20260406_00102.txt
Extracted: produkt_ff_stunde_20241004_20260228_00125.txt
Extracted: produkt_ff_stunde_20241004_20260406_00161.txt
Extracted: produkt_ff_stunde_20241004_20260406_00164.txt
Extracted: produkt_ff_stunde_20241004_20260406_00183.txt
Extracted: produkt_ff_stunde_20241004_20260406_00197.txt
Extracted: produkt_ff_stunde_20241004_20260406_00198.txt
Extracted: produkt_ff_stunde_20241004_20260406_00232.txt
Extracted: produkt_ff_stunde_20241004_20260406_00282.txt
Extracted: produkt_ff_stunde_20241004_20260406_00298.txt
Extracted: produkt_ff_stunde_20241004_20260406_00303.txt
Extracted: produkt_ff_stunde_20241004_20260406_00342.txt
Extracted: produkt_ff_stunde_20241004_20260228_00368.txt
Extracted: produkt_ff_stunde_20241004_20260406_00427.txt
Extracted: produkt_ff_stunde_20241004_20260406_00433.txt
Extracted: produkt_ff_stunde_20241004_20260406_00460.txt
Extracted: produkt_ff_stunde_20241004_20260406_00591.txt
Extracted: produkt_ff_stunde_20241004_20260406_00596.txt
Extracted: produkt_ff_stunde_20241004_20260406_00603.txt
Extracted: produkt_ff_stunde_20241004_20260406_00619.txt
Extracted: produkt_ff_stunde_20241004_20260406_00642.txt
Extracted: produkt_ff_stunde_20241004_20260406_00656.txt
Extracted: produkt_ff_stunde_20241004_20260406_00662.txt
Extracted: produkt_ff_stunde_20241004_20260406_00691.txt
Extracted: produkt_ff_stunde_20241004_20260329_00701.txt
Extracted: produkt_ff_stunde_20241004_20260406_00704.txt
Extracted: produkt_ff_stunde_20241004_20260406_00722.txt
Extracted: produkt_ff_stunde_20241004_20260228_00766.txt
Extracted: produkt_ff_stunde_20241004_20260406_00788.txt
Extracted: produkt_ff_stunde_20241004_20260406_00840.txt
Extracted: produkt_ff_stunde_20241004_20260406_00853.txt
Extracted: produkt_ff_stunde_20241004_20260406_00856.txt
Extracted: produkt_ff_stunde_20241004_20260406_00867.txt
Extracted: produkt_ff_stunde_20241004_20260406_00880.txt
Extracted: produkt_ff_stunde_20241004_20260406_00891.txt
Extracted: produkt_ff_stunde_20241004_20260406_00953.txt
Extracted: produkt_ff_stunde_20241004_20260406_00954.txt
Extracted: produkt_ff_stunde_20241004_20260406_00963.txt
Extracted: produkt_ff_stunde_20241004_20260406_01001.txt
Extracted: produkt_ff_stunde_20241004_20260406_01011.txt
Extracted: produkt_ff_stunde_20241004_20260406_01013.txt
Extracted: produkt_ff_stunde_20241004_20260406_01048.txt
Extracted: produkt_ff_stunde_20241004_20260406_01078.txt
Extracted: produkt_ff_stunde_20241004_20260406_01200.txt
Extracted: produkt_ff_stunde_20241004_20250723_01228.txt
Extracted: produkt_ff_stunde_20241004_20260406_01262.txt
Extracted: produkt_ff_stunde_20241004_20260406_01270.txt
Extracted: produkt_ff_stunde_20241004_20260406_01303.txt
Extracted: produkt_ff_stunde_20241004_20260331_01339.txt
Extracted: produkt_ff_stunde_20241004_20260406_01346.txt
Extracted: produkt_ff_stunde_20241004_20260406_01357.txt
Extracted: produkt_ff_stunde_20241004_20260406_01358.txt
Extracted: produkt_ff_stunde_20241004_20260406_01379.txt
Extracted: produkt_ff_stunde_20241004_20260406_01420.txt
Extracted: produkt_ff_stunde_20241004_20260406_01443.txt
Extracted: produkt_ff_stunde_20241004_20260406_01468.txt
Extracted: produkt_ff_stunde_20241004_20260406_01490.txt
Extracted: produkt_ff_stunde_20241004_20260406_01503.txt
Extracted: produkt_ff_stunde_20241004_20260406_01544.txt
Extracted: produkt_ff_stunde_20241004_20260406_01550.txt
Extracted: produkt_ff_stunde_20241004_20260406_01580.txt
Extracted: produkt_ff_stunde_20241004_20260406_01587.txt
Extracted: produkt_ff_stunde_20241004_20260406_01605.txt
Extracted: produkt_ff_stunde_20241004_20260406_01612.txt
Extracted: produkt_ff_stunde_20241004_20260406_01639.txt
Extracted: produkt_ff_stunde_20241004_20260406_01684.txt
Extracted: produkt_ff_stunde_20241004_20260406_01691.txt
Extracted: produkt_ff_stunde_20241004_20260406_01694.txt
Extracted: produkt_ff_stunde_20241004_20260406_01757.txt
Extracted: produkt_ff_stunde_20241004_20260406_01759.txt
Extracted: produkt_ff_stunde_20241004_20260406_01766.txt
Extracted: produkt_ff_stunde_20241004_20260406_01803.txt
Extracted: produkt_ff_stunde_20241004_20260406_01832.txt
Extracted: produkt_ff_stunde_20241004_20260406_01869.txt
Extracted: produkt_ff_stunde_20241004_20260406_01886.txt
Extracted: produkt_ff_stunde_20241004_20260406_01963.txt
Extracted: produkt_ff_stunde_20241004_20260406_01975.txt
Extracted: produkt_ff_stunde_20241004_20260406_01993.txt
Extracted: produkt_ff_stunde_20241004_20260322_02014.txt
Extracted: produkt_ff_stunde_20241004_20260406_02023.txt
Extracted: produkt_ff_stunde_20241004_20260406_02044.txt
Extracted: produkt_ff_stunde_20241004_20260406_02115.txt
Extracted: produkt_ff_stunde_20241004_20260406_02171.txt
Extracted: produkt_ff_stunde_20241004_20260406_02252.txt
Extracted: produkt_ff_stunde_20241004_20260406_02261.txt
Extracted: produkt_ff_stunde_20241004_20260406_02290.txt
Extracted: produkt_ff_stunde_20241004_20260331_02303.txt
Extracted: produkt_ff_stunde_20241004_20260331_02315.txt
Extracted: produkt_ff_stunde_20241004_20260406_02349.txt
Extracted: produkt_ff_stunde_20241004_20260406_02377.txt
Extracted: produkt_ff_stunde_20241004_20260331_02385.txt
Extracted: produkt_ff_stunde_20241004_20260331_02410.txt
Extracted: produkt_ff_stunde_20241004_20260406_02429.txt
Extracted: produkt_ff_stunde_20241004_20260406_02483.txt
Extracted: produkt_ff_stunde_20241004_20260406_02485.txt
Extracted: produkt_ff_stunde_20241004_20260406_02497.txt
Extracted: produkt_ff_stunde_20241004_20260406_02559.txt
Extracted: produkt_ff_stunde_20241004_20260406_02564.txt
Extracted: produkt_ff_stunde_20241004_20260406_02573.txt
Extracted: produkt_ff_stunde_20241004_20260406_02597.txt
Extracted: produkt_ff_stunde_20241004_20260406_02601.txt
Extracted: produkt_ff_stunde_20241004_20260406_02638.txt
Extracted: produkt_ff_stunde_20241004_20260406_02667.txt
Extracted: produkt_ff_stunde_20241004_20260406_02712.txt
Extracted: produkt_ff_stunde_20241004_20260228_02773.txt
Extracted: produkt_ff_stunde_20241004_20260406_02794.txt
Extracted: produkt_ff_stunde_20241004_20260406_02812.txt
Extracted: produkt_ff_stunde_20241004_20260406_02856.txt
Extracted: produkt_ff_stunde_20241004_20260406_02878.txt
Extracted: produkt_ff_stunde_20241004_20260331_02886.txt
Extracted: produkt_ff_stunde_20241004_20260406_02897.txt
Extracted: produkt_ff_stunde_20241004_20260331_02905.txt
Extracted: produkt_ff_stunde_20241004_20260406_02907.txt
Extracted: produkt_ff_stunde_20241004_20260406_02925.txt
Extracted: produkt_ff_stunde_20241004_20260406_02928.txt
Extracted: produkt_ff_stunde_20241004_20260406_02932.txt
Extracted: produkt_ff_stunde_20241004_20260406_02961.txt
Extracted: produkt_ff_stunde_20241004_20260406_02985.txt
Extracted: produkt_ff_stunde_20241004_20260406_03015.txt
Extracted: produkt_ff_stunde_20241004_20260406_03028.txt
Extracted: produkt_ff_stunde_20241004_20260406_03032.txt
Extracted: produkt_ff_stunde_20241004_20260406_03086.txt
Extracted: produkt_ff_stunde_20241004_20260406_03093.txt
Extracted: produkt_ff_stunde_20241004_20260406_03098.txt
Extracted: produkt_ff_stunde_20241004_20260406_03126.txt
Extracted: produkt_ff_stunde_20241004_20260406_03158.txt
Extracted: produkt_ff_stunde_20241004_20260406_03166.txt
Extracted: produkt_ff_stunde_20241004_20260406_03167.txt
Extracted: produkt_ff_stunde_20241004_20260406_03196.txt
Extracted: produkt_ff_stunde_20241004_20260406_03231.txt
Extracted: produkt_ff_stunde_20241004_20260406_03244.txt
Extracted: produkt_ff_stunde_20241004_20260331_03254.txt
Extracted: produkt_ff_stunde_20241004_20260406_03268.txt
Extracted: produkt_ff_stunde_20241004_20260406_03287.txt
Extracted: produkt_ff_stunde_20241004_20260406_03321.txt
Extracted: produkt_ff_stunde_20241004_20260406_03362.txt
Extracted: produkt_ff_stunde_20241004_20260406_03366.txt
Extracted: produkt_ff_stunde_20241004_20260406_03376.txt
Extracted: produkt_ff_stunde_20241004_20260406_03379.txt
Extracted: produkt_ff_stunde_20241004_20260406_03402.txt
Extracted: produkt_ff_stunde_20241004_20260331_03484.txt
Extracted: produkt_ff_stunde_20241004_20260406_03513.txt
Extracted: produkt_ff_stunde_20241004_20260406_03534.txt
Extracted: produkt_ff_stunde_20241004_20260331_03623.txt
Extracted: produkt_ff_stunde_20241004_20260406_03631.txt
Extracted: produkt_ff_stunde_20241004_20260228_03639.txt
Extracted: produkt_ff_stunde_20241004_20260406_03651.txt
Extracted: produkt_ff_stunde_20241004_20260406_03660.txt
Extracted: produkt_ff_stunde_20241004_20260406_03668.txt
Extracted: produkt_ff_stunde_20241004_20260406_03730.txt
Extracted: produkt_ff_stunde_20241004_20260406_03761.txt
Extracted: produkt_ff_stunde_20241004_20260406_03811.txt
Extracted: produkt_ff_stunde_20241004_20260406_03821.txt
Extracted: produkt_ff_stunde_20241004_20260406_03897.txt
Extracted: produkt_ff_stunde_20241004_20260406_03905.txt
Extracted: produkt_ff_stunde_20241004_20260406_03925.txt
Extracted: produkt_ff_stunde_20241004_20260406_03946.txt
Extracted: produkt_ff_stunde_20241004_20260406_03987.txt
Extracted: produkt_ff_stunde_20241004_20260406_04024.txt
Extracted: produkt_ff_stunde_20241004_20260406_04032.txt
Extracted: produkt_ff_stunde_20241004_20260406_04036.txt
Extracted: produkt_ff_stunde_20241004_20260406_04039.txt
Extracted: produkt_ff_stunde_20241004_20260406_04094.txt
Extracted: produkt_ff_stunde_20241004_20260406_04104.txt
Extracted: produkt_ff_stunde_20241004_20260406_04177.txt
Extracted: produkt_ff_stunde_20241004_20260406_04271.txt
Extracted: produkt_ff_stunde_20241004_20260406_04279.txt
Extracted: produkt_ff_stunde_20241004_20260406_04280.txt
Extracted: produkt_ff_stunde_20241004_20260406_04336.txt
Extracted: produkt_ff_stunde_20241004_20260406_04371.txt
Extracted: produkt_ff_stunde_20241004_20260406_04393.txt
Extracted: produkt_ff_stunde_20241004_20260406_04464.txt
Extracted: produkt_ff_stunde_20241004_20260401_04466.txt
Extracted: produkt_ff_stunde_20241004_20260406_04501.txt
Extracted: produkt_ff_stunde_20241004_20260406_04625.txt
Extracted: produkt_ff_stunde_20241004_20260406_04642.txt
Extracted: produkt_ff_stunde_20241004_20260406_04745.txt
Extracted: produkt_ff_stunde_20241004_20260406_04880.txt
Extracted: produkt_ff_stunde_20241004_20260406_04887.txt
Extracted: produkt_ff_stunde_20241004_20260406_04911.txt
Extracted: produkt_ff_stunde_20241004_20260406_04919.txt
Extracted: produkt_ff_stunde_20241004_20260406_04928.txt
Extracted: produkt_ff_stunde_20241004_20260406_04931.txt
Extracted: produkt_ff_stunde_20241004_20260406_04947.txt
Extracted: produkt_ff_stunde_20241004_20260406_05029.txt
Extracted: produkt_ff_stunde_20241004_20260406_05078.txt
Extracted: produkt_ff_stunde_20241004_20260406_05100.txt
Extracted: produkt_ff_stunde_20241004_20260406_05109.txt
Extracted: produkt_ff_stunde_20241004_20260406_05142.txt
Extracted: produkt_ff_stunde_20241004_20260406_05158.txt
Extracted: produkt_ff_stunde_20241004_20260406_05319.txt
Extracted: produkt_ff_stunde_20241004_20260406_05327.txt
Extracted: produkt_ff_stunde_20241004_20260406_05347.txt
Extracted: produkt_ff_stunde_20241004_20260406_05349.txt
Extracted: produkt_ff_stunde_20241004_20260406_05371.txt
Extracted: produkt_ff_stunde_20241004_20260406_05397.txt
Extracted: produkt_ff_stunde_20241004_20260406_05404.txt
Extracted: produkt_ff_stunde_20241004_20260406_05412.txt
Extracted: produkt_ff_stunde_20241004_20260406_05426.txt
Extracted: produkt_ff_stunde_20241004_20260406_05440.txt
Extracted: produkt_ff_stunde_20241004_20260406_05480.txt
Extracted: produkt_ff_stunde_20241004_20260406_05490.txt
Extracted: produkt_ff_stunde_20241004_20260406_05516.txt
Extracted: produkt_ff_stunde_20241004_20260406_05538.txt
Extracted: produkt_ff_stunde_20241004_20260406_05546.txt
Extracted: produkt_ff_stunde_20241004_20260406_05629.txt
Extracted: produkt_ff_stunde_20241004_20260331_05640.txt
Extracted: produkt_ff_stunde_20241004_20260406_05705.txt
Extracted: produkt_ff_stunde_20241004_20260228_05715.txt
Extracted: produkt_ff_stunde_20241004_20260406_05779.txt
Extracted: produkt_ff_stunde_20241004_20260406_05792.txt
Extracted: produkt_ff_stunde_20241004_20260406_05797.txt
Extracted: produkt_ff_stunde_20241004_20260406_05800.txt
Extracted: produkt_ff_stunde_20241004_20260406_05825.txt
Extracted: produkt_ff_stunde_20241004_20241115_05839.txt
Extracted: produkt_ff_stunde_20241004_20260406_05851.txt
Extracted: produkt_ff_stunde_20241004_20260406_05856.txt
Extracted: produkt_ff_stunde_20241004_20260406_05871.txt
Extracted: produkt_ff_stunde_20241004_20260406_05877.txt
Extracted: produkt_ff_stunde_20241004_20260406_05906.txt
Extracted: produkt_ff_stunde_20241004_20260406_05930.txt
Extracted: produkt_ff_stunde_20241004_20260406_06091.txt
Extracted: produkt_ff_stunde_20241004_20260406_06096.txt
Extracted: produkt_ff_stunde_20241004_20260406_06097.txt
Extracted: produkt_ff_stunde_20241004_20260406_06099.txt
Extracted: produkt_ff_stunde_20241004_20260406_06101.txt
Extracted: produkt_ff_stunde_20241004_20260406_06102.txt
Extracted: produkt_ff_stunde_20241004_20260406_06103.txt
Extracted: produkt_ff_stunde_20241004_20260406_06106.txt
Extracted: produkt_ff_stunde_20241004_20260406_06107.txt
Extracted: produkt_ff_stunde_20241004_20260406_06108.txt
Extracted: produkt_ff_stunde_20241004_20260406_06159.txt
Extracted: produkt_ff_stunde_20241004_20260406_06163.txt
Extracted: produkt_ff_stunde_20241004_20260406_06196.txt
Extracted: produkt_ff_stunde_20241004_20260406_06197.txt
Extracted: produkt_ff_stunde_20241004_20260406_06211.txt
Extracted: produkt_ff_stunde_20241004_20260406_06253.txt
Extracted: produkt_ff_stunde_20241004_20260406_06314.txt
Extracted: produkt_ff_stunde_20241004_20260406_06344.txt
Extracted: produkt_ff_stunde_20241004_20260406_07341.txt
Extracted: produkt_ff_stunde_20241004_20260406_07351.txt
Extracted: produkt_ff_stunde_20241004_20260406_07367.txt
Extracted: produkt_ff_stunde_20241004_20260406_07368.txt
Extracted: produkt_ff_stunde_20241004_20260406_07369.txt
Extracted: produkt_ff_stunde_20241004_20260406_07370.txt
Extracted: produkt_ff_stunde_20241004_20260406_07374.txt
Extracted: produkt_ff_stunde_20241004_20260406_07389.txt
Extracted: produkt_ff_stunde_20241004_20260406_07391.txt
Extracted: produkt_ff_stunde_20241004_20260406_07392.txt
Extracted: produkt_ff_stunde_20241004_20260406_07393.txt
Extracted: produkt_ff_stunde_20241004_20260406_07394.txt
Extracted: produkt_ff_stunde_20241004_20260406_07395.txt
Extracted: produkt_ff_stunde_20241004_20260406_07396.txt
Extracted: produkt_ff_stunde_20241004_20260406_07403.txt
Extracted: produkt_ff_stunde_20241004_20260406_07410.txt
Extracted: produkt_ff_stunde_20241004_20260406_07412.txt
Extracted: produkt_ff_stunde_20241004_20260406_07416.txt
Extracted: produkt_ff_stunde_20241004_20260406_10510.txt
Extracted: produkt_ff_stunde_20241004_20260406_13674.txt
Extracted: produkt_ff_stunde_20241004_20260406_13676.txt
Extracted: produkt_ff_stunde_20241004_20260406_13693.txt
Extracted: produkt_ff_stunde_20241004_20260406_13701.txt
Extracted: produkt_ff_stunde_20241004_20260406_13711.txt
Extracted: produkt_ff_stunde_20241004_20260406_13900.txt
Extracted: produkt_ff_stunde_20241004_20260406_13901.txt
Extracted: produkt_ff_stunde_20241004_20260406_13932.txt
Extracted: produkt_ff_stunde_20241004_20260406_13952.txt
Extracted: produkt_ff_stunde_20241004_20260406_13965.txt
Extracted: produkt_ff_stunde_20241004_20260406_14138.txt
Extracted: produkt_ff_stunde_20241004_20260406_15000.txt
Extracted: produkt_ff_stunde_20241004_20260406_15044.txt
Extracted: produkt_ff_stunde_20241004_20260406_15120.txt
Extracted: produkt_ff_stunde_20241004_20260406_15122.txt
Extracted: produkt_ff_stunde_20241004_20260406_15189.txt
Extracted: produkt_ff_stunde_20241004_20260406_15190.txt
Extracted: produkt_ff_stunde_20241004_20260406_15194.txt
Extracted: produkt_ff_stunde_20241004_20260406_15200.txt
Extracted: produkt_ff_stunde_20241004_20260406_15207.txt
Extracted: produkt_ff_stunde_20241004_20260406_15214.txt
Extracted: produkt_ff_stunde_20241004_20260406_15444.txt
Extracted: produkt_ff_stunde_20241004_20260406_15520.txt
Extracted: produkt_ff_stunde_20241004_20260406_15547.txt
Extracted: produkt_ff_stunde_20241004_20260406_15555.txt
Extracted: produkt_ff_stunde_20241004_20260406_15801.txt
Extracted: produkt_ff_stunde_20241004_20260406_15813.txt
Extracted: produkt_ff_stunde_20241004_20260406_15911.txt
Extracted: produkt_ff_stunde_20241004_20260406_15976.txt
Extracted: produkt_ff_stunde_20241004_20260406_15978.txt
Extracted: produkt_ff_stunde_20241004_20260406_19171.txt
Extracted: produkt_ff_stunde_20241004_20260406_19207.txt
Extracted: produkt_ff_stunde_20241004_20260406_19243.txt
Extracted: produkt_ff_stunde_20230908_20230908_19576.txt
Extracted: produkt_ff_stunde_20241004_20260406_19856.txt
==================================================
EXTRACTION SUMMARY
==================================================
ZIP files scanned: 296
Files extracted: 296
Errors: 0

# Merging all solar text files as csv

In [12]:
# Merging all solar text files as csv
import pandas as pd
from pathlib import Path
# Folder containing extracted DWD text files
input_folder = Path("Document_Corpus/dwd_solar/extracted")

# Find all .txt files
txt_files = list(input_folder.glob("*.txt"))

print(f"Total TXT files found: {len(txt_files)}")

# Preview first few files
for f in txt_files[:5]:
    print(f.name)

all_data = []
errors = []

for file_path in txt_files:
    try:
        print(f"Reading: {file_path.name}")
        
        # Read semicolon-separated DWD file
        df = pd.read_csv(
            file_path,
            sep=';',
            comment='#',      # ignore metadata lines if any
            engine='python'
        )
        
        # Optional: add source file name for traceability
        # df["source_file"] = file_path.name
        
        all_data.append(df)
        
    except Exception as e:
        errors.append((file_path.name, str(e)))
        print(f"Error reading {file_path.name}: {e}")




merged_df = pd.concat(all_data, ignore_index=True)
# Remove extra spaces from column names
merged_df.columns = merged_df.columns.str.strip()

print(merged_df.columns.tolist())

print("Merged shape:", merged_df.shape)



# Replace common DWD missing values
merged_df.replace(-999, pd.NA, inplace=True)
merged_df.replace(-999.0, pd.NA, inplace=True)




output_file = Path("Document_Corpus/dwd_solar/final_merged_dwd_solar.csv")

merged_df.to_csv(output_file, index=False)

print(f"Final merged CSV saved at: {output_file.resolve()}")



print("="*50)
print("MERGE SUMMARY")
print("="*50)
print(f"TXT files processed: {len(txt_files)}")
print(f"Rows in final dataset: {len(merged_df)}")
print(f"Columns in final dataset: {len(merged_df.columns)}")
print(f"Errors: {len(errors)}")
merged_df.sample(10)

Total TXT files found: 54
produkt_st_stunde_19451231_20260228_03987.txt
produkt_st_stunde_19490101_20070430_05419.txt
produkt_st_stunde_19500101_19960831_05282.txt
produkt_st_stunde_19530101_20260228_02290.txt
produkt_st_stunde_19570101_20000731_00656.txt
Reading: produkt_st_stunde_19451231_20260228_03987.txt
Reading: produkt_st_stunde_19490101_20070430_05419.txt
Reading: produkt_st_stunde_19500101_19960831_05282.txt
Reading: produkt_st_stunde_19530101_20260228_02290.txt
Reading: produkt_st_stunde_19570101_20000731_00656.txt
Reading: produkt_st_stunde_19570101_20260228_05705.txt
Reading: produkt_st_stunde_19580101_20260228_00662.txt
Reading: produkt_st_stunde_19580101_20260228_01358.txt
Reading: produkt_st_stunde_19580101_20260228_05100.txt
Reading: produkt_st_stunde_19610101_20260228_05404.txt
Reading: produkt_st_stunde_19640101_20260228_03631.txt
Reading: produkt_st_stunde_19720101_20150131_03032.txt
Reading: produkt_st_stunde_19730101_20150131_01443.txt
Reading: produkt_st_stunde_19740101_19901231_01594.txt
Reading: produkt_st_stunde_19760101_20131231_01580.txt
Reading: produkt_st_stunde_19770101_20011231_03815.txt
Reading: produkt_st_stunde_19770101_20260228_02712.txt
Reading: produkt_st_stunde_19790101_20021231_02532.txt
Reading: produkt_st_stunde_19790101_20260228_04928.txt
Reading: produkt_st_stunde_19790101_20260228_05906.txt
Reading: produkt_st_stunde_19800101_20260228_04466.txt
Reading: produkt_st_stunde_19810101_20140930_05440.txt
Reading: produkt_st_stunde_19810101_20150131_01957.txt
Reading: produkt_st_stunde_19810101_20260228_00183.txt
Reading: produkt_st_stunde_19810101_20260228_00853.txt
Reading: produkt_st_stunde_19810101_20260228_03015.txt
Reading: produkt_st_stunde_19810101_20260228_04336.txt
Reading: produkt_st_stunde_19810101_20260228_05779.txt
Reading: produkt_st_stunde_19820101_20110831_03028.txt
Reading: produkt_st_stunde_19910101_20031231_03478.txt
Reading: produkt_st_stunde_19910101_20260228_04642.txt
Reading: produkt_st_stunde_19960901_20260228_01048.txt
Reading: produkt_st_stunde_19970102_20260228_05856.txt
Reading: produkt_st_stunde_19980101_20260228_04271.txt
Reading: produkt_st_stunde_20010101_20260228_01684.txt
Reading: produkt_st_stunde_20050101_20260228_01975.txt
Reading: produkt_st_stunde_20060101_20130731_03098.txt
Reading: produkt_st_stunde_20061001_20190531_02928.txt
Reading: produkt_st_stunde_20080701_20260228_04393.txt
Reading: produkt_st_stunde_20090101_20260228_00691.txt
Reading: produkt_st_stunde_20090101_20260228_03668.txt
Reading: produkt_st_stunde_20090101_20260228_07365.txt
Reading: produkt_st_stunde_20130101_20260228_05792.txt
Reading: produkt_st_stunde_20190501_20230930_02932.txt
Reading: produkt_st_stunde_20210101_20260228_00867.txt
Reading: produkt_st_stunde_20210101_20260228_02925.txt
Reading: produkt_st_stunde_20210101_20260228_07370.txt
Reading: produkt_st_stunde_20220101_20260228_05142.txt
Reading: produkt_st_stunde_20220101_20260228_06197.txt
Reading: produkt_st_stunde_20230101_20260228_01346.txt
Reading: produkt_st_stunde_20230101_20260228_15000.txt
Reading: produkt_st_stunde_20230831_20241231_01303.txt
Reading: produkt_st_stunde_20240101_20260228_01639.txt
Reading: produkt_st_stunde_20250101_20260228_02483.txt
['STATIONS_ID', 'MESS_DATUM', 'QN_592', 'ATMO_LBERG', 'FD_LBERG', 'FG_LBERG', 'SD_LBERG', 'ZENIT', 'MESS_DATUM_WOZ', 'eor']
Merged shape: (14775051, 10)
Final merged CSV saved at: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\dwd_solar\final_merged_dwd_solar.csv
==================================================
MERGE SUMMARY
==================================================
TXT files processed: 54
Rows in final dataset: 14775051
Columns in final dataset: 10
Errors: 0

,STATIONS_ID,MESS_DATUM,QN_592,ATMO_LBERG,FD_LBERG,FG_LBERG,SD_LBERG,ZENIT,MESS_DATUM_WOZ,eor
10092574,183,1997093007:56,1,<NA>,<NA>,<NA>,<NA>,71.89,1997093009:00,eor
3143821,5705,2013102817:03,1,<NA>,0.0,0.0,0,95.39,2013102818:00,eor
2876140,5705,1983041608:20,1,<NA>,72.0,159.0,60,58.72,1983041609:00,eor
3223643,5705,2022120615:11,1,<NA>,3.0,3.0,0,85.95,2022120616:00,eor
14530598,2925,2022092911:09,1,109.0,62.0,68.0,1,54.26,2022092912:00,eor
7518066,3815,1995051302:24,1,<NA>,0.0,0.0,0,102.35,1995051303:00,eor
1722487,2290,1964060411:14,1,<NA>,65.0,329.0,60,26.04,1964060412:00,eor
5973162,3631,2006041500:31,1,<NA>,0.0,0.0,0,116.33,2006041501:00,eor
2138417,2290,2011111521:00,1,110.0,0.0,0.0,0,137.81,2011111522:00,eor
4214434,1358,1999082116:11,1,<NA>,51.0,124.0,42,66.41,1999082117:00,eor

# Merging all Temperature text files as csv

In [13]:
import pandas as pd
from pathlib import Path
# Folder containing extracted DWD text files
input_folder = Path("Document_Corpus/dwd_temp/extracted")

# Find all .txt files
txt_files = list(input_folder.glob("*.txt"))

print(f"Total TXT files found: {len(txt_files)}")

# Preview first few files
for f in txt_files[:5]:
    print(f.name)

all_data = []
errors = []

for file_path in txt_files:
    try:
        print(f"Reading: {file_path.name}")
        
        # Read semicolon-separated DWD file
        df = pd.read_csv(
            file_path,
            sep=';',
            comment='#',      # ignore metadata lines if any
            engine='python'
        )
        
        # Optional: add source file name for traceability
        # df["source_file"] = file_path.name
        
        all_data.append(df)
        
    except Exception as e:
        errors.append((file_path.name, str(e)))
        print(f"Error reading {file_path.name}: {e}")




merged_df = pd.concat(all_data, ignore_index=True)
# Remove extra spaces from column names
merged_df.columns = merged_df.columns.str.strip()

print(merged_df.columns.tolist())

print("Merged shape:", merged_df.shape)



# Replace common DWD missing values
# merged_df.replace(-999, pd.NA, inplace=True)
# merged_df.replace(-999.0, pd.NA, inplace=True)




output_file = Path("Document_Corpus/dwd_temp/final_merged_dwd_temp.csv")

merged_df.to_csv(output_file, index=False)

print(f"Final merged CSV saved at: {output_file.resolve()}")



print("="*50)
print("MERGE SUMMARY")
print("="*50)
print(f"TXT files processed: {len(txt_files)}")
print(f"Rows in final dataset: {len(merged_df)}")
print(f"Columns in final dataset: {len(merged_df.columns)}")
print(f"Errors: {len(errors)}")
merged_df.sample(10)

Total TXT files found: 1139
produkt_tu_stunde_18930101_20241231_03987.txt
produkt_tu_stunde_19410101_19710101_05282.txt
produkt_tu_stunde_19410101_20241231_05100.txt
produkt_tu_stunde_19460101_20241231_01580.txt
produkt_tu_stunde_19470101_19550101_00284.txt
Reading: produkt_tu_stunde_18930101_20241231_03987.txt
Reading: produkt_tu_stunde_19410101_19710101_05282.txt
Reading: produkt_tu_stunde_19410101_20241231_05100.txt
Reading: produkt_tu_stunde_19460101_20241231_01580.txt
Reading: produkt_tu_stunde_19470101_19550101_00284.txt
Reading: produkt_tu_stunde_19470101_20241231_00867.txt
Reading: produkt_tu_stunde_19470101_20241231_02290.txt
Reading: produkt_tu_stunde_19470101_20241231_04271.txt
Reading: produkt_tu_stunde_19480101_19540101_03382.txt
Reading: produkt_tu_stunde_19480101_19550101_02081.txt
Reading: produkt_tu_stunde_19480101_19620101_01425.txt
Reading: produkt_tu_stunde_19480101_19760101_00361.txt
Reading: produkt_tu_stunde_19480101_19821101_01833.txt
Reading: produkt_tu_stunde_19480101_19891001_03404.txt
Reading: produkt_tu_stunde_19480101_19970101_03879.txt
Reading: produkt_tu_stunde_19480101_20031001_05802.txt
Reading: produkt_tu_stunde_19480101_20081031_02522.txt
Reading: produkt_tu_stunde_19480101_20131031_02532.txt
Reading: produkt_tu_stunde_19480101_20140901_05155.txt
Reading: produkt_tu_stunde_19480101_20241231_00656.txt
Reading: produkt_tu_stunde_19480101_20241231_01197.txt
Reading: produkt_tu_stunde_19480101_20241231_01550.txt
Reading: produkt_tu_stunde_19480101_20241231_01691.txt
Reading: produkt_tu_stunde_19480101_20241231_02261.txt
Reading: produkt_tu_stunde_19480101_20241231_02597.txt
Reading: produkt_tu_stunde_19480101_20241231_02601.txt
Reading: produkt_tu_stunde_19480101_20241231_03730.txt
Reading: produkt_tu_stunde_19480101_20241231_04104.txt
Reading: produkt_tu_stunde_19480101_20241231_04887.txt
Reading: produkt_tu_stunde_19480101_20241231_05371.txt
Reading: produkt_tu_stunde_19480101_20241231_05705.txt
Reading: produkt_tu_stunde_19480101_20241231_05906.txt
Reading: produkt_tu_stunde_19490101_19570101_00598.txt
Reading: produkt_tu_stunde_19490101_19710101_01221.txt
Reading: produkt_tu_stunde_19490101_19740701_02374.txt
Reading: produkt_tu_stunde_19490101_19881015_02565.txt
Reading: produkt_tu_stunde_19490101_19920517_03390.txt
Reading: produkt_tu_stunde_19490101_20241231_00691.txt
Reading: produkt_tu_stunde_19490101_20241231_00701.txt
Reading: produkt_tu_stunde_19490101_20241231_01975.txt
Reading: produkt_tu_stunde_19490101_20241231_02014.txt
Reading: produkt_tu_stunde_19490101_20241231_03032.txt
Reading: produkt_tu_stunde_19490101_20241231_03631.txt
Reading: produkt_tu_stunde_19500101_20241231_01639.txt
Reading: produkt_tu_stunde_19500101_20241231_04371.txt
Reading: produkt_tu_stunde_19500101_20241231_04625.txt
Reading: produkt_tu_stunde_19500101_20241231_05792.txt
Reading: produkt_tu_stunde_19500401_20110331_00003.txt
Reading: produkt_tu_stunde_19510101_19541201_05832.txt
Reading: produkt_tu_stunde_19510101_19710101_01583.txt
Reading: produkt_tu_stunde_19510101_19710101_05732.txt
Reading: produkt_tu_stunde_19510101_19740901_00553.txt
Reading: produkt_tu_stunde_19510101_19760101_04933.txt
Reading: produkt_tu_stunde_19510101_19760701_03577.txt
Reading: produkt_tu_stunde_19510101_19780101_01758.txt
Reading: produkt_tu_stunde_19510101_19780701_01834.txt
Reading: produkt_tu_stunde_19510101_19850301_03085.txt
Reading: produkt_tu_stunde_19510101_19950327_03659.txt
Reading: produkt_tu_stunde_19510101_20030505_02503.txt
Reading: produkt_tu_stunde_19510101_20070630_05419.txt
Reading: produkt_tu_stunde_19510101_20080701_04752.txt
Reading: produkt_tu_stunde_19510101_20101130_03815.txt
Reading: produkt_tu_stunde_19510101_20161231_03023.txt
Reading: produkt_tu_stunde_19510101_20241231_00433.txt
Reading: produkt_tu_stunde_19510101_20241231_00662.txt
Reading: produkt_tu_stunde_19510101_20241231_00722.txt
Reading: produkt_tu_stunde_19510101_20241231_00853.txt
Reading: produkt_tu_stunde_19510101_20241231_00891.txt
Reading: produkt_tu_stunde_19510101_20241231_01270.txt
Reading: produkt_tu_stunde_19510101_20241231_01303.txt
Reading: produkt_tu_stunde_19510101_20241231_01358.txt
Reading: produkt_tu_stunde_19510101_20241231_01443.txt
Reading: produkt_tu_stunde_19510101_20241231_01468.txt
Reading: produkt_tu_stunde_19510101_20241231_01544.txt
Reading: produkt_tu_stunde_19510101_20241231_01684.txt
Reading: produkt_tu_stunde_19510101_20241231_02171.txt
Reading: produkt_tu_stunde_19510101_20241231_02483.txt
Reading: produkt_tu_stunde_19510101_20241231_02928.txt
Reading: produkt_tu_stunde_19510101_20241231_03015.txt
Reading: produkt_tu_stunde_19510101_20241231_03668.txt
Reading: produkt_tu_stunde_19510101_20241231_03946.txt
Reading: produkt_tu_stunde_19510101_20241231_04466.txt
Reading: produkt_tu_stunde_19510101_20241231_05142.txt
Reading: produkt_tu_stunde_19510101_20241231_05397.txt
Reading: produkt_tu_stunde_19510101_20241231_05490.txt
Reading: produkt_tu_stunde_19510101_20241231_05629.txt
Reading: produkt_tu_stunde_19520101_19720101_04373.txt
Reading: produkt_tu_stunde_19520101_20241231_01346.txt
Reading: produkt_tu_stunde_19520501_20241231_02115.txt
Reading: produkt_tu_stunde_19530101_19710101_05068.txt
Reading: produkt_tu_stunde_19530101_20150323_01957.txt
Reading: produkt_tu_stunde_19540101_19830101_03575.txt
Reading: produkt_tu_stunde_19540101_20241231_05426.txt
Reading: produkt_tu_stunde_19541201_20241231_03093.txt
Reading: produkt_tu_stunde_19550101_19751231_00175.txt
Reading: produkt_tu_stunde_19550101_19900101_02656.txt
Reading: produkt_tu_stunde_19550101_20241231_00232.txt
Reading: produkt_tu_stunde_19550101_20241231_00953.txt
Reading: produkt_tu_stunde_19550101_20241231_02559.txt
Reading: produkt_tu_stunde_19550101_20241231_03126.txt
Reading: produkt_tu_stunde_19550101_20241231_03366.txt
Reading: produkt_tu_stunde_19550101_20241231_03761.txt
Reading: produkt_tu_stunde_19550101_20241231_05440.txt
Reading: produkt_tu_stunde_19560101_19710101_04339.txt
Reading: produkt_tu_stunde_19560101_20241231_00164.txt
Reading: produkt_tu_stunde_19560101_20241231_00880.txt
Reading: produkt_tu_stunde_19560101_20241231_02925.txt
Reading: produkt_tu_stunde_19560701_20120921_05467.txt
Reading: produkt_tu_stunde_19580101_19720101_00919.txt
Reading: produkt_tu_stunde_19600101_19710101_01960.txt
Reading: produkt_tu_stunde_19600101_20241231_02667.txt
Reading: produkt_tu_stunde_19610101_19810101_00424.txt
Reading: produkt_tu_stunde_19610101_19850101_01426.txt
Reading: produkt_tu_stunde_19610101_20241231_00198.txt
Reading: produkt_tu_stunde_19610101_20241231_00282.txt
Reading: produkt_tu_stunde_19610101_20241231_00460.txt
Reading: produkt_tu_stunde_19610102_20241231_02410.txt
Reading: produkt_tu_stunde_19610103_19920629_14003.txt
Reading: produkt_tu_stunde_19620101_19840901_01421.txt
Reading: produkt_tu_stunde_19620501_20241231_04336.txt
Reading: produkt_tu_stunde_19621201_20241231_03167.txt
Reading: produkt_tu_stunde_19650101_19770801_01490.txt
Reading: produkt_tu_stunde_19650701_20241231_02638.txt
Reading: produkt_tu_stunde_19660101_20180710_02829.txt
Reading: produkt_tu_stunde_19660101_20241231_04745.txt
Reading: produkt_tu_stunde_19680401_19700401_04584.txt
Reading: produkt_tu_stunde_19690101_19750514_04665.txt
Reading: produkt_tu_stunde_19691201_20110801_00399.txt
Reading: produkt_tu_stunde_19710101_19981102_01219.txt
Reading: produkt_tu_stunde_19710101_20241231_02712.txt
Reading: produkt_tu_stunde_19710101_20241231_05779.txt
Reading: produkt_tu_stunde_19710104_20241231_00125.txt
Reading: produkt_tu_stunde_19710401_20241231_03028.txt
Reading: produkt_tu_stunde_19720501_20241231_02932.txt
Reading: produkt_tu_stunde_19730101_19761001_05431.txt
Reading: produkt_tu_stunde_19730101_19890101_00876.txt
Reading: produkt_tu_stunde_19730101_20190408_03552.txt
Reading: produkt_tu_stunde_19730101_20241231_00183.txt
Reading: produkt_tu_stunde_19730101_20241231_00427.txt
Reading: produkt_tu_stunde_19730101_20241231_00591.txt
Reading: produkt_tu_stunde_19730101_20241231_00596.txt
Reading: produkt_tu_stunde_19730101_20241231_01048.txt
Reading: produkt_tu_stunde_19730101_20241231_01612.txt
Reading: produkt_tu_stunde_19730101_20241231_05009.txt
Reading: produkt_tu_stunde_19740901_20060228_00554.txt
Reading: produkt_tu_stunde_19750101_20241231_05404.txt
Reading: produkt_tu_stunde_19750515_20241231_05029.txt
Reading: produkt_tu_stunde_19750601_19780601_00474.txt
Reading: produkt_tu_stunde_19750601_19780601_02761.txt
Reading: produkt_tu_stunde_19750601_19780601_03605.txt
Reading: produkt_tu_stunde_19750601_19960701_07135.txt
Reading: produkt_tu_stunde_19750601_20160402_02542.txt
Reading: produkt_tu_stunde_19750601_20241231_02814.txt
Reading: produkt_tu_stunde_19750601_20241231_03244.txt
Reading: produkt_tu_stunde_19760101_19780601_00982.txt
Reading: produkt_tu_stunde_19760101_19840801_04927.txt
Reading: produkt_tu_stunde_19760101_19880101_00052.txt
Reading: produkt_tu_stunde_19760301_20241231_01078.txt
Reading: produkt_tu_stunde_19760701_20050818_03478.txt
Reading: produkt_tu_stunde_19761001_20241231_04642.txt
Reading: produkt_tu_stunde_19770701_20241231_04928.txt
Reading: produkt_tu_stunde_19780101_20241231_01757.txt
Reading: produkt_tu_stunde_19780701_20241231_04501.txt
Reading: produkt_tu_stunde_19790101_19810401_03671.txt
Reading: produkt_tu_stunde_19790101_20241231_03231.txt
Reading: produkt_tu_stunde_19790401_20130514_04926.txt
Reading: produkt_tu_stunde_19810101_20040930_07244.txt
Reading: produkt_tu_stunde_19810101_20241231_00298.txt
Reading: produkt_tu_stunde_19810101_20241231_01001.txt
Reading: produkt_tu_stunde_19810101_20241231_01420.txt
Reading: produkt_tu_stunde_19810101_20241231_01694.txt
Reading: produkt_tu_stunde_19810101_20241231_01869.txt
Reading: produkt_tu_stunde_19810101_20241231_02044.txt
Reading: produkt_tu_stunde_19810101_20241231_03196.txt
Reading: produkt_tu_stunde_19810101_20241231_05349.txt
Reading: produkt_tu_stunde_19810101_20241231_05745.txt
Reading: produkt_tu_stunde_19820101_19830901_04018.txt
Reading: produkt_tu_stunde_19820101_19841101_02920.txt
Reading: produkt_tu_stunde_19820101_19910502_02166.txt
Reading: produkt_tu_stunde_19820101_19940401_02521.txt
Reading: produkt_tu_stunde_19820101_19960101_05663.txt
Reading: produkt_tu_stunde_19820101_19970101_04294.txt
Reading: produkt_tu_stunde_19820101_19990331_03385.txt
Reading: produkt_tu_stunde_19820101_20021001_02488.txt
Reading: produkt_tu_stunde_19820101_20241231_00142.txt
Reading: produkt_tu_stunde_19820101_20241231_00222.txt
Reading: produkt_tu_stunde_19820101_20241231_01605.txt
Reading: produkt_tu_stunde_19820101_20241231_03166.txt
Reading: produkt_tu_stunde_19820101_20241231_04024.txt
Reading: produkt_tu_stunde_19820701_20241231_03811.txt
Reading: produkt_tu_stunde_19821101_20241231_01832.txt
Reading: produkt_tu_stunde_19831101_20050101_03139.txt
Reading: produkt_tu_stunde_19840101_19971201_00599.txt
Reading: produkt_tu_stunde_19840801_20241231_03821.txt
Reading: produkt_tu_stunde_19850101_20241231_03147.txt
Reading: produkt_tu_stunde_19850301_20241231_03086.txt
Reading: produkt_tu_stunde_19860101_20210505_00430.txt
Reading: produkt_tu_stunde_19860701_20241231_05546.txt
Reading: produkt_tu_stunde_19861101_20241231_01279.txt
Reading: produkt_tu_stunde_19871001_20241231_03287.txt
Reading: produkt_tu_stunde_19880101_20241231_04931.txt
Reading: produkt_tu_stunde_19880111_20241231_04039.txt
Reading: produkt_tu_stunde_19890101_20241231_02794.txt
Reading: produkt_tu_stunde_19890101_20241231_03158.txt
Reading: produkt_tu_stunde_19890101_20241231_05158.txt
Reading: produkt_tu_stunde_19890501_20241231_03513.txt
Reading: produkt_tu_stunde_19890801_20241231_04464.txt
Reading: produkt_tu_stunde_19891001_20241231_01766.txt
Reading: produkt_tu_stunde_19891001_20241231_04445.txt
Reading: produkt_tu_stunde_19891215_20110901_00348.txt
Reading: produkt_tu_stunde_19900101_20100501_05665.txt
Reading: produkt_tu_stunde_19910101_20121001_03791.txt
Reading: produkt_tu_stunde_19910101_20241231_00400.txt
Reading: produkt_tu_stunde_19910101_20241231_00704.txt
Reading: produkt_tu_stunde_19910101_20241231_00840.txt
Reading: produkt_tu_stunde_19910101_20241231_00856.txt
Reading: produkt_tu_stunde_19910101_20241231_01587.txt
Reading: produkt_tu_stunde_19910101_20241231_01803.txt
Reading: produkt_tu_stunde_19910101_20241231_02907.txt
Reading: produkt_tu_stunde_19910101_20241231_03376.txt
Reading: produkt_tu_stunde_19910101_20241231_05930.txt
Reading: produkt_tu_stunde_19910305_20241231_02985.txt
Reading: produkt_tu_stunde_19910801_20241231_02444.txt
Reading: produkt_tu_stunde_19920517_20241231_01262.txt
Reading: produkt_tu_stunde_19921001_19941001_03274.txt
Reading: produkt_tu_stunde_19930401_19991201_04629.txt
Reading: produkt_tu_stunde_19930819_20241231_00303.txt
Reading: produkt_tu_stunde_19940101_20241231_03098.txt
Reading: produkt_tu_stunde_19940103_20241231_00963.txt
Reading: produkt_tu_stunde_19940401_19941101_02691.txt
Reading: produkt_tu_stunde_19940501_20241231_04911.txt
Reading: produkt_tu_stunde_19950101_20241231_02812.txt
Reading: produkt_tu_stunde_19950302_20241231_03660.txt
Reading: produkt_tu_stunde_19960531_20241231_05516.txt
Reading: produkt_tu_stunde_19970103_20241231_05856.txt
Reading: produkt_tu_stunde_19970701_20241231_03379.txt
Reading: produkt_tu_stunde_19970701_20241231_05839.txt
Reading: produkt_tu_stunde_19970701_20241231_05871.txt
Reading: produkt_tu_stunde_19980101_19980201_02738.txt
Reading: produkt_tu_stunde_19981106_20080501_05049.txt
Reading: produkt_tu_stunde_19990928_20081103_00181.txt
Reading: produkt_tu_stunde_19991201_20241231_04393.txt
Reading: produkt_tu_stunde_20000401_20120327_06182.txt
Reading: produkt_tu_stunde_20000501_20241231_00954.txt
Reading: produkt_tu_stunde_20001025_20241231_01759.txt
Reading: produkt_tu_stunde_20010401_20241231_06163.txt
Reading: produkt_tu_stunde_20010402_20241231_05347.txt
Reading: produkt_tu_stunde_20010403_20241231_00603.txt
Reading: produkt_tu_stunde_20011017_20050826_02456.txt
Reading: produkt_tu_stunde_20020101_20030611_00879.txt
Reading: produkt_tu_stunde_20020101_20050422_01130.txt
Reading: produkt_tu_stunde_20020101_20051223_02338.txt
Reading: produkt_tu_stunde_20020101_20061031_00685.txt
Reading: produkt_tu_stunde_20020101_20070613_03246.txt
Reading: produkt_tu_stunde_20020101_20070828_04719.txt
Reading: produkt_tu_stunde_20020101_20090630_05277.txt
Reading: produkt_tu_stunde_20020101_20121221_03170.txt
Reading: produkt_tu_stunde_20020101_20131020_02494.txt
Reading: produkt_tu_stunde_20020101_20171220_04174.txt
Reading: produkt_tu_stunde_20020101_20241231_00102.txt
Reading: produkt_tu_stunde_20020101_20241231_00368.txt
Reading: produkt_tu_stunde_20020101_20241231_00403.txt
Reading: produkt_tu_stunde_20020101_20241231_00766.txt
Reading: produkt_tu_stunde_20020101_20241231_00769.txt
Reading: produkt_tu_stunde_20020101_20241231_00850.txt
Reading: produkt_tu_stunde_20020101_20241231_01200.txt
Reading: produkt_tu_stunde_20020101_20241231_01228.txt
Reading: produkt_tu_stunde_20020101_20241231_01339.txt
Reading: produkt_tu_stunde_20020101_20241231_01504.txt
Reading: produkt_tu_stunde_20020101_20241231_01572.txt
Reading: produkt_tu_stunde_20020101_20241231_01666.txt
Reading: produkt_tu_stunde_20020101_20241231_02023.txt
Reading: produkt_tu_stunde_20020101_20241231_02303.txt
Reading: produkt_tu_stunde_20020101_20241231_02385.txt
Reading: produkt_tu_stunde_20020101_20241231_02429.txt
Reading: produkt_tu_stunde_20020101_20241231_02437.txt
Reading: produkt_tu_stunde_20020101_20241231_02564.txt
Reading: produkt_tu_stunde_20020101_20241231_02773.txt
Reading: produkt_tu_stunde_20020101_20241231_02796.txt
Reading: produkt_tu_stunde_20020101_20241231_02886.txt
Reading: produkt_tu_stunde_20020101_20241231_02905.txt
Reading: produkt_tu_stunde_20020101_20241231_02961.txt
Reading: produkt_tu_stunde_20020101_20241231_03362.txt
Reading: produkt_tu_stunde_20020101_20241231_03484.txt
Reading: produkt_tu_stunde_20020101_20241231_03603.txt
Reading: produkt_tu_stunde_20020101_20241231_03623.txt
Reading: produkt_tu_stunde_20020101_20241231_03639.txt
Reading: produkt_tu_stunde_20020101_20241231_03897.txt
Reading: produkt_tu_stunde_20020101_20241231_04280.txt
Reading: produkt_tu_stunde_20020101_20241231_05109.txt
Reading: produkt_tu_stunde_20020101_20241231_05640.txt
Reading: produkt_tu_stunde_20020101_20241231_05715.txt
Reading: produkt_tu_stunde_20020101_20241231_05800.txt
Reading: produkt_tu_stunde_20020101_20241231_06197.txt
Reading: produkt_tu_stunde_20020102_20021120_03245.txt
Reading: produkt_tu_stunde_20020102_20241231_03254.txt
Reading: produkt_tu_stunde_20020124_20241231_01736.txt
Reading: produkt_tu_stunde_20020124_20241231_04411.txt
Reading: produkt_tu_stunde_20021101_20241231_00257.txt
Reading: produkt_tu_stunde_20021101_20241231_02315.txt
Reading: produkt_tu_stunde_20021101_20241231_03268.txt
Reading: produkt_tu_stunde_20021101_20241231_03402.txt
Reading: produkt_tu_stunde_20021101_20241231_04169.txt
Reading: produkt_tu_stunde_20021101_20241231_04703.txt
Reading: produkt_tu_stunde_20021101_20241231_04978.txt
Reading: produkt_tu_stunde_20021101_20241231_06262.txt
Reading: produkt_tu_stunde_20021103_20071115_04702.txt
Reading: produkt_tu_stunde_20021104_20030814_01515.txt
Reading: produkt_tu_stunde_20021201_20241231_01224.txt
Reading: produkt_tu_stunde_20021201_20241231_01255.txt
Reading: produkt_tu_stunde_20021201_20241231_06260.txt
Reading: produkt_tu_stunde_20030101_20241201_02110.txt
Reading: produkt_tu_stunde_20030101_20241231_06258.txt
Reading: produkt_tu_stunde_20030701_20241231_01590.txt
Reading: produkt_tu_stunde_20030701_20241231_04063.txt
Reading: produkt_tu_stunde_20030910_20241231_05480.txt
Reading: produkt_tu_stunde_20040501_20200615_00410.txt
Reading: produkt_tu_stunde_20040501_20241231_00314.txt
Reading: produkt_tu_stunde_20040501_20241231_01645.txt
Reading: produkt_tu_stunde_20040501_20241231_02704.txt
Reading: produkt_tu_stunde_20040501_20241231_03527.txt
Reading: produkt_tu_stunde_20040501_20241231_05825.txt
Reading: produkt_tu_stunde_20040501_20241231_06093.txt
Reading: produkt_tu_stunde_20040501_20241231_06105.txt
Reading: produkt_tu_stunde_20040501_20241231_06265.txt
Reading: produkt_tu_stunde_20040601_20050512_02088.txt
Reading: produkt_tu_stunde_20040601_20241231_00535.txt
Reading: produkt_tu_stunde_20040601_20241231_00617.txt
Reading: produkt_tu_stunde_20040601_20241231_00755.txt
Reading: produkt_tu_stunde_20040601_20241231_00757.txt
Reading: produkt_tu_stunde_20040601_20241231_01072.txt
Reading: produkt_tu_stunde_20040601_20241231_01266.txt
Reading: produkt_tu_stunde_20040601_20241231_01300.txt
Reading: produkt_tu_stunde_20040601_20241231_01451.txt
Reading: produkt_tu_stunde_20040601_20241231_02074.txt
Reading: produkt_tu_stunde_20040601_20241231_02951.txt
Reading: produkt_tu_stunde_20040601_20241231_03257.txt
Reading: produkt_tu_stunde_20040601_20241231_03348.txt
Reading: produkt_tu_stunde_20040601_20241231_03426.txt
Reading: produkt_tu_stunde_20040601_20241231_03591.txt
Reading: produkt_tu_stunde_20040601_20241231_04094.txt
Reading: produkt_tu_stunde_20040601_20241231_04175.txt
Reading: produkt_tu_stunde_20040601_20241231_04349.txt
Reading: produkt_tu_stunde_20040601_20241231_05146.txt
Reading: produkt_tu_stunde_20040601_20241231_05275.txt
Reading: produkt_tu_stunde_20040601_20241231_05562.txt
Reading: produkt_tu_stunde_20040601_20241231_06170.txt
Reading: produkt_tu_stunde_20040601_20241231_06259.txt
Reading: produkt_tu_stunde_20040601_20241231_06264.txt
Reading: produkt_tu_stunde_20040601_20241231_06273.txt
Reading: produkt_tu_stunde_20040701_20080923_01239.txt
Reading: produkt_tu_stunde_20040701_20120912_02080.txt
Reading: produkt_tu_stunde_20040701_20130708_00326.txt
Reading: produkt_tu_stunde_20040701_20241231_00259.txt
Reading: produkt_tu_stunde_20040701_20241231_00294.txt
Reading: produkt_tu_stunde_20040701_20241231_00390.txt
Reading: produkt_tu_stunde_20040701_20241231_01052.txt
Reading: produkt_tu_stunde_20040701_20241231_01602.txt

           STATIONS_ID  MESS_DATUM  QN_9  TT_TU  RF_TU  eor
117482490         5133  2018112816     3    2.7   80.0  eor
66443921          1048  1990081112     3   19.7   60.0  eor
39466943          3015  1995100123     3    7.8   99.0  eor
24324029          5792  1996021501    10  -17.7  100.0  eor
14051304          4887  1949082209     5   17.3   42.0  eor
150736421        15555  2021022020     3   11.4   48.0  eor
64072944           876  1981042018     3    6.2   43.0  eor
8846067            656  2000080522    10   10.8   90.0  eor
112188449         5300  2016010821     3    0.4   97.0  eor
22800132          4371  1972031406     5    2.1   77.0  eor

In [15]:
import pandas as pd

total_rows = 0

for chunk in pd.read_csv('Document_Corpus/dwd_temp/final_merged_dwd_temp.csv', chunksize=100000):
    total_rows += len(chunk)

print("Total rows:", total_rows)

Total rows: 157887566

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14775051 entries, 0 to 14775050
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   STATIONS_ID     int64
 1   MESS_DATUM      object
 2   QN_592          int64
 3   ATMO_LBERG      float64
 4   FD_LBERG        float64
 5   FG_LBERG        float64
 6   SD_LBERG        float64
 7   ZENIT           float64
 8   MESS_DATUM_WOZ  object
 9   eor             object
 10  source_file     object
dtypes: float64(5), int64(2), object(4)
memory usage: 1.2+ GB

# Merging all Wind text files as csv

In [16]:
import pandas as pd
from pathlib import Path
# Folder containing extracted DWD text files
input_folder = Path("Document_Corpus/dwd_wind/extracted")

# Find all .txt files
txt_files = list(input_folder.glob("*.txt"))

print(f"Total TXT files found: {len(txt_files)}")

# Preview first few files
for f in txt_files[:5]:
    print(f.name)

all_data = []
errors = []

for file_path in txt_files:
    try:
        print(f"Reading: {file_path.name}")
        
        # Read semicolon-separated DWD file
        df = pd.read_csv(
            file_path,
            sep=';',
            comment='#',      # ignore metadata lines if any
            engine='python'
        )
        
        # Optional: add source file name for traceability
        # df["source_file"] = file_path.name
        
        all_data.append(df)
        
    except Exception as e:
        errors.append((file_path.name, str(e)))
        print(f"Error reading {file_path.name}: {e}")




merged_df = pd.concat(all_data, ignore_index=True)
# Remove extra spaces from column names
merged_df.columns = merged_df.columns.str.strip()

print(merged_df.columns.tolist())

print("Merged shape:", merged_df.shape)



# Replace common DWD missing values
# merged_df.replace(-999, pd.NA, inplace=True)
# merged_df.replace(-999.0, pd.NA, inplace=True)




output_file = Path("Document_Corpus/dwd_wind/final_merged_dwd_wind.csv")

merged_df.to_csv(output_file, index=False)

print(f"Final merged CSV saved at: {output_file.resolve()}")



print("="*50)
print("MERGE SUMMARY")
print("="*50)
print(f"TXT files processed: {len(txt_files)}")
print(f"Rows in final dataset: {len(merged_df)}")
print(f"Columns in final dataset: {len(merged_df.columns)}")
print(f"Errors: {len(errors)}")
merged_df.sample(10)

Total TXT files found: 749
produkt_ff_stunde_18930101_20020831_03988.txt
produkt_ff_stunde_18930101_20241231_03987.txt
produkt_ff_stunde_19260101_20241231_00691.txt
produkt_ff_stunde_19360101_19710731_05732.txt
produkt_ff_stunde_19370101_20110331_00003.txt
Reading: produkt_ff_stunde_18930101_20020831_03988.txt
Reading: produkt_ff_stunde_18930101_20241231_03987.txt
Reading: produkt_ff_stunde_19260101_20241231_00691.txt
Reading: produkt_ff_stunde_19360101_19710731_05732.txt
Reading: produkt_ff_stunde_19370101_20110331_00003.txt
Reading: produkt_ff_stunde_19370101_20241231_00656.txt
Reading: produkt_ff_stunde_19370101_20241231_05100.txt
Reading: produkt_ff_stunde_19390101_20241231_01639.txt
Reading: produkt_ff_stunde_19390101_20241231_02290.txt
Reading: produkt_ff_stunde_19410101_19701231_05282.txt
Reading: produkt_ff_stunde_19450101_19751231_01960.txt
Reading: produkt_ff_stunde_19480101_20081031_02522.txt
Reading: produkt_ff_stunde_19480101_20241231_02261.txt
Reading: produkt_ff_stunde_19490101_20241231_03668.txt
Reading: produkt_ff_stunde_19490101_20241231_04104.txt
Reading: produkt_ff_stunde_19490801_19840731_04927.txt
Reading: produkt_ff_stunde_19500101_20070630_05419.txt
Reading: produkt_ff_stunde_19500101_20090201_00998.txt
Reading: produkt_ff_stunde_19500101_20241231_01975.txt
Reading: produkt_ff_stunde_19500101_20241231_02014.txt
Reading: produkt_ff_stunde_19500101_20241231_03032.txt
Reading: produkt_ff_stunde_19500301_19741231_01221.txt
Reading: produkt_ff_stunde_19500301_19920517_03390.txt
Reading: produkt_ff_stunde_19510101_19850228_03085.txt
Reading: produkt_ff_stunde_19510101_20241231_01580.txt
Reading: produkt_ff_stunde_19510101_20241231_03015.txt
Reading: produkt_ff_stunde_19510101_20241231_03730.txt
Reading: produkt_ff_stunde_19510501_19621231_01425.txt
Reading: produkt_ff_stunde_19520101_20241231_00701.txt
Reading: produkt_ff_stunde_19520101_20241231_01078.txt
Reading: produkt_ff_stunde_19520101_20241231_03761.txt
Reading: produkt_ff_stunde_19520101_20241231_04887.txt
Reading: produkt_ff_stunde_19520101_20241231_05397.txt
Reading: produkt_ff_stunde_19530101_19881015_02565.txt
Reading: produkt_ff_stunde_19530101_20030505_02503.txt
Reading: produkt_ff_stunde_19530101_20241231_04931.txt
Reading: produkt_ff_stunde_19530101_20241231_05490.txt
Reading: produkt_ff_stunde_19540101_20131031_02532.txt
Reading: produkt_ff_stunde_19540101_20241231_04271.txt
Reading: produkt_ff_stunde_19540101_20241231_04625.txt
Reading: produkt_ff_stunde_19550101_20241231_01346.txt
Reading: produkt_ff_stunde_19550101_20241231_01358.txt
Reading: produkt_ff_stunde_19550101_20241231_01443.txt
Reading: produkt_ff_stunde_19550101_20241231_03366.txt
Reading: produkt_ff_stunde_19560101_19760630_03577.txt
Reading: produkt_ff_stunde_19560101_20241231_00722.txt
Reading: produkt_ff_stunde_19560101_20241231_04336.txt
Reading: produkt_ff_stunde_19570701_20241231_02667.txt
Reading: produkt_ff_stunde_19570701_20241231_05516.txt
Reading: produkt_ff_stunde_19570801_20241231_03126.txt
Reading: produkt_ff_stunde_19580101_19751031_05063.txt
Reading: produkt_ff_stunde_19580101_20080701_04752.txt
Reading: produkt_ff_stunde_19580101_20241231_02928.txt
Reading: produkt_ff_stunde_19580201_20241231_04466.txt
Reading: produkt_ff_stunde_19580601_20241231_04745.txt
Reading: produkt_ff_stunde_19590101_20241231_01544.txt
Reading: produkt_ff_stunde_19590101_20241231_02115.txt
Reading: produkt_ff_stunde_19590101_20241231_05371.txt
Reading: produkt_ff_stunde_19590108_19790618_02201.txt
Reading: produkt_ff_stunde_19590701_20241231_02712.txt
Reading: produkt_ff_stunde_19590820_20101130_03815.txt
Reading: produkt_ff_stunde_19600101_19780331_03661.txt
Reading: produkt_ff_stunde_19610101_19771231_01758.txt
Reading: produkt_ff_stunde_19610101_20241231_00198.txt
Reading: produkt_ff_stunde_19610101_20241231_00232.txt
Reading: produkt_ff_stunde_19610101_20241231_00853.txt
Reading: produkt_ff_stunde_19610101_20241231_05629.txt
Reading: produkt_ff_stunde_19630101_20241231_01303.txt
Reading: produkt_ff_stunde_19630101_20241231_01684.txt
Reading: produkt_ff_stunde_19640101_19841231_01426.txt
Reading: produkt_ff_stunde_19650101_19711016_02374.txt
Reading: produkt_ff_stunde_19650101_19911231_03404.txt
Reading: produkt_ff_stunde_19650101_20241231_00766.txt
Reading: produkt_ff_stunde_19650101_20241231_00788.txt
Reading: produkt_ff_stunde_19650101_20241231_01490.txt
Reading: produkt_ff_stunde_19660101_19961231_03879.txt
Reading: produkt_ff_stunde_19660101_20241231_00662.txt
Reading: produkt_ff_stunde_19660101_20241231_02559.txt
Reading: produkt_ff_stunde_19660101_20241231_02601.txt
Reading: produkt_ff_stunde_19660101_20241231_05705.txt
Reading: produkt_ff_stunde_19670101_20241231_01420.txt
Reading: produkt_ff_stunde_19690101_19750531_04665.txt
Reading: produkt_ff_stunde_19690101_19770630_04933.txt
Reading: produkt_ff_stunde_19690101_19811031_05120.txt
Reading: produkt_ff_stunde_19690101_19820930_02093.txt
Reading: produkt_ff_stunde_19690101_19911231_01515.txt
Reading: produkt_ff_stunde_19690101_19920731_01261.txt
Reading: produkt_ff_stunde_19690101_19951130_00044.txt
Reading: produkt_ff_stunde_19690101_19951231_03096.txt
Reading: produkt_ff_stunde_19690101_19970331_01987.txt
Reading: produkt_ff_stunde_19690101_20011231_00052.txt
Reading: produkt_ff_stunde_19690101_20021129_03245.txt
Reading: produkt_ff_stunde_19690101_20040630_02456.txt
Reading: produkt_ff_stunde_19690101_20120921_05467.txt
Reading: produkt_ff_stunde_19690101_20121001_03791.txt
Reading: produkt_ff_stunde_19690101_20140901_05155.txt
Reading: produkt_ff_stunde_19690101_20171222_02829.txt
Reading: produkt_ff_stunde_19690101_20241231_00460.txt
Reading: produkt_ff_stunde_19690101_20241231_00891.txt
Reading: produkt_ff_stunde_19690101_20241231_00953.txt
Reading: produkt_ff_stunde_19690101_20241231_01550.txt
Reading: produkt_ff_stunde_19690101_20241231_01691.txt
Reading: produkt_ff_stunde_19690101_20241231_01963.txt
Reading: produkt_ff_stunde_19690101_20241231_02303.txt
Reading: produkt_ff_stunde_19690101_20241231_02483.txt
Reading: produkt_ff_stunde_19690101_20241231_02638.txt
Reading: produkt_ff_stunde_19690101_20241231_02905.txt
Reading: produkt_ff_stunde_19690101_20241231_03167.txt
Reading: produkt_ff_stunde_19690101_20241231_03623.txt
Reading: produkt_ff_stunde_19690101_20241231_03631.txt
Reading: produkt_ff_stunde_19690101_20241231_04371.txt
Reading: produkt_ff_stunde_19690101_20241231_04393.txt
Reading: produkt_ff_stunde_19690101_20241231_05440.txt
Reading: produkt_ff_stunde_19690101_20241231_05640.txt
Reading: produkt_ff_stunde_19690101_20241231_05906.txt
Reading: produkt_ff_stunde_19690901_19920831_00706.txt
Reading: produkt_ff_stunde_19700101_19880729_04678.txt
Reading: produkt_ff_stunde_19700101_20241231_02886.txt
Reading: produkt_ff_stunde_19700201_20161231_03023.txt
Reading: produkt_ff_stunde_19700601_19741231_00553.txt
Reading: produkt_ff_stunde_19700701_19891231_02656.txt
Reading: produkt_ff_stunde_19700701_19960930_03954.txt
Reading: produkt_ff_stunde_19701001_20241231_01468.txt
Reading: produkt_ff_stunde_19710101_19741031_02906.txt
Reading: produkt_ff_stunde_19710101_19821231_03575.txt
Reading: produkt_ff_stunde_19710101_19891231_02926.txt
Reading: produkt_ff_stunde_19710101_19900430_06277.txt
Reading: produkt_ff_stunde_19710101_19931231_03518.txt
Reading: produkt_ff_stunde_19710101_19950831_06189.txt
Reading: produkt_ff_stunde_19710101_20071231_01666.txt
Reading: produkt_ff_stunde_19710101_20080131_02437.txt
Reading: produkt_ff_stunde_19710101_20171219_04174.txt
Reading: produkt_ff_stunde_19710101_20241231_01339.txt
Reading: produkt_ff_stunde_19710101_20241231_04280.txt
Reading: produkt_ff_stunde_19710101_20241231_05078.txt
Reading: produkt_ff_stunde_19710401_20241231_03028.txt
Reading: produkt_ff_stunde_19710801_20241231_00282.txt
Reading: produkt_ff_stunde_19720101_19950327_03659.txt
Reading: produkt_ff_stunde_19720101_20060930_00769.txt
Reading: produkt_ff_stunde_19720101_20150323_01957.txt
Reading: produkt_ff_stunde_19720101_20241231_00867.txt
Reading: produkt_ff_stunde_19720101_20241231_03093.txt
Reading: produkt_ff_stunde_19720101_20241231_05404.txt
Reading: produkt_ff_stunde_19720401_20040229_01130.txt
Reading: produkt_ff_stunde_19720501_19871231_01423.txt
Reading: produkt_ff_stunde_19720501_20241231_02932.txt
Reading: produkt_ff_stunde_19721001_19991130_04629.txt
Reading: produkt_ff_stunde_19721201_20241231_02597.txt
Reading: produkt_ff_stunde_19730101_19760930_05431.txt
Reading: produkt_ff_stunde_19730101_19770531_03442.txt
Reading: produkt_ff_stunde_19730101_19780630_01834.txt
Reading: produkt_ff_stunde_19730101_19881231_00876.txt
Reading: produkt_ff_stunde_19730101_20040630_05009.txt
Reading: produkt_ff_stunde_19730101_20190408_03552.txt
Reading: produkt_ff_stunde_19730101_20241231_00183.txt
Reading: produkt_ff_stunde_19730101_20241231_00368.txt
Reading: produkt_ff_stunde_19730101_20241231_00427.txt
Reading: produkt_ff_stunde_19730101_20241231_00591.txt
Reading: produkt_ff_stunde_19730101_20241231_00596.txt
Reading: produkt_ff_stunde_19730101_20241231_01048.txt
Reading: produkt_ff_stunde_19730101_20241231_01270.txt
Reading: produkt_ff_stunde_19730101_20241231_01612.txt
Reading: produkt_ff_stunde_19730101_20241231_02925.txt
Reading: produkt_ff_stunde_19730101_20241231_03254.txt
Reading: produkt_ff_stunde_19730101_20241231_03484.txt
Reading: produkt_ff_stunde_19730101_20241231_03946.txt
Reading: produkt_ff_stunde_19730801_19890430_01422.txt
Reading: produkt_ff_stunde_19731201_20241231_05426.txt
Reading: produkt_ff_stunde_19740101_19960930_05154.txt
Reading: produkt_ff_stunde_19740101_20241231_00433.txt
Reading: produkt_ff_stunde_19740101_20241231_00963.txt
Reading: produkt_ff_stunde_19740101_20241231_02410.txt
Reading: produkt_ff_stunde_19740101_20241231_02564.txt
Reading: produkt_ff_stunde_19740101_20241231_02773.txt
Reading: produkt_ff_stunde_19740101_20241231_03639.txt
Reading: produkt_ff_stunde_19740101_20241231_04911.txt
Reading: produkt_ff_stunde_19740101_20241231_05715.txt
Reading: produkt_ff_stunde_19740201_19760430_00175.txt
Reading: produkt_ff_stunde_19740301_19781231_02207.txt
Reading: produkt_ff_stunde_19740301_20241231_00125.txt
Reading: produkt_ff_stunde_19740401_20241231_02385.txt
Reading: produkt_ff_stunde_19740601_19960430_03921.txt
Reading: produkt_ff_stunde_19740601_20051223_02338.txt
Reading: produkt_ff_stunde_19740801_20150630_00850.txt
Reading: produkt_ff_stunde_19741001_19800930_14003.txt
Reading: produkt_ff_stunde_19741201_20241231_02907.txt
Reading: produkt_ff_stunde_19750101_19801231_00424.txt
Reading: produkt_ff_stunde_19750101_19980310_01219.txt
Reading: produkt_ff_stunde_19750101_19990228_00599.txt
Reading: produkt_ff_stunde_19750101_20060228_00554.txt
Reading: produkt_ff_stunde_19750101_20071031_01505.txt
Reading: produkt_ff_stunde_19750101_20241231_05480.txt
Reading: produkt_ff_stunde_19750401_20150630_00399.txt
Reading: produkt_ff_stunde_19750601_20241231_05029.txt
Reading: produkt_ff_stunde_19750701_20051031_19580.txt
Reading: produkt_ff_stunde_19760101_20241231_05792.txt
Reading: produkt_ff_stunde_19760401_20241231_02171.txt
Reading: produkt_ff_stunde_19760401_20241231_05779.txt
Reading: produkt_ff_stunde_19760501_19810531_05244.txt
Reading: produkt_ff_stunde_19760601_19881231_01415.txt
Reading: produkt_ff_stunde_19760701_20010831_19582.txt
Reading: produkt_ff_stunde_19760701_20050816_03478.txt
Reading: produkt_ff_stunde_19760901_20241231_04928.txt
Reading: produkt_ff_stunde_19761001_20241231_04642.txt
Reading: produkt_ff_stunde_19761201_19971231_03103.txt
Reading: produkt_ff_stunde_19761201_20241231_01993.txt
Reading: produkt_ff_stunde_19770127_20241231_02812.txt
Reading: produkt_ff_stunde_19770301_19930729_01526.txt
Reading: produkt_ff_stunde_19770301_19940531_02486.txt
Reading: produkt_ff_stunde_19770301_20080531_00330.txt
Reading: produkt_ff_stunde_19770601_20041231_19581.txt
Reading: produkt_ff_stunde_19770701_19950831_04549.txt
Reading: produkt_ff_stunde_19771001_20241231_04919.txt
Reading: produkt_ff_stunde_19780101_19981216_03775.txt
Reading: produkt_ff_stunde_19780101_20241231_01757.txt
Reading: produkt_ff_stunde_19780501_19930731_00259.txt
Reading: produkt_ff_stunde_19780701_20241231_04501.txt
Reading: produkt_ff_stunde_19780801_19880831_05675.txt
Reading: produkt_ff_stunde_19780901_19950531_00072.txt
Reading: produkt_ff_stunde_19781201_19800430_02482.txt
Reading: produkt_ff_stunde_19781201_19930531_03300.txt
Reading: produkt_ff_stunde_19790101_19970131_00320.txt
Reading: produkt_ff_stunde_19790101_20041231_02228.txt
Reading: produkt_ff_stunde_19790101_20080501_05049.txt
Reading: produkt_ff_stunde_19790101_20241231_00164.txt
Reading: produkt_ff_stunde_19790101_20241231_02497.txt
Reading: produkt_ff_stunde_19790101_20241231_03231.txt
Reading: produkt_ff_stunde_19790201_20241231_13901.txt
Reading: produkt_ff_stunde_19790401_20030331_01920.txt
Reading: produkt_ff_stunde_19790401_20241231_00704.txt
Reading: produkt_ff_stunde_19790601_19901130_05128.txt
Reading: produkt_ff_stunde_19790601_20190412_04225.txt
Reading: produkt_ff_stunde_19790901_19871231_00193.txt
Reading: produkt_ff_stunde_19791101_20101130_00126.txt
Reading: produkt_ff_stunde_19800101_20060315_03369.txt
Reading: produkt_ff_stunde_19800201_19910331_03046.txt
Reading: produkt_ff_stunde_19800401_20241231_01013.txt
Reading: produkt_ff_stunde_19800901_20241231_00011.txt
Reading: produkt_ff_stunde_19801201_19850718_01297.txt
Reading: produkt_ff_stunde_19801201_20241231_00161.txt
Reading: produkt_ff_stunde_19810101_19911031_05745.txt
Reading: produkt_ff_stunde_19810101_19970331_03228.txt
Reading: produkt_ff_stunde_19810101_20040928_07244.txt
Reading: produkt_ff_stunde_19810101_20100501_04477.txt
Reading: produkt_ff_stunde_19810101_20241231_00298.txt
Reading: produkt_ff_stunde_19810101_20241231_00642.txt
Reading: produkt_ff_stunde_19810101_20241231_01001.txt
Reading: produkt_ff_stunde_19810101_20241231_01869.txt
Reading: produkt_ff_stunde_19810101_20241231_02044.txt
Reading: produkt_ff_stunde_19810101_20241231_02377.txt
Reading: produkt_ff_stunde_19810101_20241231_03196.txt
Reading: produkt_ff_stunde_19810101_20241231_05349.txt
Reading: produkt_ff_stunde_19810301_20241231_03534.txt
Reading: produkt_ff_stunde_19810501_19901231_02465.txt
Reading: produkt_ff_stunde_19810714_20241231_05327.txt
Reading: produkt_ff_stunde_19810801_20241231_05319.txt
Reading: produkt_ff_stunde_19810801_20241231_05930.txt
Reading: produkt_ff_stunde_19810901_20241231_01694.txt
Reading: produkt_ff_stunde_19820101_19910502_02166.txt
Reading: produkt_ff_stunde_19820101_19921126_01359.txt
Reading: produkt_ff_stunde_19820101_19961130_05663.txt
Reading: produkt_ff_stunde_19820101_20080701_00222.txt
Reading: produkt_ff_stunde_19820101_20241231_01605.txt
Reading: produkt_ff_stunde_19820101_20241231_01766.txt
Reading: produkt_ff_stunde_19820101_20241231_03166.txt
Reading: produkt_ff_stunde_19820101_20241231_04024.txt
Reading: produkt_ff_stunde_19820101_20241231_05142.txt
Reading: produkt_ff_stunde_19820201_20110412_04663.txt
Reading: produkt_ff_stunde_19820801_19950430_06136.txt
Reading: produkt_ff_stunde_19821101_20241231_01832.txt
Reading: produkt_ff_stunde_19821201_20041231_01572.txt
Reading: produkt_ff_stunde_19821201_20241231_01379.txt
Reading: produkt_ff_stunde_19821201_20241231_04039.txt
Reading: produkt_ff_stunde_19830101_20031210_05306.txt
Reading: produkt_ff_stunde_19830101_20050930_05289.txt
Reading: produkt_ff_stunde_19830101_20241231_00880.txt
Reading: produkt_ff_stunde_19830101_20241231_03811.txt
Reading: produkt_ff_stunde_19830601_20150831_03657.txt
Reading: produkt_ff_stunde_19830901_20040827_01831.txt
Reading: produkt_ff_stunde_19831001_19960731_02253.txt
Reading: produkt_ff_stunde_19840101_19950531_05059.txt
Reading: produkt_ff_stunde_19840401_19871231_01416.txt
Reading: produkt_ff_stunde_19840901_19850531_04929.txt
Reading: produkt_ff_stunde_19841101_20070531_03246.txt
Reading: produkt_ff_stunde_19841201_20241231_04880.txt
Reading: produkt_ff_stunde_19850101_19891031_03256.txt
Reading: produkt_ff_stunde_19850101_20241231_03379.txt
Reading: produkt_ff_stunde_19850206_20180125_07308.txt
Reading: produkt_ff_stunde_19850301_20241231_03086.txt
Reading: produkt_ff_stunde_19860101_20241231_03821.txt
Reading: produkt_ff_stunde_19860701_20241231_05546.txt
Reading: produkt_ff_stunde_19860801_20241231_00603.txt
Reading: produkt_ff_stunde_19870101_20210505_00430.txt
Reading: produkt_ff_stunde_19870401_20080923_01010.txt
Reading: produkt_ff_stunde_19870501_20241231_00619.txt
Reading: produkt_ff_stunde_19870521_20241231_13932.txt
Reading: produkt_ff_stunde_19870610_20241231_02573.txt
Reading: produkt_ff_stunde_19870610_20241231_06211.txt
Reading: produkt_ff_stunde_19870611_20011117_05226.txt
Reading: produkt_ff_stunde_19871001_20241231_03287.txt
Reading: produkt_ff_stunde_19871113_20141228_02055.txt
Reading: produkt_ff_stunde_19871208_19901231_05249.txt
Reading: produkt_ff_stunde_19880219_20241231_00090.txt
Reading: produkt_ff_stunde_19880301_20241231_02429.txt
Reading: produkt_ff_stunde_19880817_20241231_04947.txt
Reading: produkt_ff_stunde_19890101_20241231_02794.txt
Reading: produkt_ff_stunde_19890101_20241231_03158.txt
Reading: produkt_ff_stunde_19890101_20241231_05158.txt
Reading: produkt_ff_stunde_19890406_20241231_03925.txt
Reading: produkt_ff_stunde_19890418_20241231_04279.txt
Reading: produkt_ff_stunde_19890501_20100501_05665.txt
Reading: produkt_ff_stunde_19890501_20241231_03513.txt
Reading: produkt_ff_stunde_19890801_20241231_04464.txt
Reading: produkt_ff_stunde_19891001_19911031_04445.txt
Reading: produkt_ff_stunde_19891030_20241231_02349.txt
Reading: produkt_ff_stunde_19891214_20110901_00348.txt
Reading: produkt_ff_stunde_19900501_20241231_00840.txt
Reading: produkt_ff_stunde_19900701_19920630_01689.txt
Reading: produkt_ff_stunde_19900801_20241231_00197.txt
Reading: produkt_ff_stunde_19900829_20241231_03905.txt
Reading: produkt_ff_stunde_19900830_20241231_02897.txt
Reading: produkt_ff_stunde_19901011_20241231_01011.txt
Reading: produkt_ff_stunde_19910101_20001025_00400.txt
Reading: produkt_ff_stunde_19910101_20241231_01803.txt
Reading: produkt_ff_stunde_19910101_20241231_03376.txt
Reading: produkt_ff_stunde_19910531_20241231_05412.txt
Reading: produkt_ff_stunde_19910903_19940630_06221.txt
Reading: produkt_ff_stunde_19911101_20241231_02985.txt
Reading: produkt_ff_stunde_19911126_20081226_04583.txt
Reading: produkt_ff_stunde_19920201_19980331_02444.txt
Reading: produkt_ff_stunde_19920402_20241231_03651.txt
Reading: produkt_ff_stunde_19920519_20241231_01262.txt
Reading: produkt_ff_stunde_19921201_19941130_03274.txt
Reading: produkt_ff_stunde_19930101_20130930_02494.txt
Reading: produkt_ff_stunde_19930906_20241231_00303.txt
Reading: produkt_ff_stunde_19931215_20241231_01357.txt
Reading: produkt_ff_stunde_19940101_20241231_03098.txt
Reading: produkt_ff_stunde_19950101_20241231_13900.txt
Reading: produkt_ff_stunde_19950301_20241231_03660.txt
Reading: produkt_ff_stunde_19961231_20241231_05856.txt
Reading: produkt_ff_stunde_19970310_20241231_05877.txt
Reading: produkt_ff_stunde_19970312_20241231_05851.txt
Reading: produkt_ff_stunde_19970701_20241115_05839.txt
Reading: produkt_ff_stunde_19971008_20241231_06091.txt
Reading: produkt_ff_stunde_19971105_20241231_02252.txt
Reading: produkt_ff_stunde_19971209_20241231_04094.txt
Reading: produkt_ff_stunde_19980101_19980201_02738.txt
Reading: produkt_ff_stunde_19980717_20241231_06096.txt
Reading: produkt_ff_stunde_19981101_20241231_05871.txt
Reading: produkt_ff_stunde_19981104_20241231_06097.txt
Reading: produkt_ff_stunde_19990331_20241231_06102.txt
Reading: produkt_ff_stunde_19990414_20241231_06107.txt
Reading: produkt_ff_stunde_19990501_20241231_02856.txt
Reading: produkt_ff_stunde_19991101_20081102_00181.txt
Reading: produkt_ff_stunde_19991216_20241231_06101.txt
Reading: produkt_ff_stunde_20000420_20241231_06099.txt
Reading: produkt_ff_stunde_20000503_20100430_06098.txt
Reading: produkt_ff_stunde_20000606_20241231_06103.txt

           STATIONS_ID  MESS_DATUM  QN_3    F    D  eor
26511301          5516  2022080807    10  2.9  280  eor
44743273           891  2018081401    10  3.5  240  eor
88193078          7244  1985102314    10  1.0   70  eor
94561062          1766  2019121322    10  3.5  220  eor
19193813          4931  2009022105    10  1.5  290  eor
113757663         5871  2014102107    10  4.7  220  eor
20545475          4271  1968122616     5  6.3  330  eor
60865504          5404  2020111413    10  2.5  110  eor
78921547          4928  1985051507    10  1.5  360  eor
122414447        13965  2019011815    10  1.5   50  eor

# Power Consumption Data merging

In [1]:
import pandas as pd
from pathlib import Path

# Folder containing CSV files
input_folder = Path("Document_Corpus/power_consumption/seperated")

# Find all CSV files
csv_files = list(input_folder.glob("*.csv"))

print(f"Total CSV files found: {len(csv_files)}")

# Preview first few file names
for f in csv_files[:10]:
    print(f.name)

all_data = []
errors = []

for file_path in csv_files:
    try:
        print(f"Reading: {file_path.name}")
        
        df = pd.read_csv(file_path, sep=';',  engine='python')
        
        # Optional: keep source file name
        df["source_file"] = file_path.name
        
        all_data.append(df)
        
    except Exception as e:
        errors.append((file_path.name, str(e)))
        print(f"Error reading {file_path.name}: {e}")


merged_df = pd.concat(all_data, ignore_index=True)

print("Merged shape:", merged_df.shape)
merged_df.head()

merged_df.columns = merged_df.columns.str.strip()
print(merged_df.columns.tolist())

output_file = Path("Document_Corpus/power_consumption/final_merged_power_consumption.csv")

merged_df.to_csv(output_file, index=False)

print(f"Final merged CSV saved at: {output_file.resolve()}")


print("="*50)
print("MERGE SUMMARY")
print("="*50)
print(f"CSV files processed: {len(csv_files)}")
print(f"Rows in final dataset: {len(merged_df)}")
print(f"Columns in final dataset: {len(merged_df.columns)}")
print(f"Errors: {len(errors)}")

Total CSV files found: 2
Actual_consumption_201501010000_202101010000_Hour.csv
Actual_consumption_202101010000_202604010000_Hour.csv
Reading: Actual_consumption_201501010000_202101010000_Hour.csv
Reading: Actual_consumption_202101010000_202604010000_Hour.csv
Merged shape: (98591, 7)
['Start date', 'End date', 'grid load [MWh] Calculated resolutions', 'Grid load incl. hydro pumped storage [MWh] Calculated resolutions', 'Hydro pumped storage [MWh] Calculated resolutions', 'Residual load [MWh] Calculated resolutions', 'source_file']
Final merged CSV saved at: C:\Users\Kamal_FOM\python\python\Thesis2015-2026\Document_Corpus\power_consumption\final_merged_power_consumption.csv
==================================================
MERGE SUMMARY
==================================================
CSV files processed: 2
Rows in final dataset: 98591
Columns in final dataset: 7
Errors: 0

# Power generation data merging

In [31]:
import pandas as pd
from pathlib import Path

# Folder containing CSV files
input_folder = Path("Document_Corpus/power_generation/seperated")

# Find all CSV files
csv_files = list(input_folder.glob("*.csv"))

print(f"Total CSV files found: {len(csv_files)}")

# Preview first few file names
for f in csv_files[:10]:
    print(f.name)

all_data = []
errors = []

for file_path in csv_files:
    try:
        print(f"Reading: {file_path.name}")
        
        df = pd.read_csv(file_path, sep=';',  engine='python')
        
        # Optional: keep source file name
        df["source_file"] = file_path.name
        
        all_data.append(df)
        
    except Exception as e:
        errors.append((file_path.name, str(e)))
        print(f"Error reading {file_path.name}: {e}")


merged_df = pd.concat(all_data, ignore_index=True)

print("Merged shape:", merged_df.shape)
merged_df.head()

merged_df.columns = merged_df.columns.str.strip()
print(merged_df.columns.tolist())

output_file = Path("Document_Corpus/power_generation/final_merged_power_generation.csv")

merged_df.to_csv(output_file, index=False)

print(f"Final merged CSV saved at: {output_file.resolve()}")


print("="*50)
print("MERGE SUMMARY")
print("="*50)
print(f"CSV files processed: {len(csv_files)}")
print(f"Rows in final dataset: {len(merged_df)}")
print(f"Columns in final dataset: {len(merged_df.columns)}")
print(f"Errors: {len(errors)}")

Total CSV files found: 3
01_Actual_generation_201501010000_202101010000_Hour.csv
02_Actual_generation_202101010000_202601010000_Hour.csv
03_Actual_generation_202601010000_202604010000_Hour.csv
Reading: 01_Actual_generation_201501010000_202101010000_Hour.csv
Reading: 02_Actual_generation_202101010000_202601010000_Hour.csv
Reading: 03_Actual_generation_202601010000_202604010000_Hour.csv
Merged shape: (98591, 15)
['Start date', 'End date', 'Biomass [MWh] Calculated resolutions', 'Hydropower [MWh] Calculated resolutions', 'Wind offshore [MWh] Calculated resolutions', 'Wind onshore [MWh] Calculated resolutions', 'Photovoltaics [MWh] Calculated resolutions', 'Other renewable [MWh] Calculated resolutions', 'Nuclear [MWh] Calculated resolutions', 'Lignite [MWh] Calculated resolutions', 'Hard coal [MWh] Calculated resolutions', 'Fossil gas [MWh] Calculated resolutions', 'Hydro pumped storage [MWh] Calculated resolutions', 'Other conventional [MWh] Calculated resolutions', 'source_file']
Final merged CSV saved at: C:\Users\Kamal_FOM\python\python\Thesis\RE\Document_Corpus\power_generation\final_merged_power_generation.csv
==================================================
MERGE SUMMARY
==================================================
CSV files processed: 3
Rows in final dataset: 98591
Columns in final dataset: 15
Errors: 0

# Power capacity Data Merging

In [30]:
import pandas as pd
from pathlib import Path

# Folder containing CSV files
input_folder = Path("Document_Corpus/power_capacity/seperated")

# Find all CSV files
csv_files = list(input_folder.glob("*.csv"))

print(f"Total CSV files found: {len(csv_files)}")

# Preview first few file names
for f in csv_files[:10]:
    print(f.name)

all_data = []
errors = []

for file_path in csv_files:
    try:
        print(f"Reading: {file_path.name}")
        
        df = pd.read_csv(file_path, sep=';',  engine='python')
        
        # Optional: keep source file name
        df["source_file"] = file_path.name
        
        all_data.append(df)
        
    except Exception as e:
        errors.append((file_path.name, str(e)))
        print(f"Error reading {file_path.name}: {e}")


merged_df = pd.concat(all_data, ignore_index=True)

print("Merged shape:", merged_df.shape)
merged_df.head()

merged_df.columns = merged_df.columns.str.strip()
print(merged_df.columns.tolist())

output_file = Path("Document_Corpus/power_capacity/final_merged_power_capacity.csv")

merged_df.to_csv(output_file, index=False)

print(f"Final merged CSV saved at: {output_file.resolve()}")


print("="*50)
print("MERGE SUMMARY")
print("="*50)
print(f"CSV files processed: {len(csv_files)}")
print(f"Rows in final dataset: {len(merged_df)}")
print(f"Columns in final dataset: {len(merged_df.columns)}")
print(f"Errors: {len(errors)}")

Total CSV files found: 3
01_Installed_generation_capacity_201501010000_202101010000_Hour.csv
02_Installed_generation_capacity_202101010000_202601010000_Hour.csv
03_Installed_generation_capacity_202601010000_202604010000_Hour.csv
Reading: 01_Installed_generation_capacity_201501010000_202101010000_Hour.csv
Reading: 02_Installed_generation_capacity_202101010000_202601010000_Hour.csv
Reading: 03_Installed_generation_capacity_202601010000_202604010000_Hour.csv
Merged shape: (98591, 15)
['Start date', 'End date', 'Biomass [MW] Calculated resolutions', 'Hydropower [MW] Calculated resolutions', 'Wind offshore [MW] Calculated resolutions', 'Wind onshore [MW] Calculated resolutions', 'Photovoltaics [MW] Calculated resolutions', 'Other renewable [MW] Calculated resolutions', 'Nuclear [MW] Calculated resolutions', 'Lignite [MW] Calculated resolutions', 'Hard coal [MW] Calculated resolutions', 'Fossil gas [MW] Calculated resolutions', 'Hydro pumped storage [MW] Calculated resolutions', 'Other conventional [MW] Calculated resolutions', 'source_file']
Final merged CSV saved at: C:\Users\Kamal_FOM\python\python\Thesis\RE\Document_Corpus\power_capacity\final_merged_power_capacity.csv
==================================================
MERGE SUMMARY
==================================================
CSV files processed: 3
Rows in final dataset: 98591
Columns in final dataset: 15
Errors: 0

# Power price Data Merging

In [19]:
import pandas as pd
from pathlib import Path

# Folder containing CSV files
input_folder = Path("Document_Corpus/power_price/seperated")

# Find all CSV files
csv_files = list(input_folder.glob("*.csv"))

print(f"Total CSV files found: {len(csv_files)}")

# Preview first few file names
for f in csv_files[:10]:
    print(f.name)

all_data = []
errors = []

for file_path in csv_files:
    try:
        print(f"Reading: {file_path.name}")
        
        df = pd.read_csv(file_path, sep=';',  engine='python')
        
        # Optional: keep source file name
        df["source_file"] = file_path.name
        
        all_data.append(df)
        
    except Exception as e:
        errors.append((file_path.name, str(e)))
        print(f"Error reading {file_path.name}: {e}")


merged_df = pd.concat(all_data, ignore_index=True)

print("Merged shape:", merged_df.shape)
merged_df.head()

merged_df.columns = merged_df.columns.str.strip()
print(merged_df.columns.tolist())

output_file = Path("Document_Corpus/power_price/final_merged_power_price.csv")

merged_df.to_csv(output_file, index=False)

print(f"Final merged CSV saved at: {output_file.resolve()}")


print("="*50)
print("MERGE SUMMARY")
print("="*50)
print(f"CSV files processed: {len(csv_files)}")
print(f"Rows in final dataset: {len(merged_df)}")
print(f"Columns in final dataset: {len(merged_df.columns)}")
print(f"Errors: {len(errors)}")

Total CSV files found: 3
01_Day-ahead_prices_201501010000_202101010000_Hour.csv
02_Day-ahead_prices_202101010000_202601010000_Hour.csv
03_Day-ahead_prices_202601010000_202604010000_Hour.csv
Reading: 01_Day-ahead_prices_201501010000_202101010000_Hour.csv
Reading: 02_Day-ahead_prices_202101010000_202601010000_Hour.csv
Reading: 03_Day-ahead_prices_202601010000_202604010000_Hour.csv
Merged shape: (98591, 20)
['Start date', 'End date', 'Germany/Luxembourg [€/MWh] Calculated resolutions', '∅ DE/LU neighbours [€/MWh] Calculated resolutions', 'Belgium [€/MWh] Calculated resolutions', 'Denmark 1 [€/MWh] Calculated resolutions', 'Denmark 2 [€/MWh] Calculated resolutions', 'France [€/MWh] Calculated resolutions', 'Netherlands [€/MWh] Calculated resolutions', 'Norway 2 [€/MWh] Calculated resolutions', 'Austria [€/MWh] Calculated resolutions', 'Poland [€/MWh] Calculated resolutions', 'Sweden 4 [€/MWh] Calculated resolutions', 'Switzerland [€/MWh] Calculated resolutions', 'Czech Republic [€/MWh] Calculated resolutions', 'DE/AT/LU [€/MWh] Calculated resolutions', 'Northern Italy [€/MWh] Calculated resolutions', 'Slovenia [€/MWh] Calculated resolutions', 'Hungary [€/MWh] Calculated resolutions', 'source_file']
Final merged CSV saved at: C:\Users\Kamal_FOM\python\python\Thesis2\Document_corpus\power_price\final_merged_power_price.csv
==================================================
MERGE SUMMARY
==================================================
CSV files processed: 3
Rows in final dataset: 98591
Columns in final dataset: 20
Errors: 0

In [32]:
# Creating a File Structure of Data Corpus
import os
import pandas as pd

# Base folder (your current main folder)
base_folder = os.getcwd()   # assumes script runs inside Document_Corpus

# Output files
tree_output_file = os.path.join(base_folder, "dwd_file_structure.txt")
inventory_output_file = os.path.join(base_folder, "dwd_file_inventory.csv")

# Store inventory rows
inventory = []

def generate_tree(folder, prefix=""):
    """
    Recursively build folder tree as text.
    """
    entries = sorted(os.listdir(folder))
    tree_lines = []

    for i, entry in enumerate(entries):
        path = os.path.join(folder, entry)
        connector = "└── " if i == len(entries) - 1 else "├── "
        tree_lines.append(prefix + connector + entry)

        # Save file/folder info for CSV inventory
        inventory.append({
            "name": entry,
            "full_path": path,
            "type": "folder" if os.path.isdir(path) else "file",
            "extension": os.path.splitext(entry)[1].lower() if os.path.isfile(path) else "",
            "size_bytes": os.path.getsize(path) if os.path.isfile(path) else None
        })

        if os.path.isdir(path):
            extension = "    " if i == len(entries) - 1 else "│   "
            tree_lines.extend(generate_tree(path, prefix + extension))

    return tree_lines

# Generate tree
tree_lines = [os.path.basename(base_folder)]
tree_lines.extend(generate_tree(base_folder))

# Save tree to txt
with open(tree_output_file, "w", encoding="utf-8") as f:
    f.write("\n".join(tree_lines))

# Save inventory to CSV
df_inventory = pd.DataFrame(inventory)
df_inventory.to_csv(inventory_output_file, index=False)

print("Done!")
print(f"Tree file saved at: {tree_output_file}")
print(f"Inventory CSV saved at: {inventory_output_file}")

Done!
Tree file saved at: C:\Users\Kamal_FOM\python\python\Thesis\RE\Document_Corpus\dwd_file_structure.txt
Inventory CSV saved at: C:\Users\Kamal_FOM\python\python\Thesis\RE\Document_Corpus\dwd_file_inventory.csv