In [24]:
# ==========================================================
# 1. IMPORT LIBRARIES
# ==========================================================

import os
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    LSTM,
    Dense,
    Dropout,
    Input
)

from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import backend as K
import gc

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import time

start_time = time.time()

###########################################################

# ==========================================================
# 2. LOAD MODELLING DATASETS
# ==========================================================

solar_model_df = pd.read_csv(
    "Data_Corpus/final/modelling/solar_model_dataset.csv"
)

wind_onshore_model_df = pd.read_csv(
    "Data_Corpus/final/modelling/wind_onshore_model_dataset.csv"
)

wind_offshore_model_df = pd.read_csv(
    "Data_Corpus/final/modelling/wind_offshore_model_dataset.csv"
)

for df in [
    solar_model_df,
    wind_onshore_model_df,
    wind_offshore_model_df
]:
    df["datetime"] = pd.to_datetime(df["datetime"])

    
DATASETS = {
    "Solar": solar_model_df,
    "Wind_Onshore": wind_onshore_model_df,
    "Wind_Offshore": wind_offshore_model_df
}
######################################################33

PERIODS = {

    "FULL": {
        "start": "2015-01-08 00:00:00",
        "train_end": "2022-12-31 23:00:00",
        "valid_end": "2023-12-31 23:00:00"
    },

    "POST_2020": {
        "start": "2020-01-01 00:00:00",
        "train_end": "2023-12-31 23:00:00",
        "valid_end": "2024-12-31 23:00:00"
    },

    "POST_2021": {
        "start": "2021-01-01 00:00:00",
        "train_end": "2023-12-31 23:00:00",
        "valid_end": "2024-12-31 23:00:00"
    }
}

############################################################

HORIZONS = [    1,    6,    24,    72,    168]

###################################

# ==========================================================
# EPOCH SETTINGS
# ==========================================================

EPOCHS_LIST = [    20,    40,    60,    80,    100 ]

########################################3


results = pd.DataFrame(
    columns=[
        "Period",
        "Target",
        "Horizon",
        "Epochs",
        "Model",
        "MAE",
        "RMSE",
        "MAPE",
        "R2"
    ]
)

###################################################
# ==========================================================
# MAPE
# ==========================================================

def calculate_mape(
    y_true,
    y_pred
):

    y_true = np.where(
        y_true == 0,
        1e-8,
        y_true
    )

    mape = np.mean(
        np.abs(
            (y_true - y_pred)
            / y_true
        )
    ) * 100

    return mape


###############################################
def evaluate_model(
    y_true,
    y_pred
):

    mae = mean_absolute_error(
        y_true,
        y_pred
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_true,
            y_pred
        )
    )

    mape = calculate_mape(
        y_true,
        y_pred
    )

    r2 = r2_score(
        y_true,
        y_pred
    )

    return (
        mae,
        rmse,
        mape,
        r2
    )
##############################################

def get_period_split(df, period_name):

    period = PERIODS[period_name]

    df_period = df[
        df["datetime"] >= period["start"]
    ].copy()

    train_df = df_period[
        df_period["datetime"] <= period["train_end"]
    ]

    valid_df = df_period[
        (df_period["datetime"] > period["train_end"]) &
        (df_period["datetime"] <= period["valid_end"])
    ]

    test_df = df_period[
        df_period["datetime"] > period["valid_end"]
    ]

    return train_df, valid_df, test_df

##########################################################

LOOKBACK = 24

def create_sequences(
    X,
    y,
    lookback=24
):

    X_seq = []
    y_seq = []

    for i in range(
        lookback,
        len(X)
    ):

        X_seq.append(
            X[i-lookback:i]
        )

        y_seq.append(
            y[i]
        )

    return (
        np.array(X_seq),
        np.array(y_seq)
    )

    

#################################

def add_result(
    results,
    period,
    target,
    horizon,
    epochs,
    model,
    mae,
    rmse,
    mape,
    r2
):

    results.loc[len(results)] = {

        "Period": period,
        "Target": target,
        "Horizon": horizon,
        "Epochs": epochs,
        "Model": model,

        "MAE": mae,
        "RMSE": rmse,
        "MAPE": mape,
        "R2": r2
    }

    return results




# ==========================================================
# 10. LSTM MODEL FUNCTION
# ==========================================================

def run_lstm(
    X_train,
    y_train,
    X_valid,
    y_valid,
    epochs=20,
    lookback=24
):

    # ==========================================
    # Scale Features
    # ==========================================
    feature_scaler = MinMaxScaler()

    X_train_scaled = feature_scaler.fit_transform(
        X_train
    )

    X_valid_scaled = feature_scaler.transform(
        X_valid
    )

    # ==========================================
    # Scale Target
    # ==========================================
    target_scaler = MinMaxScaler()

    y_train_scaled = target_scaler.fit_transform(
        y_train.values.reshape(-1,1)
    )

    y_valid_scaled = target_scaler.transform(
        y_valid.values.reshape(-1,1)
    )

    # ==========================================
    # Create Sequences
    # ==========================================
    X_train_seq, y_train_seq = create_sequences(
        X_train_scaled,
        y_train_scaled,
        lookback
    )

    X_valid_seq, y_valid_seq = create_sequences(
        X_valid_scaled,
        y_valid_scaled,
        lookback
    )

    # ==========================================
    # Build Model
    # ==========================================
    model = Sequential()

    model.add(
        Input(
            shape=(
                X_train_seq.shape[1],
                X_train_seq.shape[2]
            )
        )
    )

    model.add(
        LSTM(
            64
        )
    )

    model.add(
        Dropout(0.2)
    )

    model.add(
        Dense(1)
    )

    model.compile(
        optimizer="adam",
        loss="mse"
    )

    # ==========================================
    # Early Stopping
    # ==========================================
    # early_stop = EarlyStopping(
    #     monitor="val_loss",
    #     patience=3,
    #     restore_best_weights=True
    # )

    # ==========================================
    # Train
    # ==========================================
    model.fit(
        X_train_seq,
        y_train_seq,
        validation_data=(
            X_valid_seq,
            y_valid_seq
        ),
        epochs=epochs,
        batch_size=256,
        # callbacks=[early_stop],
        verbose=0
    )

    # ==========================================
    # Predict
    # ==========================================
    y_pred_scaled = model.predict(
        X_valid_seq,
        verbose=0
    )

    # ==========================================
    # Inverse Scaling
    # ==========================================
    y_pred = target_scaler.inverse_transform(
        y_pred_scaled
    )

    y_true = target_scaler.inverse_transform(
        y_valid_seq
    )

    # ==========================================
    # Metrics
    # ==========================================
    mae, rmse, mape, r2 = evaluate_model(
        y_true,
        y_pred
    )
    # K.clear_session()
    # gc.collect()
    return model, mae, rmse,mape, r2

####################################################################3

# ==========================================================
# 4. FEATURE DEFINITIONS
# ==========================================================

SOLAR_FEATURES = [

    "global_radiation",
    "sunshine_duration",
    "solar_zenith_angle",
    "air_temperature",
    "relative_humidity",

    "capacity_photovoltaics_mw",

    "grid_load_mwh",
    "price_eur_per_mwh",

    "hour",
    "month",
    "dayofweek",

    "generation_photovoltaics_mwh_lag_1",
    "generation_photovoltaics_mwh_lag_6",
    "generation_photovoltaics_mwh_lag_24",
    "generation_photovoltaics_mwh_lag_72",
    "generation_photovoltaics_mwh_lag_168",

    "generation_photovoltaics_mwh_roll_mean_24",
    "generation_photovoltaics_mwh_roll_mean_168",
    "generation_photovoltaics_mwh_roll_std_24"
]
####################################
WIND_ON_FEATURES = [

    "wind_speed",
    "wind_dir_sin",
    "wind_dir_cos",

    "air_temperature",
    "relative_humidity",

    "capacity_wind_onshore_mw",

    "grid_load_mwh",
    "price_eur_per_mwh",

    "hour",
    "month",
    "dayofweek",

    "generation_wind_onshore_mwh_lag_1",
    "generation_wind_onshore_mwh_lag_6",
    "generation_wind_onshore_mwh_lag_24",
    "generation_wind_onshore_mwh_lag_72",
    "generation_wind_onshore_mwh_lag_168",

    "generation_wind_onshore_mwh_roll_mean_24",
    "generation_wind_onshore_mwh_roll_mean_168",
    "generation_wind_onshore_mwh_roll_std_24"
]
##################################

WIND_OFF_FEATURES = [

    "wind_speed",
    "wind_dir_sin",
    "wind_dir_cos",

    "air_temperature",
    "relative_humidity",

    "capacity_wind_offshore_mw",

    "grid_load_mwh",
    "price_eur_per_mwh",

    "hour",
    "month",
    "dayofweek",

    "generation_wind_offshore_mwh_lag_1",
    "generation_wind_offshore_mwh_lag_6",
    "generation_wind_offshore_mwh_lag_24",
    "generation_wind_offshore_mwh_lag_72",
    "generation_wind_offshore_mwh_lag_168",

    "generation_wind_offshore_mwh_roll_mean_24",
    "generation_wind_offshore_mwh_roll_mean_168",
    "generation_wind_offshore_mwh_roll_std_24"
]

##############################################
FEATURES = {
    "Solar": SOLAR_FEATURES,
    "Wind_Onshore": WIND_ON_FEATURES,
    "Wind_Offshore": WIND_OFF_FEATURES
}










def get_model_data(
    train_df,
    valid_df,
    test_df,
    target_name,
    horizon
):

    features = FEATURES[target_name]

    target_col = f"target_h{horizon}"

    X_train = train_df[features]
    y_train = train_df[target_col]

    X_valid = valid_df[features]
    y_valid = valid_df[target_col]

    X_test = test_df[features]
    y_test = test_df[target_col]

    return (
        X_train,
        y_train,
        X_valid,
        y_valid,
        X_test,
        y_test
    )

In [25]:
start_time = time.time()

TOTAL_RUNS = (
    len(PERIODS)
    * len(DATASETS)
    * len(HORIZONS)
    * len(EPOCHS_LIST)
)

counter = 1

print(f"Total Experiments = {TOTAL_RUNS}")

for period_name in PERIODS:

    for target_name in DATASETS:

        dataset = DATASETS[target_name]

        train_df, valid_df, test_df = get_period_split(
            dataset,
            period_name
        )

        for horizon in HORIZONS:

            (
                X_train,
                y_train,
                X_valid,
                y_valid,
                X_test,
                y_test
            ) = get_model_data(
                train_df,
                valid_df,
                test_df,
                target_name,
                horizon
            )

            for epochs in EPOCHS_LIST:

                print(
                    f"\n[{counter}/{TOTAL_RUNS}] "
                    f"{period_name} | "
                    f"{target_name} | "
                    f"H{horizon} | "
                    f"Epochs={epochs}"
                )

                model, mae, rmse,mape, r2 = run_lstm(
                    X_train,
                    y_train,
                    X_valid,
                    y_valid,
                    epochs=epochs
                )

                results = add_result(
                    results,
                    period_name,
                    target_name,
                    horizon,
                    epochs,
                    "LSTM",
                    mae,
                    rmse,
                    mape,
                    r2
                )

                results.to_csv(
                    "results/lstm_results.csv",
                    index=False
                )

                K.clear_session()
                gc.collect()

                counter += 1


################################################
end_time = time.time()

print(
    f"Total runtime: "
    f"{(end_time-start_time)/60:.2f} minutes"
)

Total Experiments = 225

[1/225] FULL | Solar | H1 | Epochs=20

[2/225] FULL | Solar | H1 | Epochs=40

[3/225] FULL | Solar | H1 | Epochs=60

[4/225] FULL | Solar | H1 | Epochs=80

[5/225] FULL | Solar | H1 | Epochs=100

[6/225] FULL | Solar | H6 | Epochs=20

[7/225] FULL | Solar | H6 | Epochs=40

[8/225] FULL | Solar | H6 | Epochs=60

[9/225] FULL | Solar | H6 | Epochs=80

[10/225] FULL | Solar | H6 | Epochs=100

[11/225] FULL | Solar | H24 | Epochs=20

[12/225] FULL | Solar | H24 | Epochs=40

[13/225] FULL | Solar | H24 | Epochs=60

[14/225] FULL | Solar | H24 | Epochs=80

[15/225] FULL | Solar | H24 | Epochs=100

[16/225] FULL | Solar | H72 | Epochs=20

[17/225] FULL | Solar | H72 | Epochs=40

[18/225] FULL | Solar | H72 | Epochs=60

[19/225] FULL | Solar | H72 | Epochs=80

[20/225] FULL | Solar | H72 | Epochs=100

[21/225] FULL | Solar | H168 | Epochs=20

[22/225] FULL | Solar | H168 | Epochs=40

[23/225] FULL | Solar | H168 | Epochs=60

[24/225] FULL | Solar | H168 | Epochs=80

[25/225] FULL | Solar | H168 | Epochs=100

[26/225] FULL | Wind_Onshore | H1 | Epochs=20

[27/225] FULL | Wind_Onshore | H1 | Epochs=40

[28/225] FULL | Wind_Onshore | H1 | Epochs=60

[29/225] FULL | Wind_Onshore | H1 | Epochs=80

[30/225] FULL | Wind_Onshore | H1 | Epochs=100

[31/225] FULL | Wind_Onshore | H6 | Epochs=20

[32/225] FULL | Wind_Onshore | H6 | Epochs=40

[33/225] FULL | Wind_Onshore | H6 | Epochs=60

[34/225] FULL | Wind_Onshore | H6 | Epochs=80

[35/225] FULL | Wind_Onshore | H6 | Epochs=100

[36/225] FULL | Wind_Onshore | H24 | Epochs=20

[37/225] FULL | Wind_Onshore | H24 | Epochs=40

[38/225] FULL | Wind_Onshore | H24 | Epochs=60

[39/225] FULL | Wind_Onshore | H24 | Epochs=80

[40/225] FULL | Wind_Onshore | H24 | Epochs=100

[41/225] FULL | Wind_Onshore | H72 | Epochs=20

[42/225] FULL | Wind_Onshore | H72 | Epochs=40

[43/225] FULL | Wind_Onshore | H72 | Epochs=60

[44/225] FULL | Wind_Onshore | H72 | Epochs=80

[45/225] FULL | Wind_Onshore | H72 | Epochs=100

[46/225] FULL | Wind_Onshore | H168 | Epochs=20

[47/225] FULL | Wind_Onshore | H168 | Epochs=40

[48/225] FULL | Wind_Onshore | H168 | Epochs=60

[49/225] FULL | Wind_Onshore | H168 | Epochs=80

[50/225] FULL | Wind_Onshore | H168 | Epochs=100

[51/225] FULL | Wind_Offshore | H1 | Epochs=20

[52/225] FULL | Wind_Offshore | H1 | Epochs=40

[53/225] FULL | Wind_Offshore | H1 | Epochs=60

[54/225] FULL | Wind_Offshore | H1 | Epochs=80

[55/225] FULL | Wind_Offshore | H1 | Epochs=100

[56/225] FULL | Wind_Offshore | H6 | Epochs=20

[57/225] FULL | Wind_Offshore | H6 | Epochs=40

[58/225] FULL | Wind_Offshore | H6 | Epochs=60

[59/225] FULL | Wind_Offshore | H6 | Epochs=80

[60/225] FULL | Wind_Offshore | H6 | Epochs=100

[61/225] FULL | Wind_Offshore | H24 | Epochs=20

[62/225] FULL | Wind_Offshore | H24 | Epochs=40

[63/225] FULL | Wind_Offshore | H24 | Epochs=60

[64/225] FULL | Wind_Offshore | H24 | Epochs=80

[65/225] FULL | Wind_Offshore | H24 | Epochs=100

[66/225] FULL | Wind_Offshore | H72 | Epochs=20

[67/225] FULL | Wind_Offshore | H72 | Epochs=40

[68/225] FULL | Wind_Offshore | H72 | Epochs=60

[69/225] FULL | Wind_Offshore | H72 | Epochs=80

[70/225] FULL | Wind_Offshore | H72 | Epochs=100

[71/225] FULL | Wind_Offshore | H168 | Epochs=20

[72/225] FULL | Wind_Offshore | H168 | Epochs=40

[73/225] FULL | Wind_Offshore | H168 | Epochs=60

[74/225] FULL | Wind_Offshore | H168 | Epochs=80

[75/225] FULL | Wind_Offshore | H168 | Epochs=100

[76/225] POST_2020 | Solar | H1 | Epochs=20

[77/225] POST_2020 | Solar | H1 | Epochs=40

[78/225] POST_2020 | Solar | H1 | Epochs=60

[79/225] POST_2020 | Solar | H1 | Epochs=80

[80/225] POST_2020 | Solar | H1 | Epochs=100

[81/225] POST_2020 | Solar | H6 | Epochs=20

[82/225] POST_2020 | Solar | H6 | Epochs=40

[83/225] POST_2020 | Solar | H6 | Epochs=60

[84/225] POST_2020 | Solar | H6 | Epochs=80

[85/225] POST_2020 | Solar | H6 | Epochs=100

[86/225] POST_2020 | Solar | H24 | Epochs=20

[87/225] POST_2020 | Solar | H24 | Epochs=40

[88/225] POST_2020 | Solar | H24 | Epochs=60

[89/225] POST_2020 | Solar | H24 | Epochs=80

[90/225] POST_2020 | Solar | H24 | Epochs=100

[91/225] POST_2020 | Solar | H72 | Epochs=20

[92/225] POST_2020 | Solar | H72 | Epochs=40

[93/225] POST_2020 | Solar | H72 | Epochs=60

[94/225] POST_2020 | Solar | H72 | Epochs=80

[95/225] POST_2020 | Solar | H72 | Epochs=100

[96/225] POST_2020 | Solar | H168 | Epochs=20

[97/225] POST_2020 | Solar | H168 | Epochs=40

[98/225] POST_2020 | Solar | H168 | Epochs=60

[99/225] POST_2020 | Solar | H168 | Epochs=80

[100/225] POST_2020 | Solar | H168 | Epochs=100

[101/225] POST_2020 | Wind_Onshore | H1 | Epochs=20

[102/225] POST_2020 | Wind_Onshore | H1 | Epochs=40

[103/225] POST_2020 | Wind_Onshore | H1 | Epochs=60

[104/225] POST_2020 | Wind_Onshore | H1 | Epochs=80

[105/225] POST_2020 | Wind_Onshore | H1 | Epochs=100

[106/225] POST_2020 | Wind_Onshore | H6 | Epochs=20

[107/225] POST_2020 | Wind_Onshore | H6 | Epochs=40

[108/225] POST_2020 | Wind_Onshore | H6 | Epochs=60

[109/225] POST_2020 | Wind_Onshore | H6 | Epochs=80

[110/225] POST_2020 | Wind_Onshore | H6 | Epochs=100

[111/225] POST_2020 | Wind_Onshore | H24 | Epochs=20

[112/225] POST_2020 | Wind_Onshore | H24 | Epochs=40

[113/225] POST_2020 | Wind_Onshore | H24 | Epochs=60

[114/225] POST_2020 | Wind_Onshore | H24 | Epochs=80

[115/225] POST_2020 | Wind_Onshore | H24 | Epochs=100

[116/225] POST_2020 | Wind_Onshore | H72 | Epochs=20

[117/225] POST_2020 | Wind_Onshore | H72 | Epochs=40

[118/225] POST_2020 | Wind_Onshore | H72 | Epochs=60

[119/225] POST_2020 | Wind_Onshore | H72 | Epochs=80

[120/225] POST_2020 | Wind_Onshore | H72 | Epochs=100

[121/225] POST_2020 | Wind_Onshore | H168 | Epochs=20

[122/225] POST_2020 | Wind_Onshore | H168 | Epochs=40

[123/225] POST_2020 | Wind_Onshore | H168 | Epochs=60

[124/225] POST_2020 | Wind_Onshore | H168 | Epochs=80

[125/225] POST_2020 | Wind_Onshore | H168 | Epochs=100

[126/225] POST_2020 | Wind_Offshore | H1 | Epochs=20

[127/225] POST_2020 | Wind_Offshore | H1 | Epochs=40

[128/225] POST_2020 | Wind_Offshore | H1 | Epochs=60

[129/225] POST_2020 | Wind_Offshore | H1 | Epochs=80

[130/225] POST_2020 | Wind_Offshore | H1 | Epochs=100

[131/225] POST_2020 | Wind_Offshore | H6 | Epochs=20

[132/225] POST_2020 | Wind_Offshore | H6 | Epochs=40

[133/225] POST_2020 | Wind_Offshore | H6 | Epochs=60

[134/225] POST_2020 | Wind_Offshore | H6 | Epochs=80

[135/225] POST_2020 | Wind_Offshore | H6 | Epochs=100

[136/225] POST_2020 | Wind_Offshore | H24 | Epochs=20

[137/225] POST_2020 | Wind_Offshore | H24 | Epochs=40

[138/225] POST_2020 | Wind_Offshore | H24 | Epochs=60

[139/225] POST_2020 | Wind_Offshore | H24 | Epochs=80

[140/225] POST_2020 | Wind_Offshore | H24 | Epochs=100

[141/225] POST_2020 | Wind_Offshore | H72 | Epochs=20

[142/225] POST_2020 | Wind_Offshore | H72 | Epochs=40

[143/225] POST_2020 | Wind_Offshore | H72 | Epochs=60

[144/225] POST_2020 | Wind_Offshore | H72 | Epochs=80

[145/225] POST_2020 | Wind_Offshore | H72 | Epochs=100

[146/225] POST_2020 | Wind_Offshore | H168 | Epochs=20

[147/225] POST_2020 | Wind_Offshore | H168 | Epochs=40

[148/225] POST_2020 | Wind_Offshore | H168 | Epochs=60

[149/225] POST_2020 | Wind_Offshore | H168 | Epochs=80

[150/225] POST_2020 | Wind_Offshore | H168 | Epochs=100

[151/225] POST_2021 | Solar | H1 | Epochs=20

[152/225] POST_2021 | Solar | H1 | Epochs=40

[153/225] POST_2021 | Solar | H1 | Epochs=60

[154/225] POST_2021 | Solar | H1 | Epochs=80

[155/225] POST_2021 | Solar | H1 | Epochs=100

[156/225] POST_2021 | Solar | H6 | Epochs=20

[157/225] POST_2021 | Solar | H6 | Epochs=40

[158/225] POST_2021 | Solar | H6 | Epochs=60

[159/225] POST_2021 | Solar | H6 | Epochs=80

[160/225] POST_2021 | Solar | H6 | Epochs=100

[161/225] POST_2021 | Solar | H24 | Epochs=20

[162/225] POST_2021 | Solar | H24 | Epochs=40

[163/225] POST_2021 | Solar | H24 | Epochs=60

[164/225] POST_2021 | Solar | H24 | Epochs=80

[165/225] POST_2021 | Solar | H24 | Epochs=100

[166/225] POST_2021 | Solar | H72 | Epochs=20

[167/225] POST_2021 | Solar | H72 | Epochs=40

[168/225] POST_2021 | Solar | H72 | Epochs=60

[169/225] POST_2021 | Solar | H72 | Epochs=80

[170/225] POST_2021 | Solar | H72 | Epochs=100

[171/225] POST_2021 | Solar | H168 | Epochs=20

[172/225] POST_2021 | Solar | H168 | Epochs=40

[173/225] POST_2021 | Solar | H168 | Epochs=60

[174/225] POST_2021 | Solar | H168 | Epochs=80

[175/225] POST_2021 | Solar | H168 | Epochs=100

[176/225] POST_2021 | Wind_Onshore | H1 | Epochs=20

[177/225] POST_2021 | Wind_Onshore | H1 | Epochs=40

[178/225] POST_2021 | Wind_Onshore | H1 | Epochs=60

[179/225] POST_2021 | Wind_Onshore | H1 | Epochs=80

[180/225] POST_2021 | Wind_Onshore | H1 | Epochs=100

[181/225] POST_2021 | Wind_Onshore | H6 | Epochs=20

[182/225] POST_2021 | Wind_Onshore | H6 | Epochs=40

[183/225] POST_2021 | Wind_Onshore | H6 | Epochs=60

[184/225] POST_2021 | Wind_Onshore | H6 | Epochs=80

[185/225] POST_2021 | Wind_Onshore | H6 | Epochs=100

[186/225] POST_2021 | Wind_Onshore | H24 | Epochs=20

[187/225] POST_2021 | Wind_Onshore | H24 | Epochs=40

[188/225] POST_2021 | Wind_Onshore | H24 | Epochs=60

[189/225] POST_2021 | Wind_Onshore | H24 | Epochs=80

[190/225] POST_2021 | Wind_Onshore | H24 | Epochs=100

[191/225] POST_2021 | Wind_Onshore | H72 | Epochs=20

[192/225] POST_2021 | Wind_Onshore | H72 | Epochs=40

[193/225] POST_2021 | Wind_Onshore | H72 | Epochs=60

[194/225] POST_2021 | Wind_Onshore | H72 | Epochs=80

[195/225] POST_2021 | Wind_Onshore | H72 | Epochs=100

[196/225] POST_2021 | Wind_Onshore | H168 | Epochs=20

[197/225] POST_2021 | Wind_Onshore | H168 | Epochs=40

[198/225] POST_2021 | Wind_Onshore | H168 | Epochs=60

[199/225] POST_2021 | Wind_Onshore | H168 | Epochs=80

[200/225] POST_2021 | Wind_Onshore | H168 | Epochs=100

[201/225] POST_2021 | Wind_Offshore | H1 | Epochs=20

[202/225] POST_2021 | Wind_Offshore | H1 | Epochs=40

[203/225] POST_2021 | Wind_Offshore | H1 | Epochs=60

[204/225] POST_2021 | Wind_Offshore | H1 | Epochs=80

[205/225] POST_2021 | Wind_Offshore | H1 | Epochs=100

[206/225] POST_2021 | Wind_Offshore | H6 | Epochs=20

[207/225] POST_2021 | Wind_Offshore | H6 | Epochs=40

[208/225] POST_2021 | Wind_Offshore | H6 | Epochs=60

[209/225] POST_2021 | Wind_Offshore | H6 | Epochs=80

[210/225] POST_2021 | Wind_Offshore | H6 | Epochs=100

[211/225] POST_2021 | Wind_Offshore | H24 | Epochs=20

[212/225] POST_2021 | Wind_Offshore | H24 | Epochs=40

[213/225] POST_2021 | Wind_Offshore | H24 | Epochs=60

[214/225] POST_2021 | Wind_Offshore | H24 | Epochs=80

[215/225] POST_2021 | Wind_Offshore | H24 | Epochs=100

[216/225] POST_2021 | Wind_Offshore | H72 | Epochs=20

[217/225] POST_2021 | Wind_Offshore | H72 | Epochs=40

[218/225] POST_2021 | Wind_Offshore | H72 | Epochs=60

[219/225] POST_2021 | Wind_Offshore | H72 | Epochs=80

[220/225] POST_2021 | Wind_Offshore | H72 | Epochs=100

[221/225] POST_2021 | Wind_Offshore | H168 | Epochs=20

[222/225] POST_2021 | Wind_Offshore | H168 | Epochs=40

[223/225] POST_2021 | Wind_Offshore | H168 | Epochs=60

[224/225] POST_2021 | Wind_Offshore | H168 | Epochs=80

[225/225] POST_2021 | Wind_Offshore | H168 | Epochs=100
Total runtime: 1982.24 minutes

In [29]:
lstm_results_df = pd.read_csv("results/lstm_results.csv")
lstm_results_df

,Period,Target,Horizon,Epochs,Model,MAE,RMSE,MAPE,R2
0,FULL,Solar,1,20,LSTM,602.603506,1020.352217,1.461434e+03,0.989252
1,FULL,Solar,1,40,LSTM,442.585734,797.031427,1.025014e+03,0.993442
2,FULL,Solar,1,60,LSTM,433.569274,780.562896,6.515794e+02,0.993710
3,FULL,Solar,1,80,LSTM,422.977549,758.602883,6.653812e+02,0.994059
4,FULL,Solar,1,100,LSTM,416.559941,758.939807,9.254263e+02,0.994054
...,...,...,...,...,...,...,...,...,...
220,POST_2021,Wind_Offshore,168,20,LSTM,1657.037239,1978.620951,3.172745e+10,-0.101546
221,POST_2021,Wind_Offshore,168,40,LSTM,1923.321616,2397.456096,2.592488e+10,-0.617255
222,POST_2021,Wind_Offshore,168,60,LSTM,1846.683348,2301.167081,2.646914e+10,-0.489957
223,POST_2021,Wind_Offshore,168,80,LSTM,1862.503082,2318.059423,3.779020e+10,-0.511912
224,POST_2021,Wind_Offshore,168,100,LSTM,1910.971308,2401.109731,2.823387e+10,-0.622188

In [32]:
# ==========================================================
# BEST EPOCH PER PERIOD + TARGET + HORIZON
# ==========================================================

best_epochs = lstm_results_df.loc[
    lstm_results_df.groupby(
        ["Period", "Target", "Horizon"]
    )["RMSE"].idxmin()
].reset_index(drop=True)

best_epochs

,Period,Target,Horizon,Epochs,Model,MAE,RMSE,MAPE,R2
0,FULL,Solar,1,80,LSTM,422.977549,758.602883,6.653812e+02,0.994059
1,FULL,Solar,6,40,LSTM,1176.750211,2156.634335,2.678298e+03,0.951984
2,FULL,Solar,24,20,LSTM,1505.825810,2841.549972,2.001145e+03,0.916642
3,FULL,Solar,72,20,LSTM,2232.319667,3695.451194,1.099257e+04,0.859017
4,FULL,Solar,168,20,LSTM,2165.183462,4092.128412,3.390104e+03,0.827150
5,FULL,Wind_Offshore,1,60,LSTM,534.698492,737.371844,2.124459e+08,0.837335
6,FULL,Wind_Offshore,6,20,LSTM,983.611508,1276.898913,6.824792e+08,0.512382
7,FULL,Wind_Offshore,24,20,LSTM,1498.543132,1865.873582,4.292729e+09,-0.043839
8,FULL,Wind_Offshore,72,20,LSTM,1668.188934,2029.568156,5.431591e+09,-0.236828
9,FULL,Wind_Offshore,168,20,LSTM,1649.510638,2030.450243,7.548251e+09,-0.250306
10,FULL,Wind_Onshore,1,60,LSTM,1146.448457,1590.641954,1.536988e+01,0.977224
11,FULL,Wind_Onshore,6,20,LSTM,2948.211863,3957.265214,3.820573e+01,0.859145
12,FULL,Wind_Onshore,24,20,LSTM,7109.680493,9429.403225,1.233745e+02,0.201266
13,FULL,Wind_Onshore,72,20,LSTM,8409.602807,11254.669869,1.334665e+02,-0.135385
14,FULL,Wind_Onshore,168,20,LSTM,8919.392045,11935.248111,1.414783e+02,-0.284578
15,POST_2020,Solar,1,80,LSTM,620.329050,1033.480505,1.149089e+03,0.991140
16,POST_2020,Solar,6,60,LSTM,1587.466666,2750.830859,3.568111e+03,0.937231
17,POST_2020,Solar,24,20,LSTM,1929.983499,3316.071824,5.333717e+03,0.908771
18,POST_2020,Solar,72,20,LSTM,2150.139327,4046.133217,2.560647e+03,0.864181
19,POST_2020,Solar,168,20,LSTM,2399.472100,4506.557924,2.673349e+03,0.831492
20,POST_2020,Wind_Offshore,1,80,LSTM,577.209406,784.428750,7.474952e+08,0.826935
21,POST_2020,Wind_Offshore,6,20,LSTM,1057.312779,1338.180970,6.829538e+09,0.496293
22,POST_2020,Wind_Offshore,24,20,LSTM,1545.741978,1888.124178,4.718165e+10,-0.005137
23,POST_2020,Wind_Offshore,72,20,LSTM,1627.463082,1947.907282,3.321968e+10,-0.062800
24,POST_2020,Wind_Offshore,168,20,LSTM,1816.135335,2202.833325,3.695963e+10,-0.365339
25,POST_2020,Wind_Onshore,1,80,LSTM,1191.469693,1633.999328,1.656183e+01,0.973563
26,POST_2020,Wind_Onshore,6,20,LSTM,3258.030214,4345.127114,4.891370e+01,0.813410
27,POST_2020,Wind_Onshore,24,20,LSTM,7350.220742,9644.055135,1.799687e+02,0.087290
28,POST_2020,Wind_Onshore,72,20,LSTM,8535.930913,11208.861725,2.323318e+02,-0.247253
29,POST_2020,Wind_Onshore,168,80,LSTM,9306.060507,12076.587726,2.229077e+02,-0.396625
30,POST_2021,Solar,1,100,LSTM,543.756034,992.386921,5.262359e+02,0.991831
31,POST_2021,Solar,6,20,LSTM,1650.943641,2844.547382,3.112483e+03,0.932881
32,POST_2021,Solar,24,20,LSTM,2018.252282,3353.999821,6.180330e+03,0.906672
33,POST_2021,Solar,72,40,LSTM,2514.615138,4403.040956,7.019557e+03,0.839163
34,POST_2021,Solar,168,20,LSTM,2804.902743,5230.695799,3.315361e+03,0.772988
35,POST_2021,Wind_Offshore,1,40,LSTM,587.625116,789.077840,1.131643e+09,0.824877
36,POST_2021,Wind_Offshore,6,20,LSTM,1086.660005,1348.120765,1.167434e+10,0.488782
37,POST_2021,Wind_Offshore,24,20,LSTM,1603.645099,1991.331903,4.354556e+10,-0.118024
38,POST_2021,Wind_Offshore,72,20,LSTM,1754.013728,2157.616084,3.838454e+10,-0.303957
39,POST_2021,Wind_Offshore,168,20,LSTM,1657.037239,1978.620951,3.172745e+10,-0.101546
40,POST_2021,Wind_Onshore,1,80,LSTM,1233.939784,1682.037051,1.813876e+01,0.971985
41,POST_2021,Wind_Onshore,6,20,LSTM,3483.921979,4614.735280,5.411853e+01,0.789537
42,POST_2021,Wind_Onshore,24,20,LSTM,8612.097305,10840.207167,2.339190e+02,-0.153158
43,POST_2021,Wind_Onshore,72,20,LSTM,8578.492340,11160.076300,2.511021e+02,-0.236420
44,POST_2021,Wind_Onshore,168,20,LSTM,9997.656042,12308.435807,2.695247e+02,-0.450765